{
  "name": "QUAN TRI TAI CHINH",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_e7fc6338-213c-444d-aa35-a5b23cf5d435",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "9272d2c2-a26f-4ec0-891f-918a505cf3d6",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "ede3719a-3c32-4356-9ca8-58b5280b1821",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "638bc8e1-9613-46f5-aaad-f7ac31340a0d",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "5cbe1e4b-b33a-4b6d-8d52-872f8e6b08f4",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "d41884ab-e8be-4909-90b5-e9fe9b945491",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "edf00987-64e9-4837-a2d5-f766772d6937",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "1cc25e68-965c-4741-ac79-c0b873dcf46f",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "7caaf229-da64-4fc7-a641-d00a639d45c3",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_e7fc6338-213c-444d-aa35-a5b23cf5d435",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "a82b116e-7b7b-456d-a0e2-53bce01cfd79",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "c7eee447-aa8c-40d2-b134-68fb3a38b55e"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "8f720aef-41dd-47bb-b98b-160e54d88481"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "231f705b-eaee-4b2a-83fc-c4bcd4fd6d31"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "ccbb8151-8e9d-44bd-9fd8-0843c3bbdffb"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ]
      },
      {
        "name": "metrics",
        "lineageTag": "6beba09e-beb3-4c38-b78e-b54c0b6dfe41",
        "partitions": [
          {
            "name": "metrics",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "1.Doanh thu thuần",
            "expression": "CALCULATE([Total KQKD], 'A1_KQKD (month)'[id] = 3)",
            "formatString": "#,0",
            "lineageTag": "d728a0e1-f414-4ae2-8a6b-d8eafb4eb436",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Total KQKD",
            "expression": "SUM('A1_KQKD (month)'[Value]) /10^9",
            "formatString": "#,0",
            "lineageTag": "471b1be4-ba4d-4ee1-9d6b-e322c5213664",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "2.Giá vốn hàng bán",
            "expression": "CALCULATE([Total KQKD], 'A1_KQKD (month)'[id] =4)",
            "formatString": "#,0",
            "lineageTag": "a1839b93-4ce4-4b71-86ff-498002a3c75f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "3.Lợi nhuận sau thuế",
            "expression": "CALCULATE([Total KQKD], 'A1_KQKD (month)'[id] =17)",
            "formatString": "#,0",
            "lineageTag": "56256ccc-8737-488d-aa05-67da2e12b367",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "4.Tỷ suất lợi nhuận%",
            "expression": "DIVIDE([3.Lợi nhuận sau thuế], [1.Doanh thu thuần], 0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "2c8d4e43-49f9-44f6-8455-62dfc665d176"
          },
          {
            "name": "1.Doanh thu thuần LM",
            "expression": "CALCULATE([1.Doanh thu thuần], DATEADD(Dates_ref[Date], -1, MONTH))",
            "formatString": "#,0",
            "lineageTag": "f319fa0c-af2d-4bf4-9f60-f3aa20184866",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "1.Doanh thu thuần vs LM %",
            "expression": [
              "",
              "VAR LM = CALCULATE([1.Doanh thu thuần], DATEADD(Dates_ref[Date], -1, MONTH))",
              "VAR kb= DIVIDE([1.Doanh thu thuần] - LM,LM,0)",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb < 0, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = 0, \"-\", // UNICHAR ( 8660 ),",
              "kb > 0, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return FORMAT ( kb, \"0%\" ) & \" \" & Arrow"
            ],
            "lineageTag": "ac2d89be-7c8b-4ffc-b14b-b67128447651"
          },
          {
            "name": "1.Doanh thu thuần TY",
            "expression": "CALCULATE([1.Doanh thu thuần], YEAR(Dates_ref[Date]) = YEAR(TODAY()))",
            "formatString": "#,0",
            "lineageTag": "0ba2f6c1-5aaa-4e75-bf8d-3795d19a5387",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "1.Doanh thu thuần LY",
            "expression": "CALCULATE([1.Doanh thu thuần], SAMEPERIODLASTYEAR(Dates_ref[Date]))",
            "formatString": "#,0",
            "lineageTag": "6be8d8ec-f2d2-414c-83b9-daf32c519e12",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "2.Giá vốn vs LM % _",
            "expression": [
              "",
              "VAR LM = CALCULATE([2.Giá vốn hàng bán], DATEADD(Dates_ref[Date], -1, MONTH))",
              "VAR kb= DIVIDE([2.Giá vốn hàng bán] - LM,LM,0)",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb < 0, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = 0, \"-\", // UNICHAR ( 8660 ),",
              "kb > 0, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return FORMAT ( kb, \"0%\" ) & \" \" & Arrow"
            ],
            "lineageTag": "7154b272-d972-4a2b-bc7c-a120016da8b1"
          },
          {
            "name": "5.Tổng thu viện phí",
            "expression": "CALCULATE(sum(TTVP_Tuan[Tổng thu viện phí]))",
            "formatString": "0",
            "lineageTag": "58af7e93-aadf-44f5-becc-3bc6b7943e4f"
          },
          {
            "name": "5.1 LW-Tổng thu viện phí",
            "expression": [
              "CALCULATE([5.Tổng thu viện phí],DATEADD(Dates_ref[Date], -7, DAY))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f9888ebf-6537-49a6-88ca-bd26a3ffb393"
          },
          {
            "name": "5.2 %.change",
            "expression": [
              "",
              "VAR select_week = SELECTEDVALUE(TTVP_Tuan[Tuần])",
              "Var lw = CALCULATE([5.Tổng thu viện phí], (TTVP_Tuan[Tuần] = select_week - 1))",
              "var kb= IFERROR([5.Tổng thu viện phí]/lw-1,0)",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb < 0, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = 0, \"-\", // UNICHAR ( 8660 ),",
              "kb > 0, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return FORMAT ( kb, \"0%\" ) & \" \" & Arrow"
            ],
            "lineageTag": "3aae1edc-09dc-457e-80a6-a0aadc1c7669"
          },
          {
            "name": "6.Khám bệnh",
            "expression": "CALCULATE(sum(TTVP_Tuan[Khám bệnh]))",
            "formatString": "0",
            "lineageTag": "3840539e-599c-4e51-80de-bd6e66838803"
          },
          {
            "name": "6.%vs_KB_lw",
            "expression": [
              "",
              "VAR LW_number = SELECTEDVALUE(TTVP_Tuan[Tuần])",
              "var lw = CALCULATE([6.Khám bệnh],(TTVP_Tuan[Tuần]  = LW_number - 1))",
              "var kb= IFERROR([6.Khám bệnh]/lw-1,0)",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb < 0, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = 0, \"-\", // UNICHAR ( 8660 ),",
              "kb > 0, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return FORMAT ( kb, \"0%\" ) & \"\" & Arrow"
            ],
            "lineageTag": "320ab1c0-aa1f-4fea-accf-b0e47fa661ac"
          },
          {
            "name": "7.Nhà thuốc",
            "expression": "CALCULATE(sum(TTVP_Tuan[Nhà thuốc]))",
            "formatString": "0",
            "lineageTag": "8f904372-0d7d-4c44-8dde-28153ab43f93"
          },
          {
            "name": "7.%vs_NT_lw",
            "expression": [
              "",
              "VAR LW_number = SELECTEDVALUE(TTVP_Tuan[Tuần])",
              "var lw = CALCULATE([7.Nhà thuốc],(TTVP_Tuan[Tuần]  = LW_number - 1))",
              "var kb= IFERROR([7.Nhà thuốc]/lw-1,0)",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb < 0, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = 0, \"-\", // UNICHAR ( 8660 ),",
              "kb > 0, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return FORMAT ( kb, \"0%\" ) & \" \" & Arrow"
            ],
            "lineageTag": "5fa5bb77-04e1-4346-9357-bff9adb648a8"
          },
          {
            "name": "8.Cận lâm sàn",
            "expression": "CALCULATE(SUM(TTVP_Tuan[Cận lâm sàng]))",
            "formatString": "0",
            "lineageTag": "d419f700-3d9d-4eda-b2eb-82c3f2579f41"
          },
          {
            "name": "8.%vs_CLS_lw",
            "expression": [
              "",
              "VAR LW_number = SELECTEDVALUE(TTVP_Tuan[Tuần])",
              "var lw = CALCULATE([8.Cận lâm sàn],(TTVP_Tuan[Tuần]  = LW_number - 1))",
              "var kb= IFERROR([8.Cận lâm sàn]/lw-1,0)",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb < 0, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = 0, \"-\", // UNICHAR ( 8660 ),",
              "kb > 0, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return FORMAT ( kb, \"0%\" ) & \" \" & Arrow"
            ],
            "lineageTag": "18cb7e71-acbb-473d-a256-d55ac5e101a1"
          },
          {
            "name": "9.Phẫu thuật, thủ thuật",
            "expression": "CALCULATE(SUM(TTVP_Tuan[Phẫu thuật, thủ thuật]))",
            "formatString": "0",
            "lineageTag": "af38f950-c6cd-4841-a5d0-7d9dfb3ec3f5"
          },
          {
            "name": "9.%vs_PTTT_lw",
            "expression": [
              "",
              "VAR LW_number = SELECTEDVALUE(TTVP_Tuan[Tuần])",
              "var lw = CALCULATE([9.Phẫu thuật, thủ thuật], (TTVP_Tuan[Tuần]  = LW_number - 1))",
              "var kb= IFERROR([9.Phẫu thuật, thủ thuật]/lw-1,0)",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb < 0, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = 0, \"-\", // UNICHAR ( 8660 ),",
              "kb > 0, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return FORMAT ( kb, \"0%\" ) & \" \" & Arrow"
            ],
            "lineageTag": "c4dffae8-27e4-485a-a61d-cc0b7bb5a0a3"
          },
          {
            "name": "10.Ngày giường",
            "expression": "CALCULATE(SUM(TTVP_Tuan[Ngày giường]))",
            "formatString": "0",
            "lineageTag": "c4022756-697f-4c04-a747-11ec3cd51258"
          },
          {
            "name": "10.%vs_NG_lw",
            "expression": [
              "",
              "VAR LW_number = SELECTEDVALUE(TTVP_Tuan[Tuần])",
              "var lw = CALCULATE([10.Ngày giường],(TTVP_Tuan[Tuần]  = LW_number - 1))",
              "var kb= IFERROR([10.Ngày giường]/lw-1,0)",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb < 0, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = 0, \"-\", // UNICHAR ( 8660 ),",
              "kb > 0, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return FORMAT ( kb, \"0%\" ) & \" \" & Arrow"
            ],
            "lineageTag": "96605ce1-4579-4b72-8406-f6950e034d32"
          },
          {
            "name": "@Avg Rev by Day",
            "expression": "CALCULATE(AVERAGE(DoanhThu_Thang[Tháng 7]))",
            "formatString": "#,0.0",
            "lineageTag": "2b5fecfc-6443-4fe5-a605-a8757d658e70"
          },
          {
            "name": "lw",
            "expression": "CALCULATE([Total KQKD],'A1_KQKD (month)'[id] = 4,DATEADD(Dates_ref[Date], -1, MONTH))",
            "lineageTag": "79e720a2-be37-45ac-8656-633f458b9faa",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "11.%vs_LNST_LM",
            "expression": [
              "",
              "VAR LM = CALCULATE([3.Lợi nhuận sau thuế], DATEADD(Dates_ref[Date], -1, MONTH))",
              "VAR kb= DIVIDE([3.Lợi nhuận sau thuế] - LM,LM,0)",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb < 0, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = 0, \"-\", // UNICHAR ( 8660 ),",
              "kb > 0, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return FORMAT ( kb, \"0%\" ) & \" \" & Arrow"
            ],
            "lineageTag": "9608c885-15c2-4e74-9fca-6e61b3db5198"
          },
          {
            "name": "12.Tỷ suất lợi nhuận",
            "expression": "DIVIDE([3.Lợi nhuận sau thuế],[1.Doanh thu thuần],0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c64be61f-a78a-4c03-86c8-1cddcf699329"
          },
          {
            "name": "12.%vs_TSLN_LM",
            "expression": [
              "",
              "VAR LM = CALCULATE([12.Tỷ suất lợi nhuận], DATEADD(Dates_ref[Date], -1, MONTH))",
              "VAR kb= DIVIDE([12.Tỷ suất lợi nhuận] - LM,LM,0)",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb < 0, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = 0, \"-\", // UNICHAR ( 8660 ),",
              "kb > 0, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return FORMAT ( kb, \"0%\" ) & \" \" & Arrow"
            ],
            "lineageTag": "85d7a28a-9e5f-4951-9368-23addae62dd3"
          },
          {
            "name": "13. Luy Ke doanh thu Thang",
            "expression": [
              "",
              "TOTALYTD(",
              "    [1.Doanh thu thuần],",
              "",
              "        Dates_ref[Date])"
            ],
            "formatString": "#,0",
            "lineageTag": "ff78a1e0-1cde-41db-9092-ccd68e2500f1"
          },
          {
            "name": "1.L7M_ Doanh thu thuần",
            "expression": "CALCULATE([Total KQKD], 'A1_KQKD (month)'[id] =3)",
            "lineageTag": "95bedf36-ea4f-44fa-b50e-5c8b93f1512b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "13.vs.plan DTT",
            "expression": "[13. Luy Ke doanh thu Thang]/ CALCULATE(sum(Forecast[Kế hoạch]),Forecast[Nội dung]=\"Doanh thu kế họach\")",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d5fdceaa-240f-449d-9cfd-94ff62de5959"
          },
          {
            "name": "13. Luy Ke giá vốn Thang",
            "expression": [
              "",
              "",
              "TOTALYTD(",
              "    [2.Giá vốn hàng bán],",
              "",
              "        Dates_ref[Date])"
            ],
            "formatString": "#,0",
            "lineageTag": "3dbdcd65-41a5-495e-aa04-db5d54ac21da",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "13.vs.plan gv",
            "expression": [
              "",
              "var a =CALCULATE(sum(Forecast[Kế hoạch]),Forecast[Nội dung]=\"Giá vốn kế hoạch\")",
              "return",
              "DIVIDE([13. Luy Ke giá vốn Thang],a)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3e934f93-68d8-40db-bc5e-5389c6d67e8f"
          },
          {
            "name": "13.vs.plan lnst",
            "expression": [
              "",
              "var a =CALCULATE(sum(Forecast[Kế hoạch]),Forecast[Nội dung]=\"Lợi nhuận sau thuế\")",
              "return",
              "DIVIDE([13. Luy Ke Loi nhuan sau thue],a)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "75636956-18ee-4957-ba89-2007e00fe931"
          },
          {
            "name": "13. Luy Ke Loi nhuan sau thue",
            "expression": "TOTALYTD( [3.Lợi nhuận sau thuế],Dates_ref[Date])",
            "formatString": "#,0",
            "lineageTag": "b6af57f4-6275-4e9b-90e0-e74598844c4b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "14.%tsln",
            "expression": [
              "",
              "var lnst = CALCULATE(SUM(Forecast[Kế hoạch]), Forecast[Nội dung] =\"Lợi nhuận sau thuế\")",
              "var dtkh = CALCULATE(SUM(Forecast[Kế hoạch]), Forecast[Nội dung] =\"Doanh thu kế họach\")",
              "return DIVIDE(lnst,dtkh)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c7a8c172-86b4-4e0a-a35f-14af20823995"
          },
          {
            "name": "14.%vs. luy ke tsln",
            "expression": "DIVIDE([13. Luy Ke Loi nhuan sau thue],[13. Luy Ke doanh thu Thang])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "e7d8bee7-c36d-4ced-922e-d3341b27d189"
          },
          {
            "name": "space",
            "expression": "0.001",
            "formatString": "0",
            "lineageTag": "3e09fe6f-3752-48ba-b1d4-4b96ed934ef7"
          },
          {
            "name": "2.Dubaohoatdong_highlight",
            "expression": [
              "",
              "    var _val = SELECTEDVALUE('A1_KQKD (month)'[Month])",
              "    var _result = IF(_val = VALUES('A1_KQKD (month)'[Month]), \"RED\", \"BLACK\")",
              "    return _result"
            ],
            "lineageTag": "c62451ce-e9cf-47ae-b772-e25495b4b9eb"
          },
          {
            "name": "1.Highlight Doanh thu thuần",
            "expression": [
              "",
              "var abc = SELECTEDVALUE(Dates_ref[MonthInCalendar])",
              "return abc"
            ],
            "lineageTag": "3f736e78-8b3d-4be1-9c75-75de89608828"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "Dates_ref",
        "lineageTag": "7f1b47ba-bb8a-4952-96e1-f2463c3ac84d",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date",
            "formatString": "Short Date",
            "lineageTag": "ce5088dc-d5b7-4887-aaf5-474ef08d0e61",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "DateInt",
            "dataType": "double",
            "sourceColumn": "DateInt",
            "formatString": "0",
            "lineageTag": "c6fdf1a8-a094-4cb5-9926-be8891383568",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "double",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "fb5e1b0a-32b1-408b-9103-d67d6766bf13",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ShortYear",
            "dataType": "string",
            "sourceColumn": "ShortYear",
            "lineageTag": "c4e85bf9-a283-4bbe-acf7-14abd8977864",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "QuarterOfYear",
            "dataType": "double",
            "sourceColumn": "QuarterOfYear",
            "formatString": "0",
            "lineageTag": "4673db05-6798-4778-bc04-a93e7acc7ce5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "sortByColumn": "QuarterOfYear",
            "lineageTag": "09141d66-2187-4561-915b-10c9d96473dd",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "QuarterInCalendar",
            "dataType": "string",
            "sourceColumn": "QuarterInCalendar",
            "lineageTag": "805735a5-16cf-4db6-909e-6a19c394b3ce",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "QuarternYear",
            "dataType": "double",
            "sourceColumn": "QuarternYear",
            "formatString": "0",
            "lineageTag": "6b1e02d3-1e80-41e5-be4c-a63f5a2bc4cc",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthOfYear",
            "dataType": "double",
            "sourceColumn": "MonthOfYear",
            "formatString": "0",
            "lineageTag": "b3b72193-6e94-43f8-b467-c3a219ce6348",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "lineageTag": "f8bf5001-79df-48af-9f18-16f4a934346b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthShort",
            "dataType": "string",
            "sourceColumn": "MonthShort",
            "sortByColumn": "MonthOfYear",
            "lineageTag": "44d50fe9-cbe7-4848-b6b6-06388b1726e7",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthInCalendar",
            "dataType": "string",
            "sourceColumn": "MonthInCalendar",
            "sortByColumn": "MonthYear",
            "lineageTag": "2f4c63ec-edd0-4af2-a5ee-7f4367978537",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthnYear",
            "dataType": "double",
            "sourceColumn": "MonthnYear",
            "formatString": "0",
            "lineageTag": "13bc1e60-ef58-4e43-9f49-ef2de213b8a9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "WeekOfYear",
            "dataType": "double",
            "sourceColumn": "WeekOfYear",
            "formatString": "0",
            "lineageTag": "a6459839-2586-4057-b8ac-2f600d827211",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "WeeknYear",
            "dataType": "double",
            "sourceColumn": "WeeknYear",
            "formatString": "0",
            "lineageTag": "2457c27a-f6f5-4d68-827d-0d248a960398",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "WeekOfMonth",
            "dataType": "double",
            "sourceColumn": "WeekOfMonth",
            "formatString": "0",
            "lineageTag": "f7d135ff-1409-46d3-983e-958a4f2c3763",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "WeekStarting",
            "dataType": "dateTime",
            "sourceColumn": "WeekStarting",
            "formatString": "Long Date",
            "lineageTag": "9074fa3e-7e2d-4e05-b685-f32b40a97c6b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "WeekEnding",
            "dataType": "dateTime",
            "sourceColumn": "WeekEnding",
            "formatString": "Long Date",
            "lineageTag": "1c7e2718-31c7-4341-b25b-56fcdb0d84da",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "DayOfMonth",
            "dataType": "double",
            "sourceColumn": "DayOfMonth",
            "formatString": "0",
            "lineageTag": "4f7bff15-6391-4eb7-9af5-75559907e22f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "DayMonth",
            "dataType": "string",
            "sourceColumn": "DayMonth",
            "lineageTag": "b96fdd62-2dcd-485f-abf3-58e3f45e1ec0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DayInWeek",
            "dataType": "double",
            "sourceColumn": "DayInWeek",
            "formatString": "0",
            "lineageTag": "4c3f636a-a78b-440d-ad3c-77049d7566fe",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "DayOfWeekName",
            "dataType": "string",
            "sourceColumn": "DayOfWeekName",
            "lineageTag": "2d0de650-3d0b-415e-906f-22652eb2d231",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "FY",
            "dataType": "string",
            "sourceColumn": "FY",
            "lineageTag": "dfd970d2-616c-42fa-952b-1f98e4f8f82f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "WeekName",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "\"TUẦN \" &Dates_ref[WeekOfYear]",
            "lineageTag": "cde56c52-4d1a-4baf-89e4-e92e5d3a35a3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthYear",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "date(YEAR(Dates_ref[Date]),MONTH(Dates_ref[Date]),1)",
            "formatString": "mm-yyyy",
            "lineageTag": "a178db64-9a83-45df-b748-f235cba4e180",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ]
          },
          {
            "name": "Quarter Index",
            "dataType": "int64",
            "sourceColumn": "Quarter Index",
            "formatString": "0",
            "lineageTag": "d8390bc5-c949-4f19-b35f-a1c65d06af4c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Start of Quarter",
            "dataType": "dateTime",
            "sourceColumn": "Start of Quarter",
            "formatString": "Long Date",
            "lineageTag": "3e3cf2db-c842-445c-832b-432fe96d4c6e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "End of Quarter",
            "dataType": "dateTime",
            "sourceColumn": "End of Quarter",
            "formatString": "Long Date",
            "lineageTag": "a5fb1cd6-8413-485c-80fc-e3a2b28c4ad4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "MonthShort_Alternative",
            "dataType": "string",
            "sourceColumn": "MonthShort_Alternative",
            "sortByColumn": "MonthName",
            "lineageTag": "ba43651b-ddef-4040-bb71-d067d8670349",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VN_Month",
            "dataType": "string",
            "sourceColumn": "VN_Month",
            "sortByColumn": "MonthOfYear",
            "lineageTag": "9b76f848-d5d0-4191-9098-93b0d9bd067e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "VN_Quarter",
            "dataType": "string",
            "sourceColumn": "VN_Quarter",
            "sortByColumn": "QuarterOfYear",
            "lineageTag": "e8136f78-bfc4-4ab3-90f9-adaf4d595ca6",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NameMonth",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "\"THÁNG \" &Dates_ref[MonthOfYear]",
            "lineageTag": "3ce357b1-5592-4d98-8615-5a69628fff69",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "NOT_Sunday",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "IF(WEEKDAY(Dates_ref[Date],2)>6,0,1)",
            "formatString": "0",
            "lineageTag": "2e7f83af-b735-4a1a-82df-4ffdae876ca8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Dates_ref",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let fnDateTable =",
                "  let",
                "    StartDate = #date(2021, 1, 1),",
                "    Today = DateTime.Date(DateTime.LocalNow()),",
                "    EndDate = Today,",
                "    //Date.EndOfYear(Today),",
                "    //EndDate = #date(2023,8,31),",
                "    FYStartMonth = 1,",
                "    DayCount = Duration.Days(Duration.From(EndDate - StartDate))+1,",
                "    Source = List.Dates(StartDate,DayCount,#duration(1,0,0,0)),",
                "    TableFromList = Table.FromList(Source, Splitter.SplitByNothing(), type table[ Date = Date.Type ]),",
                "    InsertDateInt = Table.AddColumn(TableFromList, \"DateInt\", each Date.Year([Date]) * 10000 + Date.Month([Date]) * 100 + Date.Day([Date]), Int64.Type),",
                "    InsertYear = Table.AddColumn(InsertDateInt, \"Year\", each Date.Year([Date]),Int64.Type),",
                "    InsertShortYear = Table.AddColumn(InsertYear, \"ShortYear\", each Text.End(Text.From([Year]), 2), type text),",
                "    InsertQuarterOfYear = Table.AddColumn(InsertShortYear, \"QuarterOfYear\", each Date.QuarterOfYear([Date]), Int64.Type),",
                "    InsertQuarter = Table.AddColumn(InsertQuarterOfYear, \"Quarter\", each \"Qtr \" & Number.ToText([QuarterOfYear]), type text),",
                "    InsertCalendarQtr = Table.AddColumn(InsertQuarter, \"QuarterInCalendar\", each \"Q\" & Number.ToText([QuarterOfYear]) & \" \" & Number.ToText([Year]), type text),",
                "    InsertQuarternYear = Table.AddColumn(InsertCalendarQtr,\"QuarternYear\", each [Year] * 10000 + [QuarterOfYear]*100, Int64.Type),",
                "    InsertMonth = Table.AddColumn(InsertQuarternYear, \"MonthOfYear\", each Date.Month([Date]), Int64.Type),",
                "    InsertMonthName = Table.AddColumn(InsertMonth, \"MonthName\", each Date.ToText([Date], \"MMMM\"), type text),",
                "    InsertMonthShort = Table.AddColumn(InsertMonthName, \"MonthShort\", each Date.ToText([Date], \"MMM\"), type text),",
                "    InsertCalendarMonth = Table.AddColumn(InsertMonthShort, \"MonthInCalendar\", each (try(Text.Range([MonthName],0,3)) otherwise [MonthName]) & \" \" & Number.ToText([Year]), type text),",
                "    InsertMonthnYear = Table.AddColumn(InsertCalendarMonth,\"MonthnYear\", each [Year] * 10000 + [MonthOfYear]*100, Int64.Type),",
                "    InsertWeekOfYear= Table.AddColumn(InsertMonthnYear, \"WeekOfYear\", each Date.WeekOfYear([Date], Day.Monday), Int64.Type),",
                "    InsertWeeknYear= Table.AddColumn(InsertWeekOfYear, \"WeeknYear\", each [Year] * 10000 + Date.WeekOfYear([Date], Day.Monday)*100, Int64.Type),",
                "    InsertWeekOfMonth= Table.AddColumn(InsertWeeknYear, \"WeekOfMonth\", each [Year] * 10000 + [MonthOfYear]*100 + Date.WeekOfMonth([Date], Day.Monday), Int64.Type),",
                "    InsertWeekStart = Table.AddColumn(InsertWeekOfMonth, \"WeekStarting\", each Date.StartOfWeek([Date], Day.Monday), type date),",
                "    InsertWeekEnding = Table.AddColumn(InsertWeekStart, \"WeekEnding\", each Date.EndOfWeek([Date], Day.Monday), type date),    ",
                "    InsertDay = Table.AddColumn(InsertWeekEnding, \"DayOfMonth\", each Date.Day([Date]), Int64.Type),",
                "    InsertDayMonth = Table.AddColumn(InsertDay, \"DayMonth\", each Date.ToText([Date], \"dd MMM\"), type text),",
                "    InsertDayWeek = Table.AddColumn(InsertDayMonth, \"DayInWeek\", each Date.DayOfWeek([Date], Day.Monday), Int64.Type),",
                "    InsertDayName = Table.AddColumn(InsertDayWeek, \"DayOfWeekName\", each Date.ToText([Date], \"dddd\"), type text),",
                "    AddFY = Table.AddColumn(InsertDayName, \"FY\", each \"FY\"&(if [MonthOfYear]>=FYStartMonth then Text.From(Number.From([ShortYear])+1) else [ShortYear]), type text)",
                "in",
                "    AddFY,",
                "    #\"Inserted Start of Quarter\" = Table.AddColumn(fnDateTable, \"Start of Quarter\", each Date.StartOfQuarter([Date]), type date),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Inserted Start of Quarter\",{\"Date\", \"DateInt\", \"Year\", \"ShortYear\", \"QuarterOfYear\", \"Quarter\", \"QuarterInCalendar\", \"Start of Quarter\", \"QuarternYear\", \"MonthOfYear\", \"MonthName\", \"MonthShort\", \"MonthInCalendar\", \"MonthnYear\", \"WeekOfYear\", \"WeeknYear\", \"WeekOfMonth\", \"WeekStarting\", \"WeekEnding\", \"DayOfMonth\", \"DayMonth\", \"DayInWeek\", \"DayOfWeekName\", \"FY\"}),",
                "    #\"Inserted End of Quarter\" = Table.AddColumn(#\"Reordered Columns\", \"End of Quarter\", each Date.EndOfQuarter([Start of Quarter]), type date),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Inserted End of Quarter\",{\"Date\", \"DateInt\", \"Year\", \"ShortYear\", \"QuarterOfYear\", \"Quarter\", \"QuarterInCalendar\", \"Start of Quarter\", \"End of Quarter\", \"QuarternYear\", \"MonthOfYear\", \"MonthName\", \"MonthShort\", \"MonthInCalendar\", \"MonthnYear\", \"WeekOfYear\", \"WeeknYear\", \"WeekOfMonth\", \"WeekStarting\", \"WeekEnding\", \"DayOfMonth\", \"DayMonth\", \"DayInWeek\", \"DayOfWeekName\", \"FY\"}),",
                "    #\"Grouped Rows\" = Table.Group(#\"Reordered Columns1\", {\"QuarterInCalendar\"}, {{\"Index\", each _, type table [Date=date, DateInt=number, Year=number, ShortYear=text, QuarterOfYear=number, Quarter=text, QuarterInCalendar=text, Start of Quarter=date, End of Quarter=date, QuarternYear=number, MonthOfYear=number, MonthName=text, MonthShort=text, MonthInCalendar=text, MonthnYear=number, WeekOfYear=number, WeeknYear=number, WeekOfMonth=number, WeekStarting=date, WeekEnding=date, DayOfMonth=number, DayMonth=text, DayInWeek=number, DayOfWeekName=text, FY=text]}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Grouped Rows\", \"Index.1\", 0, 1, Int64.Type),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Index\", \"Expand\"}, {\"Index.1\", \"Quarter Index\"}}),",
                "    #\"Expanded Expand\" = Table.ExpandTableColumn(#\"Renamed Columns\", \"Expand\", {\"Date\", \"DateInt\", \"Year\", \"ShortYear\", \"QuarterOfYear\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"QuarternYear\", \"MonthOfYear\", \"MonthName\", \"MonthShort\", \"MonthInCalendar\", \"MonthnYear\", \"WeekOfYear\", \"WeeknYear\", \"WeekOfMonth\", \"WeekStarting\", \"WeekEnding\", \"DayOfMonth\", \"DayMonth\", \"DayInWeek\", \"DayOfWeekName\", \"FY\"}, {\"Date\", \"DateInt\", \"Year\", \"ShortYear\", \"QuarterOfYear\", \"Quarter\", \"Start of Quarter\", \"End of Quarter\", \"QuarternYear\", \"MonthOfYear\", \"MonthName\", \"MonthShort\", \"MonthInCalendar\", \"MonthnYear\", \"WeekOfYear\", \"WeeknYear\", \"WeekOfMonth\", \"WeekStarting\", \"WeekEnding\", \"DayOfMonth\", \"DayMonth\", \"DayInWeek\", \"DayOfWeekName\", \"FY\"}),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Expanded Expand\",{\"Date\", \"DateInt\", \"Year\", \"ShortYear\", \"QuarterOfYear\", \"Quarter\", \"QuarterInCalendar\", \"Quarter Index\", \"Start of Quarter\", \"End of Quarter\", \"QuarternYear\", \"MonthOfYear\", \"MonthName\", \"MonthShort\", \"MonthInCalendar\", \"MonthnYear\", \"WeekOfYear\", \"WeeknYear\", \"WeekOfMonth\", \"WeekStarting\", \"WeekEnding\", \"DayOfMonth\", \"DayMonth\", \"DayInWeek\", \"DayOfWeekName\", \"FY\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Reordered Columns2\",{{\"Date\", Order.Descending}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Sorted Rows\",{{\"Date\", type date}}),",
                "    #\"Sorted Rows1\" = Table.Sort(#\"Changed Type\",{{\"Date\", Order.Ascending}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Sorted Rows1\", \"Custom\", each if Date.Month([Date]) = Date.Month(List.Max(#\"Changed Type\"[Date])) and Date.Year([Date]) = Date.Year(List.Max(#\"Changed Type\"[Date])) then \"Current\" else [MonthShort]),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Added Custom\",{{\"Custom\", \"MonthShort_Alternative\"}}),",
                "    #\"Added Custom Column\" = Table.AddColumn(#\"Renamed Columns1\", \"VN_Month\", each Text.Combine({\"T\", Text.Middle(Text.From([MonthnYear], \"en-US\"), 4, 2)}), type text),",
                "    #\"Inserted Replaced Text\" = Table.AddColumn(#\"Added Custom Column\", \"VN_Quarter\", each Text.Replace([Quarter], \"tr \", \"uý \"), type text),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Inserted Replaced Text\", each true)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "@max_week",
            "expression": "MAXX(TTVP_Tuan,TTVP_Tuan[Tuần])",
            "formatString": "0",
            "lineageTag": "f7cfa25e-fdd7-451c-b808-624bf13ae20d"
          },
          {
            "name": "@max_month",
            "expression": "CALCULATE(MAX('A1_KQKD (month)'[Month]))",
            "formatString": "yyyy-mm",
            "lineageTag": "ebb02344-de22-42e6-a708-b35b18015c02",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "@max_year",
            "expression": "YEAR(MAX((Dates_ref[Date])))",
            "formatString": "0",
            "lineageTag": "1a30a84a-b433-4c55-8652-743a4311d11f"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Select last 4 Quarter",
        "lineageTag": "983e02fa-2692-4da6-bded-c1550ab409fe",
        "columns": [
          {
            "name": "QuarterInCalendar",
            "dataType": "string",
            "sourceColumn": "QuarterInCalendar",
            "sortByColumn": "Index",
            "lineageTag": "43daa1bc-0937-438f-91a1-6f404b92b863",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Start of Quarter",
            "dataType": "dateTime",
            "sourceColumn": "Start of Quarter",
            "formatString": "Long Date",
            "lineageTag": "da8265ed-316b-4d6c-b84e-b4de16e9378f",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "b3d86edb-4ec0-4b58-9f80-e7f36cc26da4",
                "defaultHierarchy": {
                  "table": "LocalDateTable_3e4af95f-1a5a-4b07-911a-35a3156bf2dc",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "End of Quarter",
            "dataType": "dateTime",
            "sourceColumn": "End of Quarter",
            "formatString": "Long Date",
            "lineageTag": "7fb6979d-74dc-440d-9053-c82432e988ff",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "d765c051-4655-457c-97dd-3eab0e59ce9f",
                "defaultHierarchy": {
                  "table": "LocalDateTable_035e6a83-2b8c-4063-b5b0-b7efd8da0d25",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Index",
            "dataType": "int64",
            "sourceColumn": "Index",
            "formatString": "0",
            "lineageTag": "81ec285e-c614-4473-8b36-4a30e812ef6f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quý",
            "dataType": "string",
            "sourceColumn": "Quý",
            "sortByColumn": "Index",
            "lineageTag": "7fd5f0c3-465e-402a-a03e-48bd52cf6b83",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Select last 4 Quarter",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let fnDateTable =",
                "  let",
                "    StartDate = #date(2022, 1, 1),",
                "    Today = DateTime.Date(DateTime.LocalNow()),",
                "    //EndDate = Today,//Date.EndOfYear(Today),",
                "    EndDate = #date(2023,12,31),",
                "    FYStartMonth = 1,",
                "    DayCount = Duration.Days(Duration.From(EndDate - StartDate))+1,",
                "    Source = List.Dates(StartDate,DayCount,#duration(1,0,0,0)),",
                "    TableFromList = Table.FromList(Source, Splitter.SplitByNothing(), type table[ Date = Date.Type ]),",
                "    InsertDateInt = Table.AddColumn(TableFromList, \"DateInt\", each Date.Year([Date]) * 10000 + Date.Month([Date]) * 100 + Date.Day([Date]), Int64.Type),",
                "    InsertYear = Table.AddColumn(InsertDateInt, \"Year\", each Date.Year([Date]),Int64.Type),",
                "    InsertShortYear = Table.AddColumn(InsertYear, \"ShortYear\", each Text.End(Text.From([Year]), 2), type text),",
                "    InsertQuarterOfYear = Table.AddColumn(InsertShortYear, \"QuarterOfYear\", each Date.QuarterOfYear([Date]), Int64.Type),",
                "    InsertQuarter = Table.AddColumn(InsertQuarterOfYear, \"Quarter\", each \"Qtr \" & Number.ToText([QuarterOfYear]), type text),",
                "    InsertCalendarQtr = Table.AddColumn(InsertQuarter, \"QuarterInCalendar\", each \"Q\" & Number.ToText([QuarterOfYear]) & \" \" & Number.ToText([Year]), type text),",
                "    InsertQuarternYear = Table.AddColumn(InsertCalendarQtr,\"QuarternYear\", each [Year] * 10000 + [QuarterOfYear]*100, Int64.Type),",
                "    InsertMonth = Table.AddColumn(InsertQuarternYear, \"MonthOfYear\", each Date.Month([Date]), Int64.Type),",
                "    InsertMonthName = Table.AddColumn(InsertMonth, \"MonthName\", each Date.ToText([Date], \"MMMM\"), type text),",
                "    InsertMonthShort = Table.AddColumn(InsertMonthName, \"MonthShort\", each Date.ToText([Date], \"MMM\"), type text),",
                "    InsertCalendarMonth = Table.AddColumn(InsertMonthShort, \"MonthInCalendar\", each (try(Text.Range([MonthName],0,3)) otherwise [MonthName]) & \" \" & Number.ToText([Year]), type text),",
                "    InsertMonthnYear = Table.AddColumn(InsertCalendarMonth,\"MonthnYear\", each [Year] * 10000 + [MonthOfYear]*100, Int64.Type),",
                "    InsertWeekOfYear= Table.AddColumn(InsertMonthnYear, \"WeekOfYear\", each Date.WeekOfYear([Date], Day.Monday), Int64.Type),",
                "    InsertWeeknYear= Table.AddColumn(InsertWeekOfYear, \"WeeknYear\", each [Year] * 10000 + Date.WeekOfYear([Date], Day.Monday)*100, Int64.Type),",
                "    InsertWeekOfMonth= Table.AddColumn(InsertWeeknYear, \"WeekOfMonth\", each [Year] * 10000 + [MonthOfYear]*100 + Date.WeekOfMonth([Date], Day.Monday), Int64.Type),",
                "    InsertWeekStart = Table.AddColumn(InsertWeekOfMonth, \"WeekStarting\", each Date.StartOfWeek([Date], Day.Monday), type date),",
                "    InsertWeekEnding = Table.AddColumn(InsertWeekStart, \"WeekEnding\", each Date.EndOfWeek([Date], Day.Monday), type date),    ",
                "    InsertDay = Table.AddColumn(InsertWeekEnding, \"DayOfMonth\", each Date.Day([Date]), Int64.Type),",
                "    InsertDayMonth = Table.AddColumn(InsertDay, \"DayMonth\", each Date.ToText([Date], \"dd MMM\"), type text),",
                "    InsertDayWeek = Table.AddColumn(InsertDayMonth, \"DayInWeek\", each Date.DayOfWeek([Date], Day.Monday), Int64.Type),",
                "    InsertDayName = Table.AddColumn(InsertDayWeek, \"DayOfWeekName\", each Date.ToText([Date], \"dddd\"), type text),",
                "    AddFY = Table.AddColumn(InsertDayName, \"FY\", each \"FY\"&(if [MonthOfYear]>=FYStartMonth then Text.From(Number.From([ShortYear])+1) else [ShortYear]), type text)",
                "in",
                "    AddFY,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(fnDateTable,{\"Date\", \"QuarterInCalendar\"}),",
                "    #\"Inserted End of Quarter\" = Table.AddColumn(#\"Removed Other Columns\", \"End of Quarter\", each Date.EndOfQuarter([Date]), type date),",
                "    #\"Inserted Start of Quarter\" = Table.AddColumn(#\"Inserted End of Quarter\", \"Start of Quarter\", each Date.StartOfQuarter([Date]), type date),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Inserted Start of Quarter\", {\"QuarterInCalendar\"}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 0, 1, Int64.Type),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Index\",{\"Date\", \"QuarterInCalendar\", \"Start of Quarter\", \"End of Quarter\", \"Index\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Reordered Columns\",{\"Date\"}),",
                "    #\"Removed Top Rows\" = Table.Skip(#\"Removed Columns\",3),",
                "    #\"Removed Bottom Rows\" = Table.RemoveLastN(#\"Removed Top Rows\",2),",
                "    #\"Added Custom Column\" = Table.AddColumn(#\"Removed Bottom Rows\", \"Quý\", each let splitQuarterInCalendar = Splitter.SplitTextByDelimiter(\"Q\", QuoteStyle.None)([QuarterInCalendar]), splitsplitQuarterInCalendar1 = Splitter.SplitTextByDelimiter(\" \", QuoteStyle.None)(splitQuarterInCalendar{1}?) in Text.Combine({\"Quý \", Text.Combine(splitsplitQuarterInCalendar1, \"/\")}), type text)",
                "in",
                "    #\"Added Custom Column\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Value in 4 quarters",
            "expression": [
              "",
              "Var selectQuarter = MAX('Select last 4 Quarter'[Index])",
              "Return",
              "CALCULATE((sum('2_CĐKT (quy)'[Value])/10^9), Dates_ref[Quarter Index] <= selectQuarter && Dates_ref[Quarter Index] >= (selectQuarter - 3))"
            ],
            "lineageTag": "fd8229c5-3a86-4cad-971a-22571428229e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_3e4af95f-1a5a-4b07-911a-35a3156bf2dc",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "0e8d969a-9d0c-4162-9e7d-1a15649a2dc0",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "b71468af-403c-40e0-89f4-0be2c46f5317",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "9d16fb51-719c-4182-9e9c-e5c51f861863",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "333cdcf0-832b-4d01-94b8-a4c6be5543c3",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "7a27588a-f75f-4061-8c92-8e71048d76d5",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "02b9561b-a5be-4529-9346-36ca3cf77e98",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "adbbb7bf-0afb-4949-b25d-dd3e296458d3",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "c1b01a5f-6035-481e-a2d4-0a8a3ec20ec0",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_3e4af95f-1a5a-4b07-911a-35a3156bf2dc",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Select last 4 Quarter'[Start of Quarter])), 1, 1), Date(Year(MAX('Select last 4 Quarter'[Start of Quarter])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "3fa74208-8fd6-4049-9eac-2488f450f9ca",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "c13dec23-b373-4e64-8730-b890c6fbefa6"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "596d8191-cb40-4b81-91cd-c8f36b3fab04"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "f1a0d100-2f1b-4c1f-9d91-85a95330bbd1"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "6dc33f72-2ec6-4cee-9cd6-550289de3be3"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "LocalDateTable_035e6a83-2b8c-4063-b5b0-b7efd8da0d25",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "2deedecc-0390-4d59-8b45-dfdf0770042a",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "b78e768c-717d-470b-99a5-ee71e153c94a",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "4d94256d-e00d-4366-a3ce-1f924ef51439",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "fd1e9001-f763-49f9-8b85-2e493b47024a",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "e2960bbb-9d21-4037-b56c-bb9e4cdbc839",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "69d7a37f-1731-472a-8249-891aac0a6358",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "9498749a-bbce-410e-a183-5b5c02d7c431",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "688ca03c-a433-411e-96da-972c5fc6252d",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_035e6a83-2b8c-4063-b5b0-b7efd8da0d25",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Select last 4 Quarter'[End of Quarter])), 1, 1), Date(Year(MAX('Select last 4 Quarter'[End of Quarter])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "4e70d1b3-9587-49ed-928c-253420431cda",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "6ec85d1d-c582-456d-a9da-aafaba230deb"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "089c1e0e-fbfe-4f91-8253-bf6a9946f38d"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "0cd2e317-b9e7-48dd-a86f-1e574feae90c"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "201507cb-5022-4a10-83f0-ffd440d7a18f"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "UMC_CDKT",
        "lineageTag": "3c5e721d-fdc5-4685-af2e-b56acacc0b50",
        "columns": [
          {
            "name": "Chỉ tiêu",
            "dataType": "string",
            "sourceColumn": "Chỉ tiêu",
            "lineageTag": "a3ea5133-988d-41a7-9f9c-5fb25b6aa165",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"UMC_CDKT\",\"TableItemName\":\"Chỉ tiêu CDKT (groups)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ]
          },
          {
            "name": "Attribute",
            "dataType": "string",
            "sourceColumn": "Attribute",
            "lineageTag": "e1e06c9b-1591-4b36-b960-33ab83fd63eb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "int64",
            "sourceColumn": "Value",
            "formatString": "0",
            "lineageTag": "76e74313-7b26-4bdc-a294-7a8cf6f00f04",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Chỉ tiêu CDKT (groups)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('UMC_CDKT'[Chỉ tiêu]),",
              "\t\"(Blank)\",",
              "\t'UMC_CDKT'[Chỉ tiêu] IN {\"Hàng Tồn Kho_140\"},",
              "\t\"Hàng Tồn Kho\",",
              "\t'UMC_CDKT'[Chỉ tiêu] IN {\"Các Khoản Phải Thu Ngắn Hạn_130\"},",
              "\t\"Phải thu khách hàng\",",
              "\t'UMC_CDKT'[Chỉ tiêu] IN {\"Quỹ Đầu Tư Phát Triển_418\"},",
              "\t\"Quỹ Đầu Tư Phát Triển\",",
              "\t'UMC_CDKT'[Chỉ tiêu] IN {\"Tiền Và Các Khoản Tương Đương Tiền_110\"},",
              "\t\"Tiền gửi ngân hàng\",",
              "\t'UMC_CDKT'[Chỉ tiêu]",
              ")"
            ],
            "lineageTag": "8d4be7e8-aa60-4c33-92e3-08e8347f3a3c",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "GroupingMetadata",
                "value": {
                  "version": 0,
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "UMC_CDKT"
                          }
                        },
                        "Property": "Chỉ tiêu"
                      }
                    }
                  ]
                }
              }
            ],
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"u\",\"Entity\":\"UMC_CDKT\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"GroupItems\":[{\"DisplayName\":\"(Blank)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"Hàng Tồn Kho\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Hàng Tồn Kho_140'\"}}]]}}},{\"DisplayName\":\"Phải thu khách hàng\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Các Khoản Phải Thu Ngắn Hạn_130'\"}}]]}}},{\"DisplayName\":\"Quỹ Đầu Tư Phát Triển\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Quỹ Đầu Tư Phát Triển_418'\"}}]]}}},{\"DisplayName\":\"Tiền gửi ngân hàng\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Tiền Và Các Khoản Tương Đương Tiền_110'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Value_bill",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "UMC_CDKT[Value]/1000000000",
            "lineageTag": "df1ba8c6-49bf-4c2a-ae5b-e9caa7fb2c29",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Parse",
            "dataType": "dateTime",
            "sourceColumn": "Parse",
            "formatString": "Short Date",
            "lineageTag": "7ad002a0-10a1-4408-888e-493a5b34c846",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "83295c94-57b0-45a9-ad92-d987a622dbc0",
                "defaultHierarchy": {
                  "table": "LocalDateTable_81224034-15ea-4f3b-959e-fc1d6244be47",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "UMC_CDKT",
            "mode": "import",
            "queryGroup": "UMC Raw Data",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DATA\\DATA_FINANCE\\02. CO SO DU LIEU\\02. Bao cao tai chinh - L3_L4_L5_L6_L7.xlsx\"), null, true),",
                "    CDKT1 = Source{[Name=\"CDKT\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(CDKT1, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type text}, {\"Chỉ tiêu\", type text}, {\"Mã số\", type text}, {\"Thuyết minh\", Int64.Type}, {\"Kỳ 1/2021\", Int64.Type}, {\"Kỳ 2/2021\", Int64.Type}, {\"Kỳ 3/2021\", Int64.Type}, {\"Kỳ 4/2021\", Int64.Type}, {\"Kỳ 5/2021\", Int64.Type}, {\"Kỳ 6/2021\", Int64.Type}, {\"Kỳ 7/2021\", Int64.Type}, {\"Kỳ 8/2021\", Int64.Type}, {\"Kỳ 9/2021\", Int64.Type}, {\"Kỳ 10/2021\", Int64.Type}, {\"Kỳ 11/2021\", Int64.Type}, {\"Kỳ 12/2021\", Int64.Type}, {\"Kỳ 1/2022\", Int64.Type}, {\"Kỳ 2/2022\", Int64.Type}, {\"Kỳ 3/2022\", Int64.Type}, {\"Kỳ 4/2022\", Int64.Type}, {\"Kỳ 5/2022\", Int64.Type}, {\"Kỳ 6/2022\", Int64.Type}, {\"Kỳ 7/2022\", Int64.Type}, {\"Kỳ 8/2022\", Int64.Type}, {\"Kỳ 9/2022\", Int64.Type}, {\"Kỳ 10/2022\", Int64.Type}, {\"Kỳ 11/2022\", Int64.Type}, {\"Kỳ 12/2022\", Int64.Type}, {\"Kỳ 1/2023\", Int64.Type}, {\"Kỳ 2/2023\", Int64.Type}, {\"Kỳ 3/2023\", Int64.Type}, {\"Kỳ 4/2023\", Int64.Type}, {\"Kỳ 5/2023\", Int64.Type}, {\"Kỳ 6/2023\", Int64.Type}, {\"Kỳ 7/2023\", Int64.Type}, {\"Kỳ 8/2023\", Int64.Type}, {\"Kỳ 9/2023\", Int64.Type}, {\"Kỳ 10/2023\", Int64.Type}, {\"Kỳ 11/2023\", Int64.Type}, {\"Kỳ 12/2023\", Int64.Type}}),",
                "    #\"Merged Columns\" = Table.CombineColumns(#\"Changed Type\",{\"Chỉ tiêu\", \"Mã số\"},Combiner.CombineTextByDelimiter(\"_\", QuoteStyle.None),\"Chỉ tiêu\"),",
                "    #\"Kept Range of Rows\" = Table.Range(#\"Merged Columns\",1,123),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Kept Range of Rows\", \"Chỉ tiêu\", Splitter.SplitTextByEachDelimiter({\"- \"}, QuoteStyle.Csv, false), {\"Chỉ tiêu.1\", \"Chỉ tiêu.2\"}),",
                "    #\"Split Column by Delimiter1\" = Table.SplitColumn(#\"Split Column by Delimiter\", \"Chỉ tiêu.1\", Splitter.SplitTextByEachDelimiter({\". \"}, QuoteStyle.Csv, false), {\"Chỉ tiêu.1.1\", \"Chỉ tiêu.1.2\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Split Column by Delimiter1\", \"Chỉ tiêu CDKT\", each if [Chỉ tiêu.2] <> null then Text.Proper(Text.BeforeDelimiter([Chỉ tiêu.2], \"(\")) else if [Chỉ tiêu.1.2] <> null then Text.Proper(Text.BeforeDelimiter([Chỉ tiêu.1.2], \"(\")) else Text.Proper(Text.BeforeDelimiter([Chỉ tiêu.1.1], \"(\"))),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Added Custom\",{\"Chỉ tiêu CDKT\", \"Kỳ 1/2021\", \"Kỳ 2/2021\", \"Kỳ 3/2021\", \"Kỳ 4/2021\", \"Kỳ 5/2021\", \"Kỳ 6/2021\", \"Kỳ 7/2021\", \"Kỳ 8/2021\", \"Kỳ 9/2021\", \"Kỳ 10/2021\", \"Kỳ 11/2021\", \"Kỳ 12/2021\", \"Kỳ 1/2022\", \"Kỳ 2/2022\", \"Kỳ 3/2022\", \"Kỳ 4/2022\", \"Kỳ 5/2022\", \"Kỳ 6/2022\", \"Kỳ 7/2022\", \"Kỳ 8/2022\", \"Kỳ 9/2022\", \"Kỳ 10/2022\", \"Kỳ 11/2022\", \"Kỳ 12/2022\", \"Kỳ 1/2023\", \"Kỳ 2/2023\", \"Kỳ 3/2023\", \"Kỳ 4/2023\", \"Kỳ 5/2023\", \"Kỳ 6/2023\", \"Kỳ 7/2023\", \"Kỳ 8/2023\", \"Kỳ 9/2023\", \"Kỳ 10/2023\", \"Kỳ 11/2023\", \"Kỳ 12/2023\"}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Removed Other Columns1\", {\"Chỉ tiêu CDKT\"}, \"Attribute\", \"Value\"),",
                "    #\"Inserted Parsed Date\" = Table.AddColumn(#\"Unpivoted Other Columns\", \"Parse\", each Date.From(DateTimeZone.From(Text.AfterDelimiter([Attribute], \" \"))), type date),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Parsed Date\",{{\"Chỉ tiêu CDKT\", \"Chỉ tiêu\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "UMC_KQKD",
        "lineageTag": "9c9d0b19-73a6-476b-b49f-010ec1d9e12e",
        "columns": [
          {
            "name": "Chỉ tiêu",
            "dataType": "string",
            "sourceColumn": "Chỉ tiêu",
            "lineageTag": "296b095c-89b1-40ab-b7e1-f9c1424f023d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"UMC_KQKD\",\"TableItemName\":\"Chỉ tiêu KQKD (groups)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ]
          },
          {
            "name": "Attribute",
            "dataType": "string",
            "sourceColumn": "Attribute",
            "lineageTag": "9cc0d7be-241d-4dcb-b2f2-d5e73590584e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "lineageTag": "ebd0b224-2a8c-48e8-9d0e-4345f8b4278e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Chỉ tiêu KQKD (groups)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('UMC_KQKD'[Chỉ tiêu]),",
              "\t\"(Blank)\",",
              "\t'UMC_KQKD'[Chỉ tiêu] IN {\"Chi phí  thuê xét nghiệm ĐHYD - Medic... liên quan KCB trong bệnh viện 63212\",",
              "\t\t\"Chi phí khác 63215\",",
              "\t\t\"Chi phí mua máu, tiểu cầu, dịch truyền 63220\",",
              "\t\t\"Giá vốn chi phí khấu hao TSCĐ 63209\",",
              "\t\t\"Giá vốn phân bổ CCDC và chi phí trả trước 63210\",",
              "\t\t\"KCB Cận lâm sàng (Ngoại trú)-LDLK 63205\",",
              "\t\t\"KCB Cận lâm sàng (Nội trú)-LDLK 63206\"},",
              "\t\"Các mục Chi phí khác\",",
              "\t'UMC_KQKD'[Chỉ tiêu] IN {\"Doanh thu các dịch vụ: hội nghị, phí quản lý, cho thuê…. 511314\",",
              "\t\t\"Doanh thu hoạt động nghiên cứu khoa học 5115\",",
              "\t\t\"Doanh thu KCB cận lâm sàng (ngoại trú) 511304\",",
              "\t\t\"Doanh thu KCB nội ngoại trú 511307\",",
              "\t\t\"Doanh thu khác 5118\",",
              "\t\t\"Doanh thu liên quan KCB - ngoài bệnh viện 511313\",",
              "\t\t\"Doanh thu liên quan KCB - trong bệnh viện 511312\",",
              "\t\t\"Nguồn thu từ NSNN chi hoạt động PCD 5119\"},",
              "\t\"Các mục Doanh thu khác\",",
              "\t'UMC_KQKD'[Chỉ tiêu] IN {\"Doanh thu KCB ngoại trú 511302\"},",
              "\t\"Doanh thu KCB ngoại trú\",",
              "\t'UMC_KQKD'[Chỉ tiêu] IN {\"Doanh thu KCB nội trú 511301\"},",
              "\t\"Doanh thu KCB nội trú\",",
              "\t'UMC_KQKD'[Chỉ tiêu] IN {\"Doanh thu nhà thuốc 511311\"},",
              "\t\"Doanh thu nhà thuốc\",",
              "\t'UMC_KQKD'[Chỉ tiêu] IN {\"Giá vốn - Chi phí nguyên vật liệu 63217\"},",
              "\t\"Giá vốn - Chi phí nguyên vật liệu\",",
              "\t'UMC_KQKD'[Chỉ tiêu] IN {\"Giá vốn Thuốc - Khoa Dược 63216\"},",
              "\t\"Giá vốn Thuốc - Khoa Dược\",",
              "\t'UMC_KQKD'[Chỉ tiêu] IN {\"Giá vốn Thuốc - Nhà thuốc 63211\"},",
              "\t\"Giá vốn Thuốc - Nhà thuốc\",",
              "\t'UMC_KQKD'[Chỉ tiêu] IN {\"Giá vốn: Chi phí tiền lương - trích Bảo hiểm 63219\"},",
              "\t\"Giá vốn: Chi phí tiền lương - trích Bảo hiểm\",",
              "\t'UMC_KQKD'[Chỉ tiêu] IN {\"Giá vốn: Thù lao dịch vụ 63218\"},",
              "\t\"Giá vốn: Thù lao dịch vụ\",",
              "\t'UMC_KQKD'[Chỉ tiêu]",
              ")"
            ],
            "lineageTag": "b36f8334-8193-4e59-93cc-3752fddbac40",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "GroupingMetadata",
                "value": {
                  "version": 0,
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "UMC_KQKD"
                          }
                        },
                        "Property": "Chỉ tiêu"
                      }
                    }
                  ]
                }
              }
            ],
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"u\",\"Entity\":\"UMC_KQKD\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"GroupItems\":[{\"DisplayName\":\"(Blank)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"Các mục Chi phí khác\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Chi phí  thuê xét nghiệm ĐHYD - Medic... liên quan KCB trong bệnh viện 63212'\"}}],[{\"Literal\":{\"Value\":\"'Chi phí khác 63215'\"}}],[{\"Literal\":{\"Value\":\"'Chi phí mua máu, tiểu cầu, dịch truyền 63220'\"}}],[{\"Literal\":{\"Value\":\"'Giá vốn chi phí khấu hao TSCĐ 63209'\"}}],[{\"Literal\":{\"Value\":\"'Giá vốn phân bổ CCDC và chi phí trả trước 63210'\"}}],[{\"Literal\":{\"Value\":\"'KCB Cận lâm sàng (Ngoại trú)-LDLK 63205'\"}}],[{\"Literal\":{\"Value\":\"'KCB Cận lâm sàng (Nội trú)-LDLK 63206'\"}}]]}}},{\"DisplayName\":\"Các mục Doanh thu khác\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Doanh thu các dịch vụ: hội nghị, phí quản lý, cho thuê…. 511314'\"}}],[{\"Literal\":{\"Value\":\"'Doanh thu hoạt động nghiên cứu khoa học 5115'\"}}],[{\"Literal\":{\"Value\":\"'Doanh thu KCB cận lâm sàng (ngoại trú) 511304'\"}}],[{\"Literal\":{\"Value\":\"'Doanh thu KCB nội ngoại trú 511307'\"}}],[{\"Literal\":{\"Value\":\"'Doanh thu khác 5118'\"}}],[{\"Literal\":{\"Value\":\"'Doanh thu liên quan KCB - ngoài bệnh viện 511313'\"}}],[{\"Literal\":{\"Value\":\"'Doanh thu liên quan KCB - trong bệnh viện 511312'\"}}],[{\"Literal\":{\"Value\":\"'Nguồn thu từ NSNN chi hoạt động PCD 5119'\"}}]]}}},{\"DisplayName\":\"Doanh thu KCB ngoại trú\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Doanh thu KCB ngoại trú 511302'\"}}]]}}},{\"DisplayName\":\"Doanh thu KCB nội trú\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Doanh thu KCB nội trú 511301'\"}}]]}}},{\"DisplayName\":\"Doanh thu nhà thuốc\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Doanh thu nhà thuốc 511311'\"}}]]}}},{\"DisplayName\":\"Giá vốn - Chi phí nguyên vật liệu\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Giá vốn - Chi phí nguyên vật liệu 63217'\"}}]]}}},{\"DisplayName\":\"Giá vốn Thuốc - Khoa Dược\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Giá vốn Thuốc - Khoa Dược 63216'\"}}]]}}},{\"DisplayName\":\"Giá vốn Thuốc - Nhà thuốc\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Giá vốn Thuốc - Nhà thuốc 63211'\"}}]]}}},{\"DisplayName\":\"Giá vốn: Chi phí tiền lương - trích Bảo hiểm\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Giá vốn: Chi phí tiền lương - trích Bảo hiểm 63219'\"}}]]}}},{\"DisplayName\":\"Giá vốn: Thù lao dịch vụ\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Giá vốn: Thù lao dịch vụ 63218'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Value_bill",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "UMC_KQKD[Value]/1000000000",
            "formatString": "#,0.00",
            "lineageTag": "9d2a272d-ba2a-441a-a649-8ba1174346c6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Parse",
            "dataType": "dateTime",
            "sourceColumn": "Parse",
            "formatString": "Short Date",
            "lineageTag": "bc688dab-5b66-483a-b5c1-a773fe36f6aa",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "8c04a982-552e-4649-94c3-f7db6551108b",
                "defaultHierarchy": {
                  "table": "LocalDateTable_8ad98c6c-2592-49d3-be92-64d686a661b3",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "UMC_KQKD",
            "mode": "import",
            "queryGroup": "UMC Raw Data",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DATA\\DATA_FINANCE\\02. CO SO DU LIEU\\02. Bao cao tai chinh - L3_L4_L5_L6_L7.xlsx\"), null, true),",
                "    KQKD1 = Source{[Name=\"KQKD\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(KQKD1, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type text}, {\"Chỉ tiêu\", type text}, {\"Mã số\", Int64.Type}, {\"Tài khoản\", type text}, {\"Kỳ 1/2021\", type text}, {\"Kỳ 2/2021\", type text}, {\"Kỳ 3/2021\", type text}, {\"Kỳ 4/2021\", type text}, {\"Kỳ 5/2021\", type text}, {\"Kỳ 6/2021\", type text}, {\"Kỳ 7/2021\", type text}, {\"Kỳ 8/2021\", type text}, {\"Kỳ 9/2021\", type text}, {\"Kỳ 10/2021\", type text}, {\"Kỳ 11/2021\", type text}, {\"Kỳ 12/2021\", type text}, {\"Kỳ 1/2022\", type text}, {\"Kỳ 2/2022\", type text}, {\"Kỳ 3/2022\", type text}, {\"Kỳ 4/2022\", type text}, {\"Kỳ 5/2022\", type text}, {\"Kỳ 6/2022\", type text}, {\"Kỳ 7/2022\", type text}, {\"Kỳ 8/2022\", type text}, {\"Kỳ 9/2022\", type text}, {\"Kỳ 10/2022\", type text}, {\"Kỳ 11/2022\", type text}, {\"Kỳ 12/2022\", type text}, {\"Kỳ 1/2023\", type number}, {\"Kỳ 2/2023\", type number}, {\"Kỳ 3/2023\", type text}, {\"Kỳ 4/2023\", type text}, {\"Kỳ 5/2023\", type text}, {\"Kỳ 6/2023\", type text}, {\"Kỳ 7/2023\", type text}, {\"Kỳ 8/2023\", type text}, {\"Kỳ 9/2023\", type text}, {\"Kỳ 10/2023\", type text}, {\"Kỳ 11/2023\", type text}, {\"Kỳ 12/2023\", type text}}),",
                "    #\"Kept Range of Rows\" = Table.Range(#\"Changed Type\",1,64),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Kept Range of Rows\",{\"Chỉ tiêu\", \"Tài khoản\", \"Kỳ 1/2021\", \"Kỳ 2/2021\", \"Kỳ 3/2021\", \"Kỳ 4/2021\", \"Kỳ 5/2021\", \"Kỳ 6/2021\", \"Kỳ 7/2021\", \"Kỳ 8/2021\", \"Kỳ 9/2021\", \"Kỳ 10/2021\", \"Kỳ 11/2021\", \"Kỳ 12/2021\", \"Kỳ 1/2022\", \"Kỳ 2/2022\", \"Kỳ 3/2022\", \"Kỳ 4/2022\", \"Kỳ 5/2022\", \"Kỳ 6/2022\", \"Kỳ 7/2022\", \"Kỳ 8/2022\", \"Kỳ 9/2022\", \"Kỳ 10/2022\", \"Kỳ 11/2022\", \"Kỳ 12/2022\", \"Kỳ 1/2023\", \"Kỳ 2/2023\", \"Kỳ 3/2023\", \"Kỳ 4/2023\", \"Kỳ 5/2023\", \"Kỳ 6/2023\", \"Kỳ 7/2023\", \"Kỳ 8/2023\", \"Kỳ 9/2023\", \"Kỳ 10/2023\", \"Kỳ 11/2023\", \"Kỳ 12/2023\"}),",
                "    #\"Merged Columns1\" = Table.CombineColumns(#\"Removed Other Columns\",{\"Chỉ tiêu\", \"Tài khoản\"},Combiner.CombineTextByDelimiter(\" \", QuoteStyle.None),\"Chỉ tiêu\"),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Merged Columns1\", each ([Chỉ tiêu] <> \" \")),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows1\", \"Chỉ tiêu KQKD\", each try if (Number.FromText(Text.At([Chỉ tiêu], 0)) is number) then Text.AfterDelimiter([Chỉ tiêu], \". \") else Text.AfterDelimiter([Chỉ tiêu], \"- \",0) otherwise if Text.StartsWith([Chỉ tiêu], \"-\") then Text.AfterDelimiter([Chỉ tiêu], \"- \",0) else [Chỉ tiêu]),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Added Custom\",{\"Chỉ tiêu KQKD\", \"Kỳ 1/2021\", \"Kỳ 2/2021\", \"Kỳ 3/2021\", \"Kỳ 4/2021\", \"Kỳ 5/2021\", \"Kỳ 6/2021\", \"Kỳ 7/2021\", \"Kỳ 8/2021\", \"Kỳ 9/2021\", \"Kỳ 10/2021\", \"Kỳ 11/2021\", \"Kỳ 12/2021\", \"Kỳ 1/2022\", \"Kỳ 2/2022\", \"Kỳ 3/2022\", \"Kỳ 4/2022\", \"Kỳ 5/2022\", \"Kỳ 6/2022\", \"Kỳ 7/2022\", \"Kỳ 8/2022\", \"Kỳ 9/2022\", \"Kỳ 10/2022\", \"Kỳ 11/2022\", \"Kỳ 12/2022\", \"Kỳ 1/2023\", \"Kỳ 2/2023\", \"Kỳ 3/2023\", \"Kỳ 4/2023\", \"Kỳ 5/2023\", \"Kỳ 6/2023\", \"Kỳ 7/2023\", \"Kỳ 8/2023\", \"Kỳ 9/2023\", \"Kỳ 10/2023\", \"Kỳ 11/2023\", \"Kỳ 12/2023\"}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Removed Other Columns1\", {\"Chỉ tiêu KQKD\"}, \"Attribute\", \"Value\"),",
                "    #\"Inserted Parsed Date\" = Table.AddColumn(#\"Unpivoted Other Columns\", \"Parse\", each Date.From(DateTimeZone.From(Text.AfterDelimiter([Attribute], \" \"))), type date),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Parsed Date\",{{\"Chỉ tiêu KQKD\", \"Chỉ tiêu\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each true)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "UMC_Index",
        "lineageTag": "c80f94d9-3262-498a-b8fe-234b276acb25",
        "columns": [
          {
            "name": "Số liệu Dashboard",
            "dataType": "string",
            "sourceColumn": "Số liệu Dashboard",
            "lineageTag": "88788005-ba08-426b-804f-b74cf8880343",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Nhóm chỉ số",
            "dataType": "string",
            "sourceColumn": "Nhóm chỉ số",
            "lineageTag": "0b31b4ee-0a8f-4c0d-8143-fcc80108a78a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Chỉ số",
            "dataType": "string",
            "sourceColumn": "Chỉ số",
            "lineageTag": "c817f70b-6401-4bb5-a905-3276a3f308af",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "ĐVT",
            "dataType": "string",
            "sourceColumn": "ĐVT",
            "lineageTag": "cd95d597-b789-4c9a-a019-4786824daf3b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Attribute",
            "dataType": "string",
            "sourceColumn": "Attribute",
            "lineageTag": "8ecde344-9a56-4396-b64b-b9029f140876",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "string",
            "sourceColumn": "Value",
            "lineageTag": "2abe76dc-b54f-459f-aad3-138d83864590",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "lineageTag": "dd9e9f42-5823-4be0-860f-fd38bcf15c2b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year",
            "lineageTag": "a2443774-bc61-4cda-8926-45fe1c68cea2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "YearnMonth",
            "dataType": "string",
            "sourceColumn": "YearnMonth",
            "lineageTag": "16239582-7dbb-4bb6-895e-1b480048004c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "UMC_Index",
            "mode": "import",
            "queryGroup": "UMC Raw Data",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DATA\\DATA_FINANCE\\02. CO SO DU LIEU\\02. Bao cao tai chinh - L3_L4_L5_L6_L7.xlsx\"), null, true),",
                "    KQKD1 = Source{[Name=\"KQKD\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(KQKD1, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type text}, {\"Chỉ tiêu\", type text}, {\"Mã số\", Int64.Type}, {\"Tài khoản\", type text}, {\"Kỳ 1/2021\", type text}, {\"Kỳ 2/2021\", type text}, {\"Kỳ 3/2021\", type text}, {\"Kỳ 4/2021\", type text}, {\"Kỳ 5/2021\", type text}, {\"Kỳ 6/2021\", type text}, {\"Kỳ 7/2021\", type text}, {\"Kỳ 8/2021\", type text}, {\"Kỳ 9/2021\", type text}, {\"Kỳ 10/2021\", type text}, {\"Kỳ 11/2021\", type text}, {\"Kỳ 12/2021\", type text}, {\"Kỳ 1/2022\", type text}, {\"Kỳ 2/2022\", type text}, {\"Kỳ 3/2022\", type text}, {\"Kỳ 4/2022\", type text}, {\"Kỳ 5/2022\", type text}, {\"Kỳ 6/2022\", type text}, {\"Kỳ 7/2022\", type text}, {\"Kỳ 8/2022\", type text}, {\"Kỳ 9/2022\", type text}, {\"Kỳ 10/2022\", type text}, {\"Kỳ 11/2022\", type text}, {\"Kỳ 12/2022\", type text}, {\"Kỳ 1/2023\", type number}, {\"Kỳ 2/2023\", type number}, {\"Kỳ 3/2023\", type text}, {\"Kỳ 4/2023\", type text}, {\"Kỳ 5/2023\", type text}, {\"Kỳ 6/2023\", type text}, {\"Kỳ 7/2023\", type text}, {\"Kỳ 8/2023\", type text}, {\"Kỳ 9/2023\", type text}, {\"Kỳ 10/2023\", type text}, {\"Kỳ 11/2023\", type text}}),",
                "    #\"Removed Top Rows\" = Table.Skip(#\"Changed Type\",58),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Top Rows\",{{\"Column1\", \"Số liệu Dashboard\"}, {\"Chỉ tiêu\", \"Chỉ số\"}, {\"Tài khoản\", \"ĐVT\"}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"Nhóm chỉ số\", each if Text.StartsWith([Chỉ số], \"Nhóm chỉ số\") then Text.Range([Chỉ số],12) else null),",
                "    #\"Filled Down\" = Table.FillDown(#\"Added Custom\",{\"Nhóm chỉ số\"}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filled Down\",{\"Số liệu Dashboard\", \"Nhóm chỉ số\", \"Chỉ số\", \"ĐVT\", \"Kỳ 1/2021\", \"Kỳ 2/2021\", \"Kỳ 3/2021\", \"Kỳ 4/2021\", \"Kỳ 5/2021\", \"Kỳ 6/2021\", \"Kỳ 7/2021\", \"Kỳ 8/2021\", \"Kỳ 9/2021\", \"Kỳ 10/2021\", \"Kỳ 11/2021\", \"Kỳ 12/2021\", \"Kỳ 1/2022\", \"Kỳ 2/2022\", \"Kỳ 3/2022\", \"Kỳ 4/2022\", \"Kỳ 5/2022\", \"Kỳ 6/2022\", \"Kỳ 7/2022\", \"Kỳ 8/2022\", \"Kỳ 9/2022\", \"Kỳ 10/2022\", \"Kỳ 11/2022\", \"Kỳ 12/2022\", \"Kỳ 1/2023\", \"Kỳ 2/2023\", \"Kỳ 3/2023\", \"Kỳ 4/2023\", \"Kỳ 5/2023\", \"Kỳ 6/2023\", \"Kỳ 7/2023\", \"Kỳ 8/2023\", \"Kỳ 9/2023\", \"Kỳ 10/2023\", \"Kỳ 11/2023\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each ([Chỉ số] <> \"Nhóm chỉ số Dòng tiền\" and [Chỉ số] <> \"Nhóm chỉ số Hiệu quả hoạt động\" and [Chỉ số] <> \"Nhóm chỉ số Sinh lợi\" and [Chỉ số] <> \"Nhóm chỉ số Thanh toán\" and [Chỉ số] <> \"Nhóm chỉ số Tăng trưởng\" and [Chỉ số] <> \"Nhóm chỉ số Đòn bẩy tài chính\")),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Filtered Rows\", {\"Số liệu Dashboard\", \"Nhóm chỉ số\", \"Chỉ số\", \"ĐVT\"}, \"Attribute\", \"Value\"),",
                "    #\"Inserted Text Between Delimiters\" = Table.AddColumn(#\"Unpivoted Other Columns\", \"Month\", each Text.BetweenDelimiters([Attribute], \" \", \"/\"), type text),",
                "    #\"Inserted Text After Delimiter\" = Table.AddColumn(#\"Inserted Text Between Delimiters\", \"Year\", each Text.AfterDelimiter([Attribute], \"/\"), type text),",
                "    #\"Added Custom Column\" = Table.AddColumn(#\"Inserted Text After Delimiter\", \"YearnMonth\", each Text.Combine({Text.From([Year], \"en-US\"), Text.PadStart(Text.From([Month], \"en-US\"), 2, \"0\"), \"00\"}), type text)",
                "in",
                "    #\"Added Custom Column\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "A3_A7_Measure",
        "lineageTag": "f7a7c44a-5fda-4bf5-8b8d-beca01c1e22e",
        "partitions": [
          {
            "name": "A3_A7_Measure",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Doanh thu thuần",
            "expression": [
              "",
              "VAR x = \"Doanh thu thuần về cung cấp dịch vụ\" ",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x)",
              "VAR month_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "var quarter_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[QuarterInYear] = MAX(UMC_Total[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "3b864cf1-77d3-4191-8279-38ca95b751b9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Giá vốn hàng bán",
            "expression": [
              "",
              "VAR x = \"Giá vốn hàng bán\" ",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x)",
              "VAR month_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "var quarter_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[QuarterInYear] = MAX(UMC_Total[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "6fa96299-058d-4aa1-8734-972429396781",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Lợi nhuận ròng",
            "expression": [
              "",
              "VAR x = \"Lợi nhuận sau thuế TNDN\" ",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x)",
              "VAR month_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "var quarter_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[QuarterInYear] = MAX(UMC_Total[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "d1982a4b-0e5f-48e1-bbad-0f44bfa3b5af",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Lợi nhuận gộp",
            "expression": [
              "",
              "VAR x = \"Lợi nhuận gộp về cung cấp dịch vụ (DT thuần - GVHB)\" ",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x)",
              "VAR month_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "var quarter_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[QuarterInYear] = MAX(UMC_Total[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c8f863e4-97dc-4797-a9ac-8f4c3bd7d01a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Biên lợi nhuận",
            "expression": "DIVIDE(A3_A7_Measure[Lợi nhuận gộp], A3_A7_Measure[Doanh thu thuần], 0)",
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "f0a57cfb-8416-4a89-8898-4dacf9d67f3b"
          },
          {
            "name": "Lợi nhuận/ doanh thu (ROS)",
            "expression": "DIVIDE(A3_A7_Measure[Lợi nhuận ròng], A3_A7_Measure[Doanh thu thuần], 0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5ffbf0a8-6c33-43ca-a74d-11c3f3edec8e"
          },
          {
            "name": "Lợi nhuận/ tài sản (ROA)_backup",
            "expression": [
              "",
              "VAR asset = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = \"Tổng Cộng Tài Sản\")",
              "VAR pre_peroid_asset = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = \"Tổng Cộng Tài Sản\", PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR roa = DIVIDE(A3_A7_Measure[Lợi nhuận ròng], (asset + pre_peroid_asset)/2, 0)",
              "",
              "VAR default_asset = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = \"Tổng Cộng Tài Sản\", UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "VAR default_pre_peroid_asset = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = \"Tổng Cộng Tài Sản\", PREVIOUSMONTH(LASTDATE(UMC_Total[Parse])))",
              "VAR default_roa = DIVIDE(A3_A7_Measure[Lợi nhuận ròng], (default_asset + default_pre_peroid_asset)/2, 0)",
              "",
              "return if(not(ISFILTERED(Dates_ref)), default_roa, roa)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "cf088d57-8b91-43ef-8a59-5d757f50091c"
          },
          {
            "name": "Lợi nhuận/ vốn chủ (ROE)_backup",
            "expression": [
              "",
              "VAR equity = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = \"Vốn Chủ Sở Hữu_410\")",
              "VAR pre_peroid_equity = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = \"Vốn Chủ Sở Hữu_410\", PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR roe = DIVIDE(A3_A7_Measure[Lợi nhuận ròng], (equity + pre_peroid_equity)/2, 0)",
              "",
              "VAR default_equity = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = \"Vốn Chủ Sở Hữu_410\", UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "VAR default_pre_peroid_equity = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = \"Vốn Chủ Sở Hữu_410\", PREVIOUSMONTH(LASTDATE(UMC_CDKT[Parse])))",
              "VAR default_roe = DIVIDE(A3_A7_Measure[Lợi nhuận ròng], (default_equity + default_pre_peroid_equity)/2, 0)",
              "",
              "return if(not(ISFILTERED(Dates_ref)), default_roe, roe)"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "23943b3a-5ea9-482e-9548-1dad1df0926b"
          },
          {
            "name": "% Giá vốn/ Doanh thu thuần",
            "expression": "DIVIDE([Year_default_Giá vốn hàng bán], [Year_default_Doanh thu thuần], 0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "aa9176e4-08bd-4cbc-a8da-e1600527e9aa"
          },
          {
            "name": "Year_default_Tổng tài sản",
            "expression": [
              "",
              "Var x = \"Tổng Cộng Tài Sản\"",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year), STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "8582d303-6451-4606-9a06-e9cd8e5b99e6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "A3_value_bill_with_default",
            "expression": [
              "",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]))",
              "VAR month_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "var quarter_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[QuarterInYear] = MAX(UMC_Total[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)",
              "",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "011de507-03a1-4267-9b7c-75f4baf2b7b4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Doanh thu thuần",
            "expression": [
              "",
              "VAR x = \"Doanh thu thuần về cung cấp dịch vụ\" ",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x)",
              "VAR b = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year)",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "8f813ca8-d8e8-41bb-a3d2-65df59c575fb",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Giá vốn hàng bán",
            "expression": [
              "",
              "VAR x = \"Giá vốn hàng bán\" ",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x)",
              "VAR b = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year)",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "9963cd47-60e2-4b5a-8472-13e1ab6c4e4b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Lợi nhuận ròng",
            "expression": [
              "",
              "VAR x = \"Lợi nhuận sau thuế TNDN\" ",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x)",
              "VAR b = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year)",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "f5895044-26d3-49db-be5e-698a29d8e0ed",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Lợi nhuận/ doanh thu (ROS)",
            "expression": "DIVIDE(A3_A7_Measure[Year_default_Lợi nhuận ròng], A3_A7_Measure[Year_default_Doanh thu thuần], 0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "51374d24-4fd2-4d41-8d79-33d72bd4edb2"
          },
          {
            "name": "Year_default_Lợi nhuận/ tài sản (ROA)",
            "expression": [
              "",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "",
              "VAR x = \"Tổng Cộng Tài Sản\"",
              "VAR asset =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "",
              "VAR _pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR _pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR _pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_asset = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), _pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), _pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), _pre_year)",
              "VAR roa = DIVIDE(A3_A7_Measure[Year_default_Lợi nhuận ròng], (asset + pre_peroid_asset)/2, 0)",
              "",
              "VAR default_asset = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(Dates_ref[Date])), Dates_ref[Year] = max_year)",
              "",
              "VAR default_pre_month = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dateadd(Dates_ref[Date], -1, MONTH)), Dates_ref[Year] = max_year)",
              "VAR default_pre_quarter = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date])))), Dates_ref[Year] = max_year)",
              "VAR default_pre_peroid_asset = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, default_pre_month,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, default_pre_quarter)",
              "VAR default_roa = DIVIDE(A3_A7_Measure[Year_default_Lợi nhuận ròng], (default_asset + default_pre_peroid_asset)/2, 0)",
              "",
              "return if(not(HASONEFILTER(Dates_ref[Year])), default_roa, roa)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f2190010-88b8-4ba9-a06e-f6fbe0e23332"
          },
          {
            "name": "Lợi nhuận/ tài sản (ROA)",
            "expression": [
              "",
              "VAR x = \"Tổng Cộng Tài Sản\"",
              "VAR asset =",
              "    CALCULATE (",
              "        SUM ( UMC_Total[Value_bill] ),",
              "        UMC_Total[Chỉ tiêu] = x,",
              "        STARTOFMONTH (",
              "            LASTDATE ( Dates_ref[Date] )",
              "        )",
              "    )",
              "VAR _pre_month =",
              "    CALCULATE (",
              "        CALCULATE (",
              "            SUM ( UMC_Total[Value_bill] ),",
              "            UMC_Total[Chỉ tiêu] = x",
              "        ),",
              "        PREVIOUSMONTH ( Dates_ref[Date] )",
              "    )",
              "VAR _pre_quarter =",
              "    CALCULATE (",
              "        SUM ( UMC_Total[Value_bill] ),",
              "        UMC_Total[Chỉ tiêu] = x,",
              "        STARTOFMONTH (",
              "            LASTDATE (",
              "                PREVIOUSQUARTER ( Dates_ref[Date] )",
              "            )",
              "        )",
              "    )",
              "VAR _pre_year =",
              "    CALCULATE (",
              "        SUM ( UMC_Total[Value_bill] ),",
              "        UMC_Total[Chỉ tiêu] = x,",
              "        STARTOFMONTH (",
              "            LASTDATE (",
              "                PREVIOUSYEAR ( Dates_ref[Date] )",
              "            )",
              "        )",
              "    )",
              "VAR pre_peroid_asset =",
              "    SWITCH (",
              "        TRUE,",
              "        (",
              "            ISFILTERED ( Dates_ref[VN_Month] )",
              "        ), _pre_month,",
              "        ISFILTERED ( Dates_ref[VN_Quarter] ), _pre_quarter,",
              "        ISFILTERED ( Dates_ref[Year] ), _pre_year",
              "    )",
              "VAR roa =",
              "    DIVIDE (",
              "        A3_A7_Measure[Lợi nhuận ròng],",
              "        ( asset + pre_peroid_asset ) / 2,",
              "        0",
              "    )",
              "VAR default_asset =",
              "    CALCULATE (",
              "        SUM ( UMC_Total[Value_bill] ),",
              "        UMC_Total[Chỉ tiêu] = x,",
              "        UMC_Total[YearnMonth]",
              "            = MAX ( UMC_Total[YearnMonth] )",
              "    )",
              "",
              "VAR _defmonth =",
              "CALCULATE (",
              "    SUM ( UMC_Total[Value_bill] ),",
              "    UMC_Total[Chỉ tiêu] = x,",
              "    PREVIOUSMONTH ( LASTDATE ( UMC_Total[Parse] ) )",
              ")",
              "VAR _defquarter =",
              "CALCULATE (",
              "    SUM ( UMC_Total[Value_bill] ),",
              "    UMC_Total[Chỉ tiêu] = x,",
              "    ENDOFQUARTER (",
              "        DATEADD ( STARTOFQUARTER ( LASTDATE ( UMC_Total[Parse] ) ), -1, QUARTER )",
              "    )",
              ")",
              "VAR default_pre_peroid_asset =",
              "SWITCH (",
              "    TRUE,",
              "    SELECTEDVALUE ( 'Qtr-Month Switch'[Qtr-Month Switch Order] ) = 1, _defmonth,",
              "    SELECTEDVALUE ( 'Qtr-Month Switch'[Qtr-Month Switch Order] ) = 0, _defquarter",
              ")",
              "",
              "VAR default_roa =",
              "    DIVIDE (",
              "        A3_A7_Measure[Lợi nhuận ròng],",
              "        ( default_asset + default_pre_peroid_asset ) / 2,",
              "        0",
              "    )",
              "RETURN",
              "    IF (",
              "        NOT (",
              "            ISFILTERED ( Dates_ref )",
              "        ),",
              "        default_roa,",
              "        roa",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6258e2c1-ee3c-4d57-8727-81150b7d8a53"
          },
          {
            "name": "Lợi nhuận/ vốn chủ (ROE)",
            "expression": [
              "",
              "VAR x = \"Vốn Chủ Sở Hữu_410\"",
              "",
              "VAR equity = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "",
              "VAR _pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR _pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR _pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_equity = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), _pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), _pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), _pre_year)",
              "",
              "VAR roe = DIVIDE(A3_A7_Measure[Lợi nhuận ròng], (equity + pre_peroid_equity)/2, 0)",
              "",
              "VAR default_equity = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "",
              "VAR _defmonth = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, PREVIOUSMONTH(LASTDATE(UMC_Total[Parse])))",
              "VAR _defquarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, ENDOFQUARTER(DATEADD(STARTOFQUARTER(LASTDATE(UMC_Total[Parse])),-1, QUARTER)))",
              "VAR default_pre_peroid_equity = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, _defmonth,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, _defquarter)",
              "VAR default_roe = DIVIDE(A3_A7_Measure[Lợi nhuận ròng], (default_equity + default_pre_peroid_equity)/2, 0)",
              "",
              "return if(not(ISFILTERED(Dates_ref)), default_roe, roe)",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "22bf8051-a81b-4187-b873-b618df65c81e"
          },
          {
            "name": "Z",
            "expression": "ENDOFQUARTER(DATEADD(STARTOFQUARTER(LASTDATE(UMC_Total[Parse])),-1, QUARTER))",
            "formatString": "General Date",
            "lineageTag": "6c591779-4dfc-4292-9293-5a3adae667a2"
          },
          {
            "name": "Lợi nhuận/ tài sản (ROA)_v1",
            "expression": [
              "",
              "VAR x = \"Tổng Cộng Tài Sản\"",
              "",
              "VAR asset = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "",
              "VAR _pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR _pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR _pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_asset = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), _pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), _pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), _pre_year)",
              "",
              "VAR roa = DIVIDE(A3_A7_Measure[Lợi nhuận ròng], (asset + pre_peroid_asset)/2, 0)",
              "",
              "VAR default_asset = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "VAR default_pre_peroid_asset = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, PREVIOUSMONTH(LASTDATE(UMC_Total[Parse])))",
              "VAR default_roa = DIVIDE(A3_A7_Measure[Lợi nhuận ròng], (default_asset + default_pre_peroid_asset)/2, 0)",
              "",
              "return if(not(ISFILTERED(Dates_ref)), default_roa, roa)",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "cf9bf62a-0955-45c0-a941-1b5d52311985"
          },
          {
            "name": "Lợi nhuận/ vốn chủ (ROE)_v1",
            "expression": [
              "",
              "VAR x = \"Vốn Chủ Sở Hữu_410\"",
              "",
              "VAR equity = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "",
              "VAR _pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR _pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR _pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_equity = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), _pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), _pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), _pre_year)",
              "",
              "VAR roe = DIVIDE(A3_A7_Measure[Lợi nhuận ròng], (equity + pre_peroid_equity)/2, 0)",
              "",
              "VAR default_equity = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "VAR default_pre_peroid_equity = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, PREVIOUSMONTH(LASTDATE(UMC_Total[Parse])))",
              "VAR default_roe = DIVIDE(A3_A7_Measure[Lợi nhuận ròng], (default_equity + default_pre_peroid_equity)/2, 0)",
              "",
              "return if(not(ISFILTERED(Dates_ref)), default_roe, roe)",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "53f6d3ef-b88a-4b0e-a6bc-856d5c75b964"
          },
          {
            "name": "Chi phí quản lý",
            "expression": [
              "",
              "VAR x = \"Chi phí quản lý doanh nghiệp\" ",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x)",
              "VAR month_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "var quarter_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[QuarterInYear] = MAX(UMC_Total[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)"
            ],
            "lineageTag": "7a2d9a39-9a7b-48e3-9f9b-05d13a3c210d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Chi phí bán hàng",
            "expression": [
              "",
              "VAR x = \"Chi phí bán hàng\" ",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x)",
              "VAR month_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "var quarter_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[QuarterInYear] = MAX(UMC_Total[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)"
            ],
            "formatString": "0",
            "lineageTag": "501300ec-8b50-48d5-aac2-d49bd2cd02b1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Chi phí bán hàng",
            "expression": [
              "",
              "VAR x = \"Chi phí bán hàng\" ",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x)",
              "VAR b = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year)",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "lineageTag": "da330193-c76b-4ba5-baa8-ec5b76addacf",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "% CP bán hàng/Doanh thu thuần",
            "expression": "DIVIDE([Year_default_Chi phí bán hàng], [Year_default_Doanh thu thuần], 0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4bb77109-ee6b-492c-8f07-7b28040e5369"
          },
          {
            "name": "Year_default_Chi phí quản lý",
            "expression": [
              "",
              "VAR x = \"Chi phí quản lý doanh nghiệp\" ",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x)",
              "VAR b = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year)",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "lineageTag": "cf216cfe-0507-4c30-8e16-625e2d7bcc78",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "% CP quản lý/Doanh thu thuần",
            "expression": "DIVIDE([Year_default_Chi phí quản lý], [Year_default_Doanh thu thuần], 0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a555d9d2-a771-4009-8760-16624a22a6c3"
          },
          {
            "name": "% Chi phí/DT thuần",
            "expression": [
              "",
              "VAR x = \"Doanh thu thuần về cung cấp dịch vụ\" ",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), FILTER(ALL(UMC_Total[Chỉ tiêu]), UMC_Total[Chỉ tiêu] = x), REMOVEFILTERS(UMC_Total[Chỉ tiêu (groups)]))",
              "VAR month_ = CALCULATE(a, filter(UMC_Total, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth])))",
              "var quarter_ = CALCULATE(a, filter(UMC_Total, UMC_Total[QuarterInYear] = MAX(UMC_Total[QuarterInYear])))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "var revenue = if(not(ISFILTERED(Dates_ref)), b, a)",
              "return DIVIDE([A3_value_bill_with_default], revenue, 0)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9e59fbb6-d627-47eb-9b86-250c676c21b1"
          },
          {
            "name": "test_DT thuần",
            "expression": [
              "",
              "VAR x = \"Doanh thu thuần về cung cấp dịch vụ\" ",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), FILTER(ALL(UMC_Total[Chỉ tiêu]), UMC_Total[Chỉ tiêu] = x), REMOVEFILTERS(UMC_Total[Chỉ tiêu (groups)]))",
              "VAR month_ = CALCULATE(a, filter(UMC_Total, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth])))",
              "var quarter_ = CALCULATE(a, filter(UMC_Total, UMC_Total[QuarterInYear] = MAX(UMC_Total[QuarterInYear])))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "var revenue = if(not(ISFILTERED(Dates_ref)), b, a)",
              "return revenue"
            ],
            "lineageTag": "c070e26c-1c28-408e-8af4-63c271c3b372",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "icon_ROA",
            "expression": [
              "",
              "VAR kb = [Lợi nhuận/ tài sản (ROA)]",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb <= 0.01, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = BLANK(), \"-\", // UNICHAR ( 8660 ),",
              "kb > 0.01, \"▲\" //UNICHAR ( 8657 ),",
              ")",
              "return Arrow"
            ],
            "lineageTag": "5d08b9ae-b065-43f8-9346-9c99b156c0ff"
          },
          {
            "name": "icon_ROE",
            "expression": [
              "",
              "VAR kb = [Lợi nhuận/ vốn chủ (ROE)]",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb <= 0.015, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = BLANK(), \"-\", // UNICHAR ( 8660 ),",
              "kb > 0.015, \"▲\" //UNICHAR ( 8657 ),",
              ")",
              "return Arrow"
            ],
            "lineageTag": "62393e9a-eec2-4bc5-9e91-dc813ced479e"
          },
          {
            "name": "icon_ROS",
            "expression": [
              "",
              "VAR kb = [Lợi nhuận/ doanh thu (ROS)]",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb <= 0.1, \"⚪\" ,//UNICHAR ( 9899 ), ",
              "kb = BLANK(), \"-\", // UNICHAR ( 9899 ),",
              "kb > 0.1, \"⚪\" //UNICHAR ( 8657 ),",
              ")",
              "return Arrow"
            ],
            "lineageTag": "b237ca33-1310-4295-89d9-09bbd1b4dd7b"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "A4_Measure",
        "lineageTag": "3da9101c-0231-4066-bc4d-13c02a45d5a8",
        "partitions": [
          {
            "name": "A4_Measure",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Tài sản_ngắn hạn",
            "expression": [
              "",
              "Var x = \"Tài Sản Ngắn Hạn_100\"",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x), LASTNONBLANK(Dates_ref[Date],COUNTROWS(RELATEDTABLE(UMC_Total))))",
              "return SWITCH(TRUE(),",
              "                ISFILTERED(Dates_ref[VN_Month]),a,",
              "                ISFILTERED(Dates_ref[VN_Quarter]),a,",
              "                b)"
            ],
            "formatString": "#,0",
            "lineageTag": "58dc5bf2-ad03-4529-8018-dd4b23abf2f5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Tài sản_dài hạn",
            "expression": [
              "",
              "Var x = \"Tài Sản Dài Hạn_200\"",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x), LASTNONBLANK(Dates_ref[Date],COUNTROWS(RELATEDTABLE(UMC_Total))))",
              "return SWITCH(TRUE(),",
              "                ISFILTERED(Dates_ref[VN_Month]),a,",
              "                ISFILTERED(Dates_ref[VN_Quarter]),a,",
              "                b)"
            ],
            "formatString": "#,0",
            "lineageTag": "7e1605ef-cb0c-4339-906f-91c1bfc48a73",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Nợ_ngắn hạn",
            "expression": [
              "",
              "Var x = \"Nợ Ngắn Hạn_310\"",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x), LASTNONBLANK(Dates_ref[Date],COUNTROWS(RELATEDTABLE(UMC_Total))))",
              "return SWITCH(TRUE(),",
              "                ISFILTERED(Dates_ref[VN_Month]),a,",
              "                ISFILTERED(Dates_ref[VN_Quarter]),a,",
              "                b)"
            ],
            "formatString": "#,0",
            "lineageTag": "5f7238d0-b96f-4851-9ffa-c7c0b9edc887",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Nợ_dài hạn",
            "expression": [
              "",
              "Var x = \"Nợ Dài Hạn_330\"",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x), LASTNONBLANK(Dates_ref[Date],COUNTROWS(RELATEDTABLE(UMC_Total))))",
              "return SWITCH(TRUE(),",
              "                ISFILTERED(Dates_ref[VN_Month]),a,",
              "                ISFILTERED(Dates_ref[VN_Quarter]),a,",
              "                b)"
            ],
            "formatString": "#,0",
            "lineageTag": "bc8709c8-3981-45d1-bdfe-f60fb3c8c395",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Vốn_CSH",
            "expression": [
              "",
              "Var x = \"Vốn Chủ Sở Hữu_410\"",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x), LASTNONBLANK(Dates_ref[Date],COUNTROWS(RELATEDTABLE(UMC_Total))))",
              "return SWITCH(TRUE(),",
              "                ISFILTERED(Dates_ref[VN_Month]),a,",
              "                ISFILTERED(Dates_ref[VN_Quarter]),a,",
              "                b)"
            ],
            "formatString": "#,0.00",
            "lineageTag": "70489a0a-19cc-4c98-8297-53f87ca34498"
          },
          {
            "name": "Vốn lưu động",
            "expression": "A4_Measure[Tài sản_ngắn hạn] - A4_Measure[Nợ_ngắn hạn]",
            "formatString": "#,0",
            "lineageTag": "0ebbb242-70ff-4a67-b7b2-9c31ba13893c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Tỷ số thanh toán nhanh",
            "expression": "DIVIDE((A4_Measure[Tài sản_ngắn hạn] - A4_Measure[Hàng tồn kho]), A4_Measure[Nợ_ngắn hạn],0)",
            "formatString": "#,0",
            "lineageTag": "ec2b9d86-5a8c-4024-ae5b-2299f202b73d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Tỷ số thanh toán hiện hành",
            "expression": "DIVIDE(A4_Measure[Tài sản_ngắn hạn], A4_Measure[Nợ_ngắn hạn],0)",
            "formatString": "#,0",
            "lineageTag": "f46211a8-9cdf-4cec-bf23-e7d68d7ad4fc",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Hàng tồn kho",
            "expression": [
              "",
              "Var x = \"Hàng Tồn Kho_140\"",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, LASTNONBLANK(Dates_ref[Date],COUNTROWS(RELATEDTABLE(UMC_Total))))",
              "return SWITCH(TRUE(),",
              "                ISFILTERED(Dates_ref[VN_Month]),a,",
              "                ISFILTERED(Dates_ref[VN_Quarter]),a,",
              "                b)"
            ],
            "formatString": "0",
            "lineageTag": "5563f5d4-35b4-4d42-b36f-da663a0f0d0d"
          },
          {
            "name": "A4_value_bill_with_default",
            "expression": [
              "",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b =",
              "        CALCULATE(",
              "   \t\t    SUM(UMC_Total[Value_bill]),",
              "            LASTNONBLANK(Dates_ref[Date],COUNTROWS(RELATEDTABLE(UMC_Total))))",
              "return SWITCH(TRUE(),",
              "                ISFILTERED(Dates_ref[VN_Month]),a,",
              "                ISFILTERED(Dates_ref[VN_Quarter]),a,",
              "                b)"
            ],
            "formatString": "#,0",
            "lineageTag": "13c95a66-8cfc-4778-bbc8-73eeab402fec",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Tài sản ngắn hạn",
            "expression": [
              "",
              "VAR x = \"Tài Sản Ngắn Hạn_100\" ",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year), STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "a34b0679-2b97-4882-9595-7fdb66abe17d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Tài sản dài hạn",
            "expression": [
              "",
              "VAR x = \"Tài Sản Dài Hạn_200\" ",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year), STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "0edbf5b7-47e0-4c08-bc37-6f50be3df992",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Nợ ngắn hạn",
            "expression": [
              "",
              "VAR x = \"Nợ Ngắn Hạn_310\" ",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year), STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "efe6664e-6ff5-4f36-89c0-12e91441bf15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Tỷ số thanh toán hiện hành",
            "expression": "DIVIDE(A4_Measure[Year_default_Tài sản ngắn hạn], [Year_default_Nợ ngắn hạn],0)",
            "formatString": "#,0.0",
            "lineageTag": "4b5f5cbb-4d71-4a19-8528-53189a2f5aca"
          },
          {
            "name": "Year_default_Hàng tồn kho",
            "expression": [
              "",
              "VAR x = \"Hàng Tồn Kho_140\" ",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year), STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "formatString": "#,0.0",
            "lineageTag": "f8d1197c-0b14-41fa-af1e-f8be2a1d64f2"
          },
          {
            "name": "LastNonBlankValue",
            "expression": [
              "",
              "CALCULATE(",
              "   \t\tSUM(UMC_Total[Value_bill]),",
              "        LASTNONBLANK(Dates_ref[Date],COUNTROWS(RELATEDTABLE(UMC_Total))))"
            ],
            "lineageTag": "b3f36bce-9fec-4973-a0e6-28fdd6ef9704",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Icon_Vốn lưu động",
            "expression": [
              "",
              "VAR kb= [Vốn lưu động]",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb <= 0, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = 0, \"-\", // UNICHAR ( 8660 ),",
              "kb > 0, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return Arrow"
            ],
            "lineageTag": "2f1a6bb0-328f-4c6f-aabd-e53f82ba2022"
          },
          {
            "name": "Icon_TSTTN",
            "expression": [
              "",
              "VAR kb = A4_Measure[Tỷ số thanh toán nhanh] ",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb <= 1.5, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = BLANK(), \"-\", // UNICHAR ( 8660 ),",
              "kb > 1.5, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return Arrow"
            ],
            "lineageTag": "2d11d758-eee2-4e72-925c-5a4890acb66b"
          },
          {
            "name": "Icon_TSTTHH",
            "expression": [
              "",
              "VAR kb = A4_Measure[Tỷ số thanh toán hiện hành]",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb <= 1.7, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = BLANK(), \"-\", // UNICHAR ( 8660 ),",
              "kb > 1.7, \"▲\" //UNICHAR ( 8657 ),",
              ")",
              "return Arrow"
            ],
            "lineageTag": "5a95d09a-ebc7-4063-91c4-c8b80d3a466f"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "UMC_Điểm Hòa Vốn",
        "lineageTag": "c6201d8e-7fdf-4196-be02-1c791fd3f62b",
        "columns": [
          {
            "name": "Attribute",
            "dataType": "string",
            "sourceColumn": "Attribute",
            "lineageTag": "09bf4abb-c3de-40cf-b90b-c182e48e63a3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "double",
            "sourceColumn": "Value",
            "formatString": "0.00",
            "lineageTag": "5b0fd12b-63e9-443b-bd4d-de81d1ad22cb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month",
            "formatString": "0",
            "lineageTag": "d9c8570f-322f-4784-8b8b-888bb8c668f4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "d305916d-555d-45f5-a56f-9b3fb89fd2d5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "YearnMonth",
            "dataType": "string",
            "sourceColumn": "YearnMonth",
            "lineageTag": "bce654f1-cb58-410c-a0f1-676840aebfcc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Value_bill",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "'UMC_Điểm Hòa Vốn'[Value]/1000000000",
            "lineageTag": "514b3c22-b850-4d2f-98c5-75c25c16c442",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Parse",
            "dataType": "string",
            "sourceColumn": "Parse",
            "lineageTag": "8910a4ad-fe38-49f9-9018-35c3c9590702",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "Month Name",
            "lineageTag": "ec13d8bb-08fb-4e3b-bb4a-631bd327db47",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthShort",
            "dataType": "string",
            "sourceColumn": "MonthShort",
            "lineageTag": "b6eaea8b-f193-4a5b-8522-ffc9e335e85f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Chỉ tiêu",
            "dataType": "string",
            "sourceColumn": "Chỉ tiêu",
            "lineageTag": "e0df0a10-5e5a-4f66-95e1-70068fd3f3a0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quater",
            "dataType": "int64",
            "sourceColumn": "Quater",
            "formatString": "0",
            "lineageTag": "2eb103ba-bf5f-4860-b4fa-07f11c83821c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "QuarterInYear",
            "dataType": "string",
            "sourceColumn": "QuarterInYear",
            "lineageTag": "4efbae78-84da-4141-a729-9965eba7c060",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "UMC_Điểm Hòa Vốn",
            "mode": "import",
            "queryGroup": "UMC Raw Data",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DATA\\DATA_FINANCE\\02. CO SO DU LIEU\\03. Diem hoa von - Don bay hoat dong - L3_L7.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Sheet1_Sheet,{{\"Column1\", type text}, {\"Column2\", type any}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"Column7\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}, {\"Column14\", type any}, {\"Column15\", type any}, {\"Column16\", type any}, {\"Column17\", type any}, {\"Column18\", type any}, {\"Column19\", type any}, {\"Column20\", type any}, {\"Column21\", type any}, {\"Column22\", type any}, {\"Column23\", type any}, {\"Column24\", type any}, {\"Column25\", type any}, {\"Column26\", type any}, {\"Column27\", type any}, {\"Column28\", type any}, {\"Column29\", type any}, {\"Column30\", type any}, {\"Column31\", type any}, {\"Column32\", type any}, {\"Column33\", type any}, {\"Column34\", type any}, {\"Column35\", type any}, {\"Column36\", type any}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type\", each ([Column1] <> \"Chỉ tiêu\")),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Filtered Rows1\", [PromoteAllScalars=true]),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Promoted Headers\", each ([Column1] <> null)),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Filtered Rows2\",{{\"Column1\", \"Chỉ tiêu\"}}),",
                "    #\"Removed Bottom Rows\" = Table.RemoveLastN(#\"Renamed Columns\",5),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Removed Bottom Rows\",{\"Chỉ tiêu\", \"1/2021\", \"2/2021\", \"3/2021\", \"4/2021\", \"5/2021\", \"6/2021\", \"7/2021\", \"8/2021\", \"9/2021\", \"10/2021\", \"11/2021\", \"12/2021\", \"1/2022\", \"2/2022\", \"3/2022\", \"4/2022\", \"5/2022\", \"6/2022\", \"7/2022\", \"8/2022\", \"9/2022\", \"10/2022\", \"11/2022\", \"12/2022\", \"1/2023\", \"2/2023\", \"3/2023\", \"4/2023\", \"5/2023\", \"6/2023\", \"7/2023\", \"8/2023\", \"9/2023\", \"10/2023\", \"11/2023\", \"12/2023\"}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Removed Other Columns\", {\"Chỉ tiêu\"}, \"Attribute\", \"Value\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Unpivoted Other Columns\", each ([Chỉ tiêu] = \"Biến phí\" or [Chỉ tiêu] = \"Doanh thu thuần\" or [Chỉ tiêu] = \"Định phí\")),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Parse\", each Date.From(DateTimeZone.From([Attribute]))),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Added Custom\", \"Month Name\", each Date.MonthName([Parse]), type text),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Month Name\", \"Month\", each Date.Month([Parse]), Int64.Type),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Inserted Month\", \"Year\", each Date.Year([Parse]), Int64.Type),",
                "    #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted Year\", \"Quater\", each Date.QuarterOfYear([Parse]), Int64.Type),",
                "    #\"Added Custom Column\" = Table.AddColumn(#\"Inserted Quarter\", \"YearnMonth\", each Text.Combine({Text.From([Year], \"en-US\"), Text.PadStart(Text.From([Month], \"en-US\"), 2, \"0\"), \"00\"}), type text),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom Column\",{{\"Value\", type number}, {\"Chỉ tiêu\", type text}, {\"Month\", Int64.Type}, {\"Year\", Int64.Type}}),",
                "    #\"Inserted First Characters\" = Table.AddColumn(#\"Changed Type2\", \"MonthShort\", each Text.Start([Month Name], 3), type text),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Inserted First Characters\", \"QuarterInYear\", each Text.Combine({Text.From([Year], \"en-US\"), \"0\", Text.From([Quater], \"en-US\"), \"00\"}), type text)",
                "in",
                "    #\"Inserted Merged Column\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Điểm hòa vốn",
            "expression": "'UMC_Điểm Hòa Vốn'[Định phí]/(1-([Biến phí]/ [DT thuần]))",
            "formatString": "#,0",
            "lineageTag": "55ec01b9-c297-4a3b-9e88-305b7944285f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Định phí",
            "expression": [
              "",
              "VAR a = CALCULATE(sum('UMC_Điểm Hòa Vốn'[Value_bill]), 'UMC_Điểm Hòa Vốn'[Chỉ tiêu] = \"Định phí\")",
              "VAR month_ = CALCULATE(sum('UMC_Điểm Hòa Vốn'[Value_bill]), 'UMC_Điểm Hòa Vốn'[Chỉ tiêu] = \"Định phí\", 'UMC_Điểm Hòa Vốn'[YearnMonth] = MAX('UMC_Điểm Hòa Vốn'[YearnMonth]))",
              "var quarter_ = CALCULATE(sum('UMC_Điểm Hòa Vốn'[Value_bill]), 'UMC_Điểm Hòa Vốn'[Chỉ tiêu] = \"Định phí\", 'UMC_Điểm Hòa Vốn'[QuarterInYear] = MAX('UMC_Điểm Hòa Vốn'[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "e19d0535-6669-4be1-8dd5-43c7d85f3887",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Biến phí",
            "expression": [
              "",
              "VAR a = CALCULATE(sum('UMC_Điểm Hòa Vốn'[Value_bill]), 'UMC_Điểm Hòa Vốn'[Chỉ tiêu] = \"Biến phí\")",
              "VAR month_ = CALCULATE(sum('UMC_Điểm Hòa Vốn'[Value_bill]), 'UMC_Điểm Hòa Vốn'[Chỉ tiêu] = \"Biến phí\", 'UMC_Điểm Hòa Vốn'[YearnMonth] = MAX('UMC_Điểm Hòa Vốn'[YearnMonth]))",
              "var quarter_ = CALCULATE(sum('UMC_Điểm Hòa Vốn'[Value_bill]), 'UMC_Điểm Hòa Vốn'[Chỉ tiêu] = \"Biến phí\", 'UMC_Điểm Hòa Vốn'[QuarterInYear] = MAX('UMC_Điểm Hòa Vốn'[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "9d5ea22b-761f-4231-9f74-fd47fe7f18be",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Số dư đảm phí",
            "expression": "[DT thuần] - [Biến phí]",
            "formatString": "#,0",
            "lineageTag": "b6e53a55-44ef-42c4-b01d-8a249c1976e1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Số dư an toàn",
            "expression": "[DT thuần] - 'UMC_Điểm Hòa Vốn'[Điểm hòa vốn]",
            "formatString": "#,0",
            "lineageTag": "97afcaa8-7cd7-4fde-a9f2-086990a319b3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Tỷ lệ số dư an toàn",
            "expression": "DIVIDE('UMC_Điểm Hòa Vốn'[Số dư an toàn],[DT thuần],0)",
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "82c7debd-74cc-4f5c-9e29-c83d9f804e35"
          },
          {
            "name": "Đòn bẩy (DOL)",
            "expression": [
              "",
              "    VAR EBIT = 'UMC_Điểm Hòa Vốn'[Số dư đảm phí] - 'UMC_Điểm Hòa Vốn'[Định phí]",
              "    RETURN DIVIDE((EBIT+'UMC_Điểm Hòa Vốn'[Định phí]),EBIT,0)"
            ],
            "formatString": "#,0.0",
            "lineageTag": "cbb1b909-1668-4818-a8d8-58e84eed2449"
          },
          {
            "name": "DT thuần",
            "expression": [
              "",
              "VAR a = CALCULATE(sum('UMC_Điểm Hòa Vốn'[Value_bill]), 'UMC_Điểm Hòa Vốn'[Chỉ tiêu] = \"Doanh thu thuần\")",
              "VAR month_ = CALCULATE(sum('UMC_Điểm Hòa Vốn'[Value_bill]), 'UMC_Điểm Hòa Vốn'[Chỉ tiêu] = \"Doanh thu thuần\", 'UMC_Điểm Hòa Vốn'[YearnMonth] = MAX('UMC_Điểm Hòa Vốn'[YearnMonth]))",
              "var quarter_ = CALCULATE(sum('UMC_Điểm Hòa Vốn'[Value_bill]), 'UMC_Điểm Hòa Vốn'[Chỉ tiêu] = \"Doanh thu thuần\", 'UMC_Điểm Hòa Vốn'[QuarterInYear] = MAX('UMC_Điểm Hòa Vốn'[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "dedf6894-6654-4d85-9188-e4c7c4425537",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "LocalDateTable_8ad98c6c-2592-49d3-be92-64d686a661b3",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "d8731081-83a1-4891-8ace-ab57cb696235",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "84fba8d4-f4c6-4853-a512-fc52534037c4",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "62af810a-3be8-4779-bbbb-ef12158ce24a",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "8c423206-984b-41b9-be04-d00d1c2f222e",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "9eec6a1c-c149-4e0a-b9da-799277a82ba0",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "674bcf2a-0c1e-4513-806c-0cab6f7a72a7",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "d69a605d-304e-4d37-abeb-481a31eaf0d2",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "e369554e-0aba-490b-88b7-e3e19776247b",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_8ad98c6c-2592-49d3-be92-64d686a661b3",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('UMC_KQKD'[Parse])), 1, 1), Date(Year(MAX('UMC_KQKD'[Parse])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "7d1237f0-be1c-4ccc-afc6-c9115e0d6a17",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "d5da7659-6e80-48eb-bd08-ef64dbfe9f44"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "bfc14187-92f8-45f0-aeaf-e568cf4ca24f"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "a8d62c9f-5efc-44cd-ac03-5e896ee17b82"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "89e3890d-d7cb-4267-b565-ba628a231032"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "LocalDateTable_81224034-15ea-4f3b-959e-fc1d6244be47",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "0f2a7139-a69d-464d-b977-91b75bb49d8e",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "224bd756-7a69-4b62-a126-14260b446e99",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "d27607c3-99f8-4d41-b68c-7dc47d608a00",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "dbc63d38-3cd6-4e18-ba99-d1c9d9ea4212",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "3b57019a-de5a-4503-8e92-5c8c7bcbaf05",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "6fff8336-82c3-43a2-9886-c8c9e8c982ae",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "02b7867d-e7c4-493d-aeaa-3030c4930324",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "36cc428c-de99-43a8-bfef-046a801dea8d",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_81224034-15ea-4f3b-959e-fc1d6244be47",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('UMC_CDKT'[Parse])), 1, 1), Date(Year(MAX('UMC_CDKT'[Parse])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "6028f549-7593-4567-bfff-10da264ad47b",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "ae788a77-aa49-44cf-859f-21554e58e9a6"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "4b6e6ec4-58df-47c1-9f26-51d01c0e7114"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "3ba63ace-7d79-4ee8-9ae4-39b5b181a92a"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "caf73150-56d3-48e5-8e2c-732f8516ec08"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "UMC_Total",
        "lineageTag": "fd196e5d-c460-4d18-9dbb-6dddb0223a19",
        "columns": [
          {
            "name": "Attribute",
            "dataType": "string",
            "sourceColumn": "Attribute",
            "lineageTag": "ddb70de8-8f5e-4465-89e2-0df142b55e22",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "double",
            "sourceColumn": "Value",
            "formatString": "0.00",
            "lineageTag": "5ca43947-f46f-4a93-9587-adffde36db75",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Parse",
            "dataType": "dateTime",
            "sourceColumn": "Parse",
            "formatString": "Short Date",
            "lineageTag": "fdb55af9-dd2e-4aea-bc24-e055685b0772",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "Month Name",
            "lineageTag": "ba73a7a3-bc5e-48b1-af24-753618ea5c55",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month",
            "formatString": "0",
            "lineageTag": "3e3354cc-07a7-4364-80de-619f538115a2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "45bf46cb-1b38-4888-97a4-6463ca2b0d9b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "YearnMonth",
            "dataType": "string",
            "sourceColumn": "YearnMonth",
            "lineageTag": "498f3545-9963-406d-8e8e-e618201ec7c4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthShort",
            "dataType": "string",
            "sourceColumn": "MonthShort",
            "sortByColumn": "Month",
            "lineageTag": "9c920f82-31fd-48a0-8140-53f6d311219b",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Value_bill",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "UMC_Total[Value]/ 1000000000",
            "formatString": "#,0.00",
            "lineageTag": "175d4aa7-575d-4f60-8d0a-33693e198c34",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Chỉ tiêu",
            "dataType": "string",
            "sourceColumn": "Chỉ tiêu",
            "lineageTag": "036c11f8-fd9b-48ac-af08-bf5e740f5a9e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"UMC_Total\",\"TableItemName\":\"Chỉ tiêu (groups)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Chỉ tiêu (groups)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('UMC_Total'[Chỉ tiêu]),",
              "\t\"(Blank)\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Tiền và tương đương tiền đầu kỳ\"},",
              "\t\" Tiền đầu kỳ\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Lưu chuyển tiền thuần từ hoạt động kinh doanh\"},",
              "\t\"1. Dòng tiền thuần từ HĐKD \",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Lưu chuyển tiền thuần từ hoạt động đầu tư\"},",
              "\t\"2. Dòng tiền thuần từ HĐĐT\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Lưu chuyển tiền thuần từ hoạt động tài chính\"},",
              "\t\"3. Dòng tiền thuần từ HĐTC\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Các Khoản Phải Thu Ngắn Hạn_130\"},",
              "\t\"Các khoản phải thu ngắn hạn\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Chi phí  thuê xét nghiệm ĐHYD - Medic... liên quan KCB trong bệnh viện 63212\",",
              "\t\t\"Chi phí khác 63215\",",
              "\t\t\"Chi phí mua máu, tiểu cầu, dịch truyền 63220\",",
              "\t\t\"Giá vốn chi phí khấu hao TSCĐ 63209\",",
              "\t\t\"Giá vốn phân bổ CCDC và chi phí trả trước 63210\",",
              "\t\t\"KCB Cận lâm sàng (Ngoại trú)-LDLK 63205\",",
              "\t\t\"KCB Cận lâm sàng (Nội trú)-LDLK 63206\"},",
              "\t\"Chi phí khác\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Chuyển Nộp Về Nhà Trường_3365\"},",
              "\t\"Chuyển nộp về nhà trường\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Doanh thu thuần về cung cấp dịch vụ\"},",
              "\t\"Doanh thu thuần\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Giá vốn hàng bán\"},",
              "\t\"Giá vốn kế hoạch\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Hàng Tồn Kho_140\"},",
              "\t\"Hàng Tồn Kho\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Doanh thu KCB ngoại trú 511302\"},",
              "\t\"KCB ngoại trú\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Doanh thu KCB nội trú 511301\"},",
              "\t\"KCB nội trú\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Lợi nhuận sau thuế TNDN\"},",
              "\t\"Lợi nhuận sau thuế\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Giá vốn: Chi phí tiền lương - trích Bảo hiểm 63219\"},",
              "\t\"Lương, phụ cấp\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Giá vốn - Chi phí nguyên vật liệu 63217\"},",
              "\t\"Nguyên vật liệu\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Doanh thu nhà thuốc 511311\"},",
              "\t\"Nhà thuốc\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Quỹ Bổ Sung Thu Nhập_\"},",
              "\t\"Quỹ bổ sung thu nhập\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Quỹ Đầu Tư Phát Triển_418\"},",
              "\t\"Quỹ đầu tư phát triển\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Quỹ Hỗ Trợ Khám Bệnh, Chữa Bệnh_\"},",
              "\t\"Quỹ hỗ trợ khám bệnh, chữa bệnh\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Quỹ Khen Thưởng_\"},",
              "\t\"Quỹ khen thưởng\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Quỹ Phúc Lợi_\"},",
              "\t\"Quỹ phúc lợi\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Doanh thu các dịch vụ: hội nghị, phí quản lý, cho thuê…. 511314\",",
              "\t\t\"Doanh thu hoạt động nghiên cứu khoa học 5115\",",
              "\t\t\"Doanh thu KCB cận lâm sàng (ngoại trú) 511304\",",
              "\t\t\"Doanh thu KCB nội ngoại trú 511307\",",
              "\t\t\"Doanh thu khác 5118\",",
              "\t\t\"Doanh thu liên quan KCB - ngoài bệnh viện 511313\",",
              "\t\t\"Doanh thu liên quan KCB - trong bệnh viện 511312\",",
              "\t\t\"Nguồn thu từ NSNN chi hoạt động PCD 5119\"},",
              "\t\"Thu khác\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Giá vốn: Thù lao dịch vụ 63218\"},",
              "\t\"Thù lao dịch vụ\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Giá vốn Thuốc - Khoa Dược 63216\"},",
              "\t\"Thuốc Khoa dược\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Giá vốn Thuốc - Nhà thuốc 63211\"},",
              "\t\"Thuốc Nhà thuốc\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Tiền và tương đương tiền cuối kỳ (70=50+60+61)\"},",
              "\t\"Tiền cuối kỳ\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Các Khoản Tương Đương Tiền_112\"},",
              "\t\"Tiền gửi có kỳ hạn < 3 tháng\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Đầu Tư Nắm Giữ Đến Ngày Đáo Hạn_123\"},",
              "\t\"Tiền gửi có kỳ hạn > 3 tháng\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Tiền_111\"},",
              "\t\"Tiền gửi không kỳ hạn\",",
              "\t'UMC_Total'[Chỉ tiêu] IN {\"Tiền Và Các Khoản Tương Đương Tiền_110\"},",
              "\t\"Tiền gửi ngân hàng\",",
              "\t'UMC_Total'[Chỉ tiêu]",
              ")"
            ],
            "lineageTag": "a7453f2d-3512-42ef-891f-6ec4071b9105",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "GroupingMetadata",
                "value": {
                  "version": 0,
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "UMC_Total"
                          }
                        },
                        "Property": "Chỉ tiêu"
                      }
                    }
                  ]
                }
              }
            ],
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"u\",\"Entity\":\"UMC_Total\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"GroupItems\":[{\"DisplayName\":\"(Blank)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\" Tiền đầu kỳ\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Tiền và tương đương tiền đầu kỳ'\"}}]]}}},{\"DisplayName\":\"1. Dòng tiền thuần từ HĐKD \",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Lưu chuyển tiền thuần từ hoạt động kinh doanh'\"}}]]}}},{\"DisplayName\":\"2. Dòng tiền thuần từ HĐĐT\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Lưu chuyển tiền thuần từ hoạt động đầu tư'\"}}]]}}},{\"DisplayName\":\"3. Dòng tiền thuần từ HĐTC\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Lưu chuyển tiền thuần từ hoạt động tài chính'\"}}]]}}},{\"DisplayName\":\"Các khoản phải thu ngắn hạn\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Các Khoản Phải Thu Ngắn Hạn_130'\"}}]]}}},{\"DisplayName\":\"Chi phí khác\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Chi phí  thuê xét nghiệm ĐHYD - Medic... liên quan KCB trong bệnh viện 63212'\"}}],[{\"Literal\":{\"Value\":\"'Chi phí khác 63215'\"}}],[{\"Literal\":{\"Value\":\"'Chi phí mua máu, tiểu cầu, dịch truyền 63220'\"}}],[{\"Literal\":{\"Value\":\"'Giá vốn chi phí khấu hao TSCĐ 63209'\"}}],[{\"Literal\":{\"Value\":\"'Giá vốn phân bổ CCDC và chi phí trả trước 63210'\"}}],[{\"Literal\":{\"Value\":\"'KCB Cận lâm sàng (Ngoại trú)-LDLK 63205'\"}}],[{\"Literal\":{\"Value\":\"'KCB Cận lâm sàng (Nội trú)-LDLK 63206'\"}}]]}}},{\"DisplayName\":\"Chuyển nộp về nhà trường\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Chuyển Nộp Về Nhà Trường_3365'\"}}]]}}},{\"DisplayName\":\"Doanh thu thuần\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Doanh thu thuần về cung cấp dịch vụ'\"}}]]}}},{\"DisplayName\":\"Giá vốn kế hoạch\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Giá vốn hàng bán'\"}}]]}}},{\"DisplayName\":\"Hàng Tồn Kho\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Hàng Tồn Kho_140'\"}}]]}}},{\"DisplayName\":\"KCB ngoại trú\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Doanh thu KCB ngoại trú 511302'\"}}]]}}},{\"DisplayName\":\"KCB nội trú\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Doanh thu KCB nội trú 511301'\"}}]]}}},{\"DisplayName\":\"Lợi nhuận sau thuế\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Lợi nhuận sau thuế TNDN'\"}}]]}}},{\"DisplayName\":\"Lương, phụ cấp\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Giá vốn: Chi phí tiền lương - trích Bảo hiểm 63219'\"}}]]}}},{\"DisplayName\":\"Nguyên vật liệu\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Giá vốn - Chi phí nguyên vật liệu 63217'\"}}]]}}},{\"DisplayName\":\"Nhà thuốc\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Doanh thu nhà thuốc 511311'\"}}]]}}},{\"DisplayName\":\"Quỹ bổ sung thu nhập\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Quỹ Bổ Sung Thu Nhập_'\"}}]]}}},{\"DisplayName\":\"Quỹ đầu tư phát triển\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Quỹ Đầu Tư Phát Triển_418'\"}}]]}}},{\"DisplayName\":\"Quỹ hỗ trợ khám bệnh, chữa bệnh\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Quỹ Hỗ Trợ Khám Bệnh, Chữa Bệnh_'\"}}]]}}},{\"DisplayName\":\"Quỹ khen thưởng\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Quỹ Khen Thưởng_'\"}}]]}}},{\"DisplayName\":\"Quỹ phúc lợi\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Quỹ Phúc Lợi_'\"}}]]}}},{\"DisplayName\":\"Thu khác\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Doanh thu các dịch vụ: hội nghị, phí quản lý, cho thuê…. 511314'\"}}],[{\"Literal\":{\"Value\":\"'Doanh thu hoạt động nghiên cứu khoa học 5115'\"}}],[{\"Literal\":{\"Value\":\"'Doanh thu KCB cận lâm sàng (ngoại trú) 511304'\"}}],[{\"Literal\":{\"Value\":\"'Doanh thu KCB nội ngoại trú 511307'\"}}],[{\"Literal\":{\"Value\":\"'Doanh thu khác 5118'\"}}],[{\"Literal\":{\"Value\":\"'Doanh thu liên quan KCB - ngoài bệnh viện 511313'\"}}],[{\"Literal\":{\"Value\":\"'Doanh thu liên quan KCB - trong bệnh viện 511312'\"}}],[{\"Literal\":{\"Value\":\"'Nguồn thu từ NSNN chi hoạt động PCD 5119'\"}}]]}}},{\"DisplayName\":\"Thù lao dịch vụ\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Giá vốn: Thù lao dịch vụ 63218'\"}}]]}}},{\"DisplayName\":\"Thuốc Khoa dược\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Giá vốn Thuốc - Khoa Dược 63216'\"}}]]}}},{\"DisplayName\":\"Thuốc Nhà thuốc\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Giá vốn Thuốc - Nhà thuốc 63211'\"}}]]}}},{\"DisplayName\":\"Tiền cuối kỳ\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Tiền và tương đương tiền cuối kỳ (70=50+60+61)'\"}}]]}}},{\"DisplayName\":\"Tiền gửi có kỳ hạn < 3 tháng\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Các Khoản Tương Đương Tiền_112'\"}}]]}}},{\"DisplayName\":\"Tiền gửi có kỳ hạn > 3 tháng\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Đầu Tư Nắm Giữ Đến Ngày Đáo Hạn_123'\"}}]]}}},{\"DisplayName\":\"Tiền gửi không kỳ hạn\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Tiền_111'\"}}]]}}},{\"DisplayName\":\"Tiền gửi ngân hàng\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"u\"}},\"Property\":\"Chỉ tiêu\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Tiền Và Các Khoản Tương Đương Tiền_110'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quarter",
            "dataType": "int64",
            "sourceColumn": "Quarter",
            "formatString": "0",
            "lineageTag": "0b099e54-060e-409d-8bb5-2781d10d68d1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "QuarterInYear",
            "dataType": "string",
            "sourceColumn": "QuarterInYear",
            "lineageTag": "e88ace18-933a-4d5f-a797-ab4f492b6f2f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "UMC_Total",
            "mode": "import",
            "queryGroup": "UMC Processed Data",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.Combine({UMC_CDKT, UMC_KQKD, UMC_LCTT}),",
                "    #\"Inserted Month Name\" = Table.AddColumn(Source, \"Month Name\", each Date.MonthName([Parse]), type text),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Month Name\", \"Month\", each Date.Month([Parse]), Int64.Type),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Inserted Month\", \"Year\", each Date.Year([Parse]), Int64.Type),",
                "    #\"Added Custom Column\" = Table.AddColumn(#\"Inserted Year\", \"YearnMonth\", each Text.Combine({Text.From([Year], \"en-US\"), Text.PadStart(Text.From([Month], \"en-US\"), 2, \"0\"), \"00\"}), type text),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom Column\",{{\"Value\", type number}, {\"Chỉ tiêu\", type text}, {\"Month\", Int64.Type}, {\"Year\", Int64.Type}}),",
                "    #\"Inserted First Characters\" = Table.AddColumn(#\"Changed Type1\", \"MonthShort\", each Text.Start([Month Name], 3), type text),",
                "    #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted First Characters\", \"Quarter\", each Date.QuarterOfYear([Parse]), Int64.Type),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Inserted Quarter\", \"QuarterInYear\", each Text.Combine({Text.From([Year], \"en-US\"), \"0\", Text.From([Quarter], \"en-US\"), \"00\"}), type text)",
                "in",
                "    #\"Inserted Merged Column\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "A5_Measure",
        "lineageTag": "e00d05da-5f65-4aa4-a34c-e414ceab66d9",
        "partitions": [
          {
            "name": "A5_Measure",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Vòng quay khoản phải thu",
            "expression": [
              "",
              "VAR x = \"Phải Thu Ngắn Hạn Của Khách Hàng _131\"",
              "",
              "VAR receivable = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR _pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR _pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR _pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_receivable = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), _pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), _pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), _pre_year)",
              "VAR receivable_turnover = DIVIDE(A3_A7_Measure[Doanh thu thuần], (receivable + pre_peroid_receivable)/2, 0)",
              "",
              "VAR default_receivable = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "VAR default_pre_peroid_receivable= CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, PREVIOUSMONTH(LASTDATE(UMC_Total[Parse])))",
              "VAR default_receivable_turnover = DIVIDE(A3_A7_Measure[Doanh thu thuần], (default_receivable + default_pre_peroid_receivable)/2, 0)",
              "",
              "return if(not(ISFILTERED(Dates_ref)), default_receivable_turnover, receivable_turnover)"
            ],
            "formatString": "0.00",
            "lineageTag": "8bab0e06-ba21-4d09-86e7-74400b939ea3"
          },
          {
            "name": "Vòng quay khoản phải trả",
            "expression": [
              "",
              "VAR x = \"Hàng Tồn Kho_140\"",
              "VAR inventory = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR inventory_pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR inventory_pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR inventory_pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_inventory = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), inventory_pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), inventory_pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), inventory_pre_year)",
              "",
              "VAR y = \"Phải Trả Người Bán Ngắn Hạn_311\"",
              "VAR payable = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =y, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR payable_pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =y), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR payable_pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =y, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR payable_pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =y, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_payable = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), payable_pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), payable_pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), payable_pre_year)",
              "",
              "VAR payable_turnover = DIVIDE((A3_A7_Measure[Giá vốn hàng bán] + inventory - pre_peroid_inventory), (payable + pre_peroid_payable)/2, 0)",
              "",
              "VAR default_inventory = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "VAR default_pre_peroid_inventory = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, PREVIOUSMONTH(LASTDATE(UMC_Total[Parse])))",
              "VAR default_payable = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = y, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "VAR default_pre_peroid_payable = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = y, PREVIOUSMONTH(LASTDATE(UMC_Total[Parse])))",
              "VAR default_payable_turnover = DIVIDE((A3_A7_Measure[Giá vốn hàng bán] + default_inventory - default_pre_peroid_inventory), (default_payable + default_pre_peroid_payable)/2, 0)",
              "",
              "return if(not(ISFILTERED(Dates_ref)), default_payable_turnover, payable_turnover)"
            ],
            "lineageTag": "2c61f9dc-9aa9-4efe-859d-7ea551291a0d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Vòng quay hàng tồn kho",
            "expression": [
              "",
              "VAR x = \"Hàng Tồn Kho_140\"",
              "",
              "VAR inventory = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR _pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR _pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR _pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_inventory = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), _pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), _pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), _pre_year)",
              "VAR inventory_turnover = DIVIDE(A3_A7_Measure[Giá vốn hàng bán], (inventory + pre_peroid_inventory)/2, 0)",
              "",
              "VAR default_inventory = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "VAR default_pre_peroid_inventory= CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, PREVIOUSMONTH(LASTDATE(UMC_Total[Parse])))",
              "VAR default_inventory_turnover = DIVIDE(A3_A7_Measure[Giá vốn hàng bán], (default_inventory + default_pre_peroid_inventory)/2, 0)",
              "",
              "return if(not(ISFILTERED(Dates_ref)), default_inventory_turnover, inventory_turnover)"
            ],
            "lineageTag": "b25ec6a8-7db5-478d-8e64-191dc34b28be",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Vòng quay tài sản cố định",
            "expression": [
              "",
              "VAR x = \"Tài Sản Cố Định_220\"",
              "VAR fixed_asset = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR fixed_asset_pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR fixed_asset_pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR fixed_asset_pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_fixed_asset = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), fixed_asset_pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), fixed_asset_pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), fixed_asset_pre_year)",
              "",
              "VAR y = \"Chi Phí Xây Dựng Cơ Bản Dở Dang_242\"",
              "VAR cip = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =y, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR cip_pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =y), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR cip_pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =y, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR cip_pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =y, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_cip = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), cip_pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), cip_pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), cip_pre_year)",
              "",
              "VAR fixed_asset_turnover = DIVIDE(A3_A7_Measure[Doanh thu thuần], (fixed_asset + pre_peroid_fixed_asset + cip + pre_peroid_cip)/2, 0)",
              "",
              "VAR default_fixed_asset = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "VAR default_pre_peroid_fixed_asset = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, PREVIOUSMONTH(LASTDATE(UMC_Total[Parse])))",
              "VAR default_cip = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = y, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "VAR default_pre_peroid_cip = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = y, PREVIOUSMONTH(LASTDATE(UMC_Total[Parse])))",
              "VAR default_fixed_asset_turnover = DIVIDE(A3_A7_Measure[Doanh thu thuần], (default_fixed_asset + default_pre_peroid_fixed_asset + default_cip + default_pre_peroid_cip) /2, 0)",
              "",
              "return if(not(ISFILTERED(Dates_ref)), default_fixed_asset_turnover, fixed_asset_turnover)"
            ],
            "lineageTag": "90497afb-41dd-494f-a36b-c57b3679ed90",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Số ngày tồn kho bình quân (DIO)",
            "expression": [
              "",
              "VAR a = 365",
              "VAR b = 90",
              "VAR c = 30",
              "",
              "VAR x = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), c,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), b,",
              "                ISFILTERED(Dates_ref[Year]),a)",
              "VAR DIO_year = DIVIDE(x, [Vòng quay hàng tồn kho], 0)",
              "VAR DIO_qtr = DIVIDE(x, [Vòng quay hàng tồn kho], 0)",
              "VAR DIO_month = DIVIDE(x,[Vòng quay hàng tồn kho], 0)",
              "",
              "return ",
              "    SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), DIO_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), DIO_qtr,",
              "                ISFILTERED(Dates_ref[Year]), DIO_year)"
            ],
            "lineageTag": "3e50177c-7aad-4604-9c90-eec960c6a10a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Số ngày trả tiền bình quân (DPO)",
            "expression": [
              "",
              "VAR a = 365",
              "VAR b = 90",
              "VAR c = 30",
              "",
              "VAR x = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), c,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), b,",
              "                ISFILTERED(Dates_ref[Year]),a)",
              "VAR DPO_year = DIVIDE(x, [Vòng quay khoản phải trả], 0)",
              "VAR DPO_qtr = DIVIDE(x, [Vòng quay khoản phải trả], 0)",
              "VAR DPO_month = DIVIDE(x, [Vòng quay khoản phải trả], 0)",
              "",
              "return ",
              "    SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), -DPO_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), -DPO_qtr,",
              "                ISFILTERED(Dates_ref[Year]), -DPO_year)"
            ],
            "lineageTag": "457f9d49-f2e1-4a95-823d-f912eeeac0b6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Tồn kho/ DT thuần",
            "expression": "DIVIDE(A4_Measure[Hàng tồn kho], A3_A7_Measure[Doanh thu thuần], 0)",
            "formatString": "#,0.0",
            "lineageTag": "24a9fa27-1a84-46ac-aed8-7406980a37d1"
          },
          {
            "name": "Year_default_Nợ phải thu",
            "expression": [
              "",
              "VAR x = \"Các Khoản Phải Thu Ngắn Hạn_130\" ",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year), STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "formatString": "0.0",
            "lineageTag": "ae81537e-b46b-4e86-b236-5eed039073ef"
          },
          {
            "name": "Year_default_Vòng quay khoản phải thu",
            "expression": [
              "",
              "VAR x = \"Các Khoản Phải Thu Ngắn Hạn_130\"",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "",
              "VAR receivable = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR _pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR _pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR _pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_receivable = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), _pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), _pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), _pre_year)",
              "VAR receivable_turnover = DIVIDE(A3_A7_Measure[Year_default_Doanh thu thuần], (receivable + pre_peroid_receivable)/2, 0)",
              "",
              "VAR default_receivable = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(Dates_ref[Date])), Dates_ref[Year] = max_year)",
              "",
              "VAR default_pre_month = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dateadd(Dates_ref[Date], -1, MONTH)), Dates_ref[Year] = max_year)",
              "VAR default_pre_quarter = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date])))), Dates_ref[Year] = max_year)",
              "VAR default_pre_peroid_receivable = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, default_pre_month,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, default_pre_quarter)",
              "VAR default_receivable_turnover = DIVIDE(A3_A7_Measure[Year_default_Doanh thu thuần], (default_receivable + default_pre_peroid_receivable)/2, 0)",
              "",
              "return if(not(HASONEVALUE(Dates_ref[Year])), default_receivable_turnover, receivable_turnover)"
            ],
            "formatString": "0.0",
            "lineageTag": "3b20ba86-d946-440a-b259-cca8ee1e449f"
          },
          {
            "name": "Year_default_DSO",
            "expression": [
              "",
              "VAR x = \"Các Khoản Phải Thu Ngắn Hạn_130\"",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR _duration = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), 30,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), 90,",
              "                ISFILTERED(Dates_ref[Year]),365)",
              "",
              "VAR receivable = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR _pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR _pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR _pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_receivable = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), _pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), _pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), _pre_year)",
              "VAR DSO = DIVIDE(((receivable + pre_peroid_receivable)/2) *_duration, A3_A7_Measure[Doanh thu thuần], 0)",
              "",
              "VAR default_receivable = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(Dates_ref[Date])), Dates_ref[Year] = max_year)",
              "",
              "VAR default_pre_month = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dateadd(Dates_ref[Date], -1, MONTH)), Dates_ref[Year] = max_year)",
              "VAR default_pre_quarter = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date])))), Dates_ref[Year] = max_year)",
              "VAR default_pre_peroid_receivable = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, default_pre_month,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, default_pre_quarter)",
              "VAR default_DSO = DIVIDE((default_receivable + default_pre_peroid_receivable)/2 *_duration, A3_A7_Measure[Year_default_Doanh thu thuần], 0)",
              "",
              "return if(not(HASONEFILTER(Dates_ref[Year])), default_DSO, DSO)"
            ],
            "formatString": "0.00",
            "lineageTag": "ee297ddb-fbb5-42da-9496-d229386280d5"
          },
          {
            "name": "Year_default_DIO",
            "expression": [
              "",
              "",
              "VAR x = \"Hàng Tồn Kho_140\"",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR _duration = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), 30,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), 90,",
              "                ISFILTERED(Dates_ref[Year]),365)",
              "",
              "VAR inventory = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR _pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR _pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR _pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_inventory = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), _pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), _pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), _pre_year)",
              "VAR DIO = DIVIDE((inventory + pre_peroid_inventory)/2 *_duration, A3_A7_Measure[Year_default_Giá vốn hàng bán], 0)",
              "",
              "VAR default_inventory = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(Dates_ref[Date])), Dates_ref[Year] = max_year)",
              "",
              "VAR default_pre_month = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dateadd(Dates_ref[Date], -1, MONTH)), Dates_ref[Year] = max_year)",
              "VAR default_pre_quarter = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date])))), Dates_ref[Year] = max_year)",
              "VAR default_pre_peroid_inventory = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, default_pre_month,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, default_pre_quarter)",
              "VAR default_DIO = DIVIDE((default_inventory + default_pre_peroid_inventory)/2 *_duration, A3_A7_Measure[Year_default_Giá vốn hàng bán], 0)",
              "",
              "return if(not(HASONEFILTER(Dates_ref[Year])), default_DIO, DIO)"
            ],
            "formatString": "0.00",
            "lineageTag": "e497c640-0bd3-4e11-ac5d-f8ed7ca04e98"
          },
          {
            "name": "Year_default_Vòng quay hàng tồn kho",
            "expression": [
              "",
              "VAR x = \"Hàng Tồn Kho_140\"",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "",
              "VAR inventory = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR _pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR _pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR _pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_inventory = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), _pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), _pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), _pre_year)",
              "VAR inventory_turnover = DIVIDE(A3_A7_Measure[Year_default_Giá vốn hàng bán], (inventory + pre_peroid_inventory)/2, 0)",
              "",
              "VAR default_inventory = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(Dates_ref[Date])), Dates_ref[Year] = max_year)",
              "",
              "VAR default_pre_month = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dateadd(Dates_ref[Date], -1, MONTH)), Dates_ref[Year] = max_year)",
              "VAR default_pre_quarter = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date])))), Dates_ref[Year] = max_year)",
              "VAR default_pre_peroid_inventory = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, default_pre_month,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, default_pre_quarter)",
              "VAR default_inventory_turnover = DIVIDE(A3_A7_Measure[Year_default_Giá vốn hàng bán], (default_inventory + default_pre_peroid_inventory)/2, 0)",
              "",
              "return if(not(HASONEFILTER(Dates_ref[Year])), default_inventory_turnover, inventory_turnover)"
            ],
            "formatString": "0.0",
            "lineageTag": "e4b13685-f9d2-4dbb-b1a7-1f0ec5559632"
          },
          {
            "name": "Year_default_Nợ phải trả",
            "expression": [
              "",
              "VAR x = \"Phải Trả Người Bán Ngắn Hạn_311\" ",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year), STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "formatString": "0.00",
            "lineageTag": "0d6041ad-256e-4368-a103-0f0cb2ecba06"
          },
          {
            "name": "Year_default_DPO",
            "expression": [
              "",
              "",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR _duration = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), 30,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), 90,",
              "                ISFILTERED(Dates_ref[Year]),365)",
              "",
              "VAR x = \"Phải Trả Người Bán Ngắn Hạn_311\"",
              "VAR payable = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR _pre_month =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR _pre_quarter = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR _pre_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_payable = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), _pre_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), _pre_quarter,",
              "                ISFILTERED(Dates_ref[Year]), _pre_year)",
              "",
              "VAR y = \"Hàng Tồn Kho_140\"",
              "VAR inventory = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =y, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR _pre_month1 =  CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =y), PREVIOUSMONTH(Dates_ref[Date]))",
              "VAR _pre_quarter1 = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =y, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date]))))",
              "VAR _pre_year1 = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =y, STARTOFMONTH(LASTDATE(PREVIOUSYEAR(Dates_ref[Date]))))",
              "VAR pre_peroid_inventory = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), _pre_month1,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), _pre_quarter1,",
              "                ISFILTERED(Dates_ref[Year]), _pre_year1)",
              "",
              "VAR DPO = DIVIDE((payable + pre_peroid_payable)/2 * _duration, A3_A7_Measure[Year_default_Giá vốn hàng bán] + inventory - pre_peroid_inventory, 0)",
              "",
              "VAR default_payable = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(Dates_ref[Date])), Dates_ref[Year] = max_year)",
              "",
              "VAR default_pre_month = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dateadd(Dates_ref[Date], -1, MONTH)), Dates_ref[Year] = max_year)",
              "VAR default_pre_quarter = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date])))), Dates_ref[Year] = max_year)",
              "VAR default_pre_peroid_payable = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, default_pre_month,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, default_pre_quarter)",
              "",
              "VAR default_inventory = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(Dates_ref[Date])), Dates_ref[Year] = max_year)",
              "",
              "VAR default_pre_month1 = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dateadd(Dates_ref[Date], -1, MONTH)), Dates_ref[Year] = max_year)",
              "VAR default_pre_quarter1 = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(LASTDATE(PREVIOUSQUARTER(Dates_ref[Date])))), Dates_ref[Year] = max_year)",
              "VAR default_pre_peroid_inventory = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, default_pre_month1,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, default_pre_quarter1)",
              "",
              "VAR default_DPO = DIVIDE((default_payable + default_pre_peroid_payable)/2 * _duration, A3_A7_Measure[Year_default_Giá vốn hàng bán] + default_inventory - default_pre_peroid_inventory, 0)",
              "",
              "return if(not(HASONEFILTER(Dates_ref[Year])), -default_DPO, -DPO)"
            ],
            "formatString": "0.00",
            "lineageTag": "ef292a42-ab47-4fc8-a25f-b0dc1258d12b"
          },
          {
            "name": "Year_default_Tồn kho/ DT thuần",
            "expression": "DIVIDE(A4_Measure[Year_default_Hàng tồn kho], A3_A7_Measure[Year_default_Doanh thu thuần], 0)",
            "formatString": "0.00",
            "lineageTag": "06f1ee41-0e58-4142-b551-80e1c3b69681"
          },
          {
            "name": "Vòng quay tiền mặt (CCC)",
            "expression": "[Số ngày tồn kho bình quân (DIO)] + [Số ngày thu tiền bình quân (DSO)] + [Số ngày trả tiền bình quân (DPO)]",
            "lineageTag": "28823039-5c26-4a7d-8e19-41a52a6a10a8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Số ngày thu tiền bình quân (DSO)",
            "expression": [
              "",
              "VAR a = 365",
              "VAR b = 90",
              "VAR c = 30",
              "",
              "VAR x = SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), c,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), b,",
              "                ISFILTERED(Dates_ref[Year]),a)",
              "VAR DSO_year = DIVIDE(x, [Vòng quay khoản phải thu], 0)",
              "VAR DSO_qtr = DIVIDE(x, [Vòng quay khoản phải thu], 0)",
              "VAR DSO_month = DIVIDE(x, [Vòng quay khoản phải thu], 0)",
              "",
              "return ",
              "    SWITCH(True,",
              "                (ISFILTERED(Dates_ref[VN_Month])), DSO_month,",
              "                ISFILTERED(Dates_ref[VN_Quarter]), DSO_qtr,",
              "                ISFILTERED(Dates_ref[Year]), DSO_year)"
            ],
            "lineageTag": "9445e034-d195-41e1-97a6-b1e31cf12ca8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Year_default_CCC",
            "expression": "[Year_default_DSO] + [Year_default_DIO] + [Year_default_DPO]",
            "formatString": "0.00",
            "lineageTag": "d67c3b68-fc3f-4c71-9ef1-3126161a2f8d"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Qtr-Month Switch",
        "lineageTag": "f23f2e9e-4006-4401-9ba0-b2e71ff78b8b",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Qtr-Month Switch",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Qtr-Month Switch Order",
            "lineageTag": "5c26b88c-39fa-4dd9-a4f1-8bebb9a63b29",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Qtr-Month Switch Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Qtr-Month Switch Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Qtr-Month Switch Order",
            "lineageTag": "2088e03d-3c3f-4a67-87c9-b510fac1630a",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Qtr-Month Switch Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "81f0c1ed-a570-43b4-b375-693e012ccba3",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Qtr-Month Switch",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"theo Quý\", NAMEOF('Dates_ref'[VN_Quarter]), 0),",
                "    (\"theo Tháng\", NAMEOF('Dates_ref'[VN_Month]), 1)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a5613b46317a449ba3f43572aabc8642"
          }
        ]
      },
      {
        "name": "A2_KQHD_actual",
        "isHidden": true,
        "lineageTag": "f9872eea-ab7c-4b39-8f0a-5914f3ab3d84",
        "columns": [
          {
            "name": "Cơ sở",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Cơ sở",
            "formatString": "0",
            "lineageTag": "a708a74f-4b9d-4a98-b5e1-ae960a8849bd",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Nội dung",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Nội dung",
            "lineageTag": "c2d63372-85ed-4e80-90b7-177bd1427282",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Tháng",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Tháng",
            "lineageTag": "e018002e-95ca-4f48-b0a2-d8b2ed218fd2",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Value",
            "formatString": "#,0.00",
            "lineageTag": "392059a9-f5a5-415c-9d54-51ac534ff342",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Date",
            "formatString": "Short Date",
            "lineageTag": "eb9bb550-29d0-4b66-b486-6014e8b48718",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR(A2_KQHD_actual[Date])",
            "formatString": "0",
            "lineageTag": "a1b616a8-5abe-4c49-ad7a-5e0aeb15e705",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "A2_KQHD_actual",
            "mode": "import",
            "queryGroup": "UMC Processed Data",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DATA\\DATA_FINANCE\\02. CO SO DU LIEU\\01. Ke hoach hoat dong - L2.xlsx\"), null, true),",
                "    A2_KQHD_Sheet = Source{[Item=\"A2_KQHD\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(A2_KQHD_Sheet,{{\"Column1\", type any}, {\"Column2\", type text}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"Column7\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}, {\"Column14\", type any}, {\"Column15\", type any}, {\"Column16\", type any}, {\"Column17\", type any}, {\"Column18\", type any}, {\"Column19\", type any}, {\"Column20\", type any}, {\"Column21\", type any}, {\"Column22\", type any}, {\"Column23\", type any}, {\"Column24\", type any}, {\"Column25\", type any}, {\"Column26\", type any}, {\"Column27\", type any}, {\"Column28\", type any}, {\"Column29\", type any}, {\"Column30\", type any}, {\"Column31\", type any}, {\"Column32\", type any}, {\"Column33\", type any}, {\"Column34\", type any}, {\"Column35\", type any}, {\"Column36\", type any}, {\"Column37\", type any}, {\"Column38\", type any}, {\"Column39\", type any}, {\"Column40\", type any}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Cơ sở\", Int64.Type}, {\"Nội dung\", type text}, {\"Kế hoạch 2021\", type number}, {\"Thực tế 2021#(lf)(lũy kế)\", type number}, {\"01/2021\", type number}, {\"02/2021\", type number}, {\"03/2021\", type number}, {\"04/2021\", type number}, {\"05/2021\", type number}, {\"06/2021\", type number}, {\"07/2021\", type number}, {\"08/2021\", type number}, {\"09/2021\", type number}, {\"10/2021\", type number}, {\"11/2021\", type number}, {\"12/2021\", type number}, {\"01/2022\", type number}, {\"02/2022\", type number}, {\"03/2022\", type number}, {\"04/2022\", type number}, {\"05/2022\", type number}, {\"06/2022\", type number}, {\"07/2022\", type number}, {\"08/2022\", type number}, {\"09/2022\", type number}, {\"10/2022\", type number}, {\"11/2022\", type number}, {\"12/2022\", type number}, {\"01/2023\", type number}, {\"02/2023\", type number}, {\"03/2023\", type number}, {\"04/2023\", type number}, {\"05/2023\", type number}, {\"06/2023\", type number}, {\"07/2023\", type number}, {\"08/2023\", type number}, {\"09/2023\", type number}, {\"10/2023\", type number}, {\"11/2023\", type number}, {\"12/2023\", type number}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"Kế hoạch 2021\", \"Thực tế 2021#(lf)(lũy kế)\"}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Removed Columns\", {\"Cơ sở\", \"Nội dung\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"Tháng\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Value\", type number}}),",
                "    #\"Inserted Date\" = Table.AddColumn(#\"Changed Type2\", \"Date\", each Date.From([Tháng]), type date),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Inserted Date\",{\"Cơ sở\", \"Value\", \"Date\", \"Nội dung\", \"Tháng\"})",
                "in",
                "    #\"Reordered Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "A2_Thực hiện",
            "expression": "SUM(A2_KQHD_actual[Value]) /10^9",
            "formatString": "#,0.0",
            "isHidden": true,
            "lineageTag": "2ce946d7-2e0b-429f-a201-fe680eb415ef",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "A2_KQHD_plan",
        "lineageTag": "466e1385-71e8-46b3-88d6-050050f8198a",
        "columns": [
          {
            "name": "Cơ sở",
            "dataType": "int64",
            "sourceColumn": "Cơ sở",
            "formatString": "0",
            "lineageTag": "dc7f4d37-c613-49c2-8c28-4286a9ef1f98",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "name": "Nội dung",
            "dataType": "string",
            "sourceColumn": "Nội dung",
            "lineageTag": "f6ba9725-2c76-4a95-97e6-7461fa1344ea",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Kế hoạch",
            "dataType": "double",
            "sourceColumn": "Kế hoạch",
            "formatString": "#,0.00",
            "lineageTag": "e266e636-b6b3-4410-9ff1-77a28b85718d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Năm",
            "dataType": "int64",
            "sourceColumn": "Năm",
            "formatString": "0",
            "lineageTag": "d820d715-2623-476a-b920-a0424d135cf1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "A2_KQHD_plan",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DATA\\DATA_FINANCE\\02. CO SO DU LIEU\\01. Ke hoach hoat dong - L2.xlsx\"), null, true),",
                "    A2_KQHD_plan_Sheet = Source{[Item=\"A2_KQHD_plan\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(A2_KQHD_plan_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Cơ sở\", Int64.Type}, {\"Nội dung\", type text}, {\"Kế hoạch\", type number}, {\"Năm\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "A2_Kế hoạch",
            "expression": [
              "",
              "var _total = (SUM(A2_KQHD_plan[Kế hoạch])) /10^9",
              "return  _total",
              "  //  if(ISFILTERED(Dates_ref[VN_Month]), _total /12, _total) "
            ],
            "formatString": "#,0",
            "lineageTag": "851730f0-1452-4dac-82f0-72c48ea44264",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "A2_KQHD_Noidung_ref",
        "lineageTag": "bcbbd839-bfbb-46d8-9d4c-956612787e32",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Nội dung",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "A2_Union_Actual[Nội dung]",
            "lineageTag": "6b55d404-164d-4c01-bea9-57e2429c7fc8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "A2_KQHD_Noidung_ref",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "DISTINCT(A2_Union_Actual[Nội dung])"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b4327e7a517a40638ef7da3032007546"
          }
        ]
      },
      {
        "name": "A2_KQHD_Coso_ref",
        "lineageTag": "5a533cd5-2d68-480d-9b16-1d50608b53bd",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Cơ sở",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "A2_KQHD_plan[Cơ sở]",
            "formatString": "0",
            "lineageTag": "27a96c9a-c066-44d0-841d-97ce56e19b6c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "A2_KQHD_Coso_ref",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "VALUES(A2_KQHD_plan[Cơ sở])"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "05f2a2e9bdae49b19d3b18f7b2b64f89"
          }
        ]
      },
      {
        "name": "A6_Measure",
        "lineageTag": "3051aca6-e3a2-425d-81d8-acc5f3205566",
        "partitions": [
          {
            "name": "A6_Measure",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Dòng tiền đầu kỳ",
            "expression": [
              "",
              "VAR x = \"Tiền và tương đương tiền đầu kỳ\" ",
              "VAR month_quarter =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, STARTOFMONTH(FIRSTDATE(Dates_ref[Date])))",
              "Var only_year = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[Month] = 1)",
              "var a = ",
              "if(",
              "    (ISFILTERED(Dates_ref[VN_Month]) ",
              "    || ISFILTERED(Dates_ref[VN_Quarter])),",
              "    month_quarter, ",
              "    only_year",
              "    )",
              "VAR month_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "var quarter_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, UMC_Total[QuarterInYear] = MAX(UMC_Total[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)"
            ],
            "lineageTag": "b5b6ea54-f40c-460a-95f4-13afce64ece8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Dòng tiền thu",
            "expression": [
              "",
              "VAR x = {\"Tiền thu từ bán hàng, cung cấp dịch vụ và doanh thu khác\",",
              "            \"Tiền thu khác từ hoạt động kinh doanh\",",
              "            \"Tiền thu từ thanh lý, nhượng bán TSCĐ và các tài sản dài hạn khác\",",
              "            \"Tiền thu hồi đầu tư góp vốn vào đơn vị khác\",",
              "            \"Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia\",",
              "            \"Tiền thu từ phát hành cổ phiếu, nhận vốn góp của chủ sở hữu\",",
              "            \"Tiền thu từ đi vay\",",
              "            \"Tiền thu hồi cho vay, bán lại các công cụ nợ của đơn vị khác\"}",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] in x)",
              "VAR month_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] in x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "var quarter_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] in x, UMC_Total[QuarterInYear] = MAX(UMC_Total[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)"
            ],
            "lineageTag": "e3a8a7fb-c651-431a-9611-b9d6a9ce9c8a",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Dòng tiền chi",
            "expression": [
              "",
              "VAR x = {\"Tiền chi trả cho người cung cấp hàng hoá và dịch vụ\",",
              "            \"Tiền chi trả cho người lao động\",",
              "            \"Tiền lãi vay đã trả\",",
              "            \"Thuế thu nhập doanh nghiệp đã nộp\",",
              "            \"Tiền chi khác cho hoạt động kinh doanh\",",
              "            \"Tiền chi để mua sắm, xây dựng TSCĐ và các tài sản dài hạn khác\",",
              "            \"Tiền chi cho vay, mua các công cụ nợ của đơn vị khác\",",
              "            \"Tiền chi đầu tư góp vốn vào đơn vị khác\",",
              "            \"Tiền trả lại vốn góp cho các chủ sở hữu, mua lại cổ phiếu  của doanh nghiệp đã phát hành\",",
              "            \"Tiền trả nợ gốc vay\",",
              "            \"Tiền trả nợ gốc thuê tài chính\",",
              "            \"Cổ tức, lợi nhuận đã trả cho chủ sở hữu\"}",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] in x)",
              "VAR month_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] in x, UMC_Total[YearnMonth] = MAX(UMC_Total[YearnMonth]))",
              "var quarter_ = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] in x, UMC_Total[QuarterInYear] = MAX(UMC_Total[QuarterInYear]))",
              "VAR b = SWITCH(True,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 1, month_,",
              "                SELECTEDVALUE('Qtr-Month Switch'[Qtr-Month Switch Order]) = 0, quarter_)",
              "return if(not(ISFILTERED(Dates_ref)), b, a)"
            ],
            "lineageTag": "152a6f82-ee6d-46b3-b890-fda79d923fc2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Dòng tiền thuần",
            "expression": "A6_Measure[Dòng tiền thu] + A6_Measure[Dòng tiền chi]",
            "lineageTag": "d7f2e631-4264-44db-86cf-862bb8715cc9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Dòng tiền cuối  kì",
            "expression": "A6_Measure[Dòng tiền đầu kỳ] + A6_Measure[Dòng tiền thu] + A6_Measure[Dòng tiền chi]",
            "lineageTag": "05641157-75a6-47f6-8e02-654d4c884acd",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Hệ số tạo tiền",
            "expression": "ABS(DIVIDE(A6_Measure[Dòng tiền thu], A6_Measure[Dòng tiền chi], 0))",
            "formatString": "#,0.0",
            "lineageTag": "3ff0d3d3-297b-442d-88cd-20f11bb4bb2a"
          },
          {
            "name": "Các khoản phải trả",
            "expression": [
              "",
              "VAR x = \"Phải Trả Người Bán Ngắn Hạn_311\"",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year), STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "lineageTag": "6e9df375-2d79-4698-bfcd-aa49883cce73",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Các khoản phải thu",
            "expression": [
              "",
              "VAR x = \"Các Khoản Phải Thu Ngắn Hạn_130\"",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] =x, STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "VAR b = CALCULATE(CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] = x, Dates_ref[Year] = max_year), STARTOFMONTH(LASTDATE(Dates_ref[Date])))",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "lineageTag": "dcaba219-077f-4190-962c-4d7e71741380",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Chênh lệch thu",
            "expression": "A6_Measure[Các khoản phải thu] - A6_Measure[Dòng tiền thu]",
            "lineageTag": "4311549f-0081-4180-b0da-3adb4e2db19b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Chênh lệch chi",
            "expression": "A6_Measure[Các khoản phải trả] - abs(A6_Measure[Dòng tiền chi])",
            "lineageTag": "d5d958a7-375f-4e76-94fe-f890b552fa61",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Received",
            "expression": [
              "",
              "// DIVIDE( A6_Measure[Các khoản phải thu], A4_Measure[Tài sản_ngắn hạn], 0)",
              "    DIVIDE([Các khoản phải thu], A3_A7_Measure[Year_default_Tổng tài sản],0)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "62245775-f2c0-41ab-bd95-2a5c0d3a84c3"
          },
          {
            "name": "Dòng tiền chi_abs",
            "expression": "abs(A6_Measure[Dòng tiền chi])",
            "lineageTag": "a70050c0-2207-4cf5-afc0-8c6c2f2f94bd",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Paid",
            "expression": [
              "",
              "// DIVIDE(A6_Measure[Dòng tiền chi_abs], A6_Measure[Các khoản phải trả], 0)",
              "DIVIDE(A4_Measure[Nợ_ngắn hạn], A3_A7_Measure[Year_default_Tổng tài sản], 0)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dc72184c-b4a4-4a90-95a3-5f052436ab33"
          },
          {
            "name": "Dòng tiền thuần_abs",
            "expression": "ABS(A6_Measure[Dòng tiền thuần])",
            "lineageTag": "78c4907e-34c0-4b39-9948-9f14927469af",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Dòng tiền thu",
            "expression": [
              "",
              "VAR x = {\"Tiền thu từ bán hàng, cung cấp dịch vụ và doanh thu khác\",",
              "            \"Tiền thu khác từ hoạt động kinh doanh\",",
              "            \"Tiền thu từ thanh lý, nhượng bán TSCĐ và các tài sản dài hạn khác\",",
              "            \"Tiền thu hồi đầu tư góp vốn vào đơn vị khác\",",
              "            \"Tiền thu lãi cho vay, cổ tức và lợi nhuận được chia\",",
              "            \"Tiền thu từ phát hành cổ phiếu, nhận vốn góp của chủ sở hữu\",",
              "            \"Tiền thu từ đi vay\",",
              "            \"Tiền thu hồi cho vay, bán lại các công cụ nợ của đơn vị khác\"}",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] in x)",
              "VAR b = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] in x, Dates_ref[Year] = max_year)",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "7cf910ae-b929-4afd-a506-9fb14ce3de76",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Dòng tiền chi",
            "expression": [
              "",
              "VAR x = {\"Tiền chi trả cho người cung cấp hàng hoá và dịch vụ\",",
              "            \"Tiền chi trả cho người lao động\",",
              "            \"Tiền lãi vay đã trả\",",
              "            \"Thuế thu nhập doanh nghiệp đã nộp\",",
              "            \"Tiền chi khác cho hoạt động kinh doanh\",",
              "            \"Tiền chi để mua sắm, xây dựng TSCĐ và các tài sản dài hạn khác\",",
              "            \"Tiền chi cho vay, mua các công cụ nợ của đơn vị khác\",",
              "            \"Tiền chi đầu tư góp vốn vào đơn vị khác\",",
              "            \"Tiền trả lại vốn góp cho các chủ sở hữu, mua lại cổ phiếu  của doanh nghiệp đã phát hành\",",
              "            \"Tiền trả nợ gốc vay\",",
              "            \"Tiền trả nợ gốc thuê tài chính\",",
              "            \"Cổ tức, lợi nhuận đã trả cho chủ sở hữu\"}",
              "VAR max_year = CALCULATE(MAX(Dates_ref[Year]), REMOVEFILTERS(Dates_ref))",
              "VAR a =  CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] in x)",
              "VAR b = CALCULATE(SUM(UMC_Total[Value_bill]), UMC_Total[Chỉ tiêu] in x, Dates_ref[Year] = max_year)",
              "// return if(not(HASONEFILTER(Dates_ref[Year])), abs(b), abs(a))",
              "return if(not(HASONEFILTER(Dates_ref[Year])), b, a)"
            ],
            "formatString": "#,0",
            "lineageTag": "9d651400-5545-4561-bce5-f8f3633e0306",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Dòng tiền thuần",
            "expression": "A6_Measure[Year_default_Dòng tiền thu] + A6_Measure[Year_default_Dòng tiền chi]",
            "formatString": "#,0",
            "lineageTag": "19c52961-a175-4c84-bb8f-f3bc4eae1704",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Dòng tiền đầu kỳ",
            "expression": [
              "",
              "[Dòng tiền đầu kỳ]"
            ],
            "lineageTag": "d61bda64-b448-4629-91fa-fffa4c221d78",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Dòng tiền cuối kỳ",
            "expression": "A6_Measure[Year_default_Dòng tiền đầu kỳ] + A6_Measure[Year_default_Dòng tiền thu] + A6_Measure[Year_default_Dòng tiền chi]",
            "lineageTag": "00097b58-4033-4d0e-bf12-d85a46188ff5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Year_default_Value_bill",
            "expression": "IF(SELECTEDVALUE(UMC_Total[Chỉ tiêu]) = \"Tiền và tương đương tiền đầu kỳ\", [Dòng tiền đầu kỳ], CALCULATE(sum(UMC_Total[Value_bill])))",
            "formatString": "0",
            "lineageTag": "885870e3-ad35-4679-8246-6b72e9f722dc"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "UMC_LCTT",
        "lineageTag": "f35ce6a9-7c2d-4e9a-ad63-344b6010f5ea",
        "columns": [
          {
            "name": "Chỉ tiêu",
            "dataType": "string",
            "sourceColumn": "Chỉ tiêu",
            "lineageTag": "40395046-42fa-4d38-b1a1-47895c5f496f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Attribute",
            "dataType": "string",
            "sourceColumn": "Attribute",
            "lineageTag": "727d8a95-7657-4904-8efa-3680fb33d64f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "int64",
            "sourceColumn": "Value",
            "lineageTag": "c1148729-a1b4-4368-94fa-ca9a639fa9c1",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Parse",
            "dataType": "dateTime",
            "sourceColumn": "Parse",
            "formatString": "Short Date",
            "lineageTag": "61126b2b-054e-42eb-aa4a-7ecbc331f25f",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "abc79ba5-000c-4261-adf4-136c3e3ef364",
                "defaultHierarchy": {
                  "table": "LocalDateTable_bd4459e3-a3b9-4b5e-9661-ef18bc474853",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "UMC_LCTT",
            "mode": "import",
            "queryGroup": "UMC Raw Data",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DATA\\DATA_FINANCE\\02. CO SO DU LIEU\\02. Bao cao tai chinh - L3_L4_L5_L6_L7.xlsx\"), null, true),",
                "    LCTT1 = Source{[Name=\"LCTT\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(LCTT1, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type text}, {\"Chỉ tiêu\", type text}, {\"Mã số\", Int64.Type}, {\"Thuyết minh\", type text}, {\"Kỳ 1/2021\", Int64.Type}, {\"Kỳ 2/2021\", Int64.Type}, {\"Kỳ 3/2021\", Int64.Type}, {\"Kỳ 4/2021\", Int64.Type}, {\"Kỳ 5/2021\", Int64.Type}, {\"Kỳ 6/2021\", Int64.Type}, {\"Kỳ 7/2021\", Int64.Type}, {\"Kỳ 8/2021\", Int64.Type}, {\"Kỳ 9/2021\", Int64.Type}, {\"Kỳ 10/2021\", Int64.Type}, {\"Kỳ 11/2021\", Int64.Type}, {\"Kỳ 12/2021\", Int64.Type}, {\"Kỳ 1/2022\", Int64.Type}, {\"Kỳ 2/2022\", Int64.Type}, {\"Kỳ 3/2022\", Int64.Type}, {\"Kỳ 4/2022\", Int64.Type}, {\"Kỳ 5/2022\", Int64.Type}, {\"Kỳ 6/2022\", Int64.Type}, {\"Kỳ 7/2022\", Int64.Type}, {\"Kỳ 8/2022\", Int64.Type}, {\"Kỳ 9/2022\", Int64.Type}, {\"Kỳ 10/2022\", Int64.Type}, {\"Kỳ 11/2022\", Int64.Type}, {\"Kỳ 12/2022\", Int64.Type}, {\"Kỳ 1/2023\", Int64.Type}, {\"Kỳ 2/2023\", Int64.Type}, {\"Kỳ 3/2023\", Int64.Type}, {\"Kỳ 4/2023\", Int64.Type}, {\"Kỳ 5/2023\", Int64.Type}, {\"Kỳ 6/2023\", Int64.Type}, {\"Kỳ 7/2023\", Int64.Type}, {\"Kỳ 8/2023\", Int64.Type}, {\"Kỳ 9/2023\", Int64.Type}, {\"Kỳ 10/2023\", Int64.Type}, {\"Kỳ 11/2023\", Int64.Type}, {\"Kỳ 12/2023\", Int64.Type}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([Mã số] <> null)),",
                "    #\"Added Custom Column\" = Table.AddColumn(#\"Filtered Rows\", \"Split\", each let splitChỉtiêu = List.Reverse(Splitter.SplitTextByDelimiter(\". \", QuoteStyle.None)([Chỉ tiêu])) in splitChỉtiêu{0}?, type text),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Added Custom Column\", \"Custom\", each Text.Trim([Split])),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Added Custom\",{\"Custom\", \"Kỳ 1/2021\", \"Kỳ 2/2021\", \"Kỳ 3/2021\", \"Kỳ 4/2021\", \"Kỳ 5/2021\", \"Kỳ 6/2021\", \"Kỳ 7/2021\", \"Kỳ 8/2021\", \"Kỳ 9/2021\", \"Kỳ 10/2021\", \"Kỳ 11/2021\", \"Kỳ 12/2021\", \"Kỳ 1/2022\", \"Kỳ 2/2022\", \"Kỳ 3/2022\", \"Kỳ 4/2022\", \"Kỳ 5/2022\", \"Kỳ 6/2022\", \"Kỳ 7/2022\", \"Kỳ 8/2022\", \"Kỳ 9/2022\", \"Kỳ 10/2022\", \"Kỳ 11/2022\", \"Kỳ 12/2022\", \"Kỳ 1/2023\", \"Kỳ 2/2023\", \"Kỳ 3/2023\", \"Kỳ 4/2023\", \"Kỳ 5/2023\", \"Kỳ 6/2023\", \"Kỳ 7/2023\", \"Kỳ 8/2023\", \"Kỳ 9/2023\", \"Kỳ 10/2023\", \"Kỳ 11/2023\", \"Kỳ 12/2023\"}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Removed Other Columns\", {\"Custom\"}, \"Attribute\", \"Value\"),",
                "    #\"Inserted Parsed Date\" = Table.AddColumn(#\"Unpivoted Other Columns\", \"Parse\", each Date.From(DateTimeZone.From(Text.AfterDelimiter([Attribute], \" \"))), type date),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Parsed Date\",{{\"Custom\", \"Chỉ tiêu\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ]
      },
      {
        "name": "LocalDateTable_bd4459e3-a3b9-4b5e-9661-ef18bc474853",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "054c90a8-4511-4783-9037-9d2b22a93de1",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "cd754504-116c-455c-8703-dade7d809a67",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "70a54afd-2e2a-46fa-8578-5c75285240e5",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "ce01f003-3f2a-4579-84fd-a5285d84bcf6",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "6d4d8543-f566-4fc1-b8ad-cbac006c3113",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "bdd83048-cca5-48ca-83c7-a116290bb1f7",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "728d6c68-7e16-4cbe-8bf2-20ca458bb90c",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "94187f64-7772-4017-9aff-fe4eef89f303",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_bd4459e3-a3b9-4b5e-9661-ef18bc474853",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('UMC_LCTT'[Parse])), 1, 1), Date(Year(MAX('UMC_LCTT'[Parse])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "3d506faf-d4f4-4265-9f02-8d3e82ad8da5",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "4867ee40-e42f-41a9-bc61-aad46a81d737"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "5a74fa72-bbf0-4a11-bc2c-fcc82501b191"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "b80ac162-5bf9-40bb-a816-b15664737d8d"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "32b69f67-545a-4419-aba2-53f3022d1a67"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "A4_TSNH_Quy_ref",
        "lineageTag": "2a16a066-7a77-43fc-9701-e8f700e05b33",
        "columns": [
          {
            "name": "STT",
            "dataType": "int64",
            "sourceColumn": "STT",
            "formatString": "0",
            "lineageTag": "79f96999-1fd2-4575-a5dd-b76d5bcf6d2b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Item",
            "dataType": "string",
            "sourceColumn": "Item",
            "sortByColumn": "STT",
            "lineageTag": "676eeca5-d985-4622-af6e-30bdf96ce161",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Item_des",
            "dataType": "string",
            "sourceColumn": "Item_des",
            "lineageTag": "b4e3f714-b318-49fe-b698-6bd89c131574",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "A4_TSNH_Quy_ref",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"pVM9SwNBEP0rw1URguRyftZpPKyEYBNTmCXcHkk2R9wLWIqFbUQsLMScQQQhJBAbb8sN+R/7T5y9L2I+Fbtj5703b+bNVSqGaeSNsqvEDQNHiaELDSo/mQMNJSZAVRiwrQDItZR4I2AC77SxYu9CQujKPhAZEOS0VThgwGfjWYCQ6X3ywSPgjlHNV4ziYiciJ/NtLvxCwSJgAacSuX9DpyaL/zRpLa1joWV9rcH1yNSclZpDd9OeCt99bQa47ON4VA4ZBeaocMRimdjRHvYpzfv3sDhwUdr/gf4lLPVi23bipqbhDpSmvdNy3HIftU5kX69GiQemJZdfMqHztToHyDrzlfjCXWfTergSjhRc3S3bDtA6hxmsQesYIJ2NlXiJElj5rDlHWRH1QgJNJQbuyjeNPtbbo/61bglMiScPuhgtMIrXwzta+Dnq9wuQ1jMLWauaEo9w5evV6SgwhKG3uRgJmHPDyaCF96HE6FIT7hjdWIvo0c+G4tl5J0fKHPmKl6Cj3I6AnAVxyLwjPxgQnBlfm3hHLiZc/QY=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [STT = _t, Item = _t, Item_des = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"STT\", Int64.Type}, {\"Item\", type text}, {\"Item_des\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"Tiền gửi kỳ hạn > 3 tháng\",\"Tiền gửi có kỳ hạn > 3 tháng\",Replacer.ReplaceText,{\"Item\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Quỹ khám chữa bệnh\",\"Quỹ hỗ trợ khám chữa bệnh\",Replacer.ReplaceText,{\"Item\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Quỹ hỗ trợ khám chữa bệnh\",\"Quỹ hỗ trợ khám bệnh, chữa bệnh\",Replacer.ReplaceText,{\"Item\"})",
                "in",
                "    #\"Replaced Value2\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "A1_DoanhThu_NguonThu",
        "lineageTag": "da4cedae-5497-435a-85eb-7556f6575cfd",
        "columns": [
          {
            "name": "Ngay",
            "dataType": "dateTime",
            "sourceColumn": "Ngay",
            "formatString": "Short Date",
            "lineageTag": "0ffaffad-fbfd-428c-bf9b-cd41b68e0103",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "IDNoiDung",
            "dataType": "int64",
            "sourceColumn": "IDNoiDung",
            "formatString": "0",
            "lineageTag": "89f2d4c8-1200-4a11-9f0f-42decc38bc8a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "STT",
            "dataType": "int64",
            "sourceColumn": "STT",
            "formatString": "0",
            "lineageTag": "6976f6fe-f3b9-4089-aaeb-4146897e010b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "NoiDung",
            "dataType": "string",
            "sourceColumn": "NoiDung",
            "lineageTag": "29843244-071c-4886-a084-4f3595d5f0d8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "TienTong",
            "dataType": "double",
            "sourceColumn": "TienTong",
            "formatString": "#,0",
            "lineageTag": "3b513dd5-8d3e-4e46-8264-88f92bb127bd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Tuan",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "WEEKNUM(A1_DoanhThu_NguonThu[Ngay])",
            "formatString": "0",
            "lineageTag": "3cce60d3-ca52-4f72-8f66-eaf1b009d164",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Startdate of week",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "A1_DoanhThu_NguonThu[Ngay] + ((7- WEEKDAY(A1_DoanhThu_NguonThu[Ngay],2))-6)",
            "formatString": "General Date",
            "lineageTag": "f8ad24c1-1836-4cdb-b74e-cccb4aa8d310",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "a4eba96f-0148-49f0-b6a3-09b471412ae4",
                "defaultHierarchy": {
                  "table": "LocalDateTable_94d69a44-648a-4564-b2cc-c62d8874f422",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Nam",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "YEAR(A1_DoanhThu_NguonThu[Ngay])",
            "formatString": "0",
            "lineageTag": "d9552a9b-66d9-46d1-b9a2-1d9e2d858882",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "A1_DoanhThu_NguonThu",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"powerbi.umc.local\\umcdb01\", \"DB_BI\"),",
                "    dbo_BI_DoanhThu_NguonThu = Source{[Schema=\"dbo\",Item=\"BI_DoanhThu_NguonThu\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_BI_DoanhThu_NguonThu,{\"CDate\", \"CHost\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Ngay\", type date}}),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Changed Type\", \"Month\", each Date.Month([Ngay]), Int64.Type),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Inserted Month\",{\"Month\"})",
                "in",
                "    #\"Removed Columns1\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Revenue bill",
            "expression": "CALCULATE(sum(A1_DoanhThu_NguonThu[TienTong])/10^9)",
            "formatString": "#,0.00",
            "lineageTag": "6eff24b6-007d-4643-a56a-63ce56896a23"
          },
          {
            "name": "Dthu năm trước",
            "expression": "CALCULATE(A1_DoanhThu_NguonThu[Revenue bill], SAMEPERIODLASTYEAR(Dates_ref[Date]))",
            "lineageTag": "c59de900-af2f-484f-a655-bd2b43b754b2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Dthu tuần trước",
            "expression": "CALCULATE(A1_DoanhThu_NguonThu[Revenue bill], DATEADD(Dates_ref[Date],-7,DAY))",
            "formatString": "#,0.00",
            "lineageTag": "6e85f196-4671-4434-867e-d934bee0138a"
          },
          {
            "name": "Dthu tháng trước",
            "expression": "CALCULATE(A1_DoanhThu_NguonThu[Revenue bill], dateadd(Dates_ref[Date],-1,MONTH)) ",
            "lineageTag": "7bccba3a-bebc-4904-9730-887495220d7e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Doanh thu trước (theo ngày)",
            "expression": [
              "",
              "var pre_month_of_current2 = MINX(TOPN(2, SUMMARIZE(Dates_ref, Dates_ref[MonthnYear]),Dates_ref[MonthnYear],DESC),Dates_ref[MonthnYear])",
              "var current2 = CALCULATE(A1_DoanhThu_NguonThu[Revenue bill], Dates_ref[MonthnYear] = pre_month_of_current2)",
              "",
              "var revenue2_month = CALCULATE(A1_DoanhThu_NguonThu[Revenue bill], dateadd(Dates_ref[Date],-1,MONTH))",
              "",
              "var revenue2_week = CALCULATE(A1_DoanhThu_NguonThu[Revenue bill], dateadd(Dates_ref[Date],-7,DAY))",
              "return ",
              "SWITCH(TRUE(),",
              "        ISFILTERED(Dates_ref[WeekName]), revenue2_week, ISFILTERED(Dates_ref[VN_Month]), revenue2_month, current2)"
            ],
            "lineageTag": "56b9707f-8748-4930-b73b-00e61470270c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Dthu hiện tại",
            "expression": [
              "",
              "var current1 = CALCULATE(A1_DoanhThu_NguonThu[Revenue bill], Dates_ref[MonthnYear] = MAX(Dates_ref[MonthnYear]))",
              "var revenue1 = CALCULATE((A1_DoanhThu_NguonThu[Revenue bill]))",
              "return if(ISFILTERED(Dates_ref[VN_Month]), revenue1, current1)"
            ],
            "lineageTag": "333f1f1e-0f1e-4318-afad-1136f341d50f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "%vs_DT_LW",
            "expression": [
              "",
              "VAR LW = A1_DoanhThu_NguonThu[Doanh thu trước (theo ngày)]",
              "VAR kb= DIVIDE([Dthu hiện tại] - LW,LW,0)",
              "VAR Arrow =",
              "SWITCH (",
              "TRUE (),",
              "kb < 0, \"▼\" ,//UNICHAR ( 8659 ), ",
              "kb = 0, \"-\", // UNICHAR ( 8660 ),",
              "kb > 0, \"▲\" //UNICHAR ( 8657 ) ",
              ")",
              "return FORMAT ( kb, \"0.0%\" ) & \" \" & Arrow"
            ],
            "lineageTag": "6a1b6a0a-44a0-48e8-b23b-2a507e3911cb"
          },
          {
            "name": ".",
            "expression": "0",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a32c5f65-b137-4d97-9f64-bf84ba16ee2e",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ]
          },
          {
            "name": "Week-Month Switch",
            "expression": [
              "",
              " SWITCH(TRUE(),",
              "    ISFILTERED(Dates_ref[WeekName]), \" Tuần\",",
              "    \" Tháng\")",
              ""
            ],
            "lineageTag": "32170ed1-4133-4477-a8c7-b812914e5565"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Metrics_table",
        "lineageTag": "c4d9eaa9-59c3-4eb1-a6d3-655faa6a7e18",
        "columns": [
          {
            "name": "Column1",
            "dataType": "string",
            "sourceColumn": "Column1",
            "lineageTag": "bc95ceb3-aacd-49fc-ae23-25f8361406a9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Metrics_table",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_94d69a44-648a-4564-b2cc-c62d8874f422",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "35348528-62ed-4be6-9d98-e39991d57dfe",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "a36f9a0a-bbd7-4b6d-9415-eb881123ed64",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "d01e3cca-fb9b-4cc1-bf69-d22ae0546c37",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "ee526077-fe14-4897-9c9a-5d30f6321aa2",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "33020aa6-a61e-404e-bc7e-b9ac4c2d29e4",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "88dfced5-1a7a-4e11-ae59-38d98751017f",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "eb48dd27-a6d1-41a9-ae0a-bb0bee5cad2f",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "f5aac878-903c-4f0d-8787-0b982bafb553",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_94d69a44-648a-4564-b2cc-c62d8874f422",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('A1_DoanhThu_NguonThu'[Startdate of week])), 1, 1), Date(Year(MAX('A1_DoanhThu_NguonThu'[Startdate of week])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "7ac1624a-573d-487b-998b-611834546293",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "1f12dd1a-61c8-4209-851f-7d62da06faf3"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "37a9a172-c3fa-4bd7-84e3-197174d94568"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "09df72b1-9da8-4ee3-8f13-6afde816b1b7"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "9df02872-6386-41ac-8c69-b6ea2607bede"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "KQHĐtungKhoa_2022",
        "isHidden": true,
        "lineageTag": "d85393fa-8d2f-4184-b0c6-6e120c5c5eae",
        "columns": [
          {
            "name": "Column1",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Column1",
            "formatString": "Long Date",
            "lineageTag": "4c2c038b-290c-47f9-94a4-b2da198d0b01",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "a39ade90-bcca-46d3-8ca3-84fe9928e723",
                "defaultHierarchy": {
                  "table": "LocalDateTable_ce76c71e-661f-45ab-b020-2805869489c0",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Nội dung",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Nội dung",
            "lineageTag": "22feeb14-0000-4679-a781-32f08d1a316d",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Attribute",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Attribute",
            "lineageTag": "9b10fcc3-bb0d-474a-9bf9-da63a6d767f8",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Value",
            "lineageTag": "24b41515-14c1-4a2f-ac96-f02f9a6a4067",
            "summarizeBy": "sum",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "KQHĐtungKhoa_2022",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DATA\\DATA_FINANCE\\02. CO SO DU LIEU\\04. Ket qua hoat dong theo khoa - L8.xlsx\"), null, true),",
                "    #\"2022_Sheet\" = Source{[Item=\"2022\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"2022_Sheet\",{{\"Column1\", type any}, {\"Column2\", type any}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"Column7\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}, {\"Column14\", type any}, {\"Column15\", type any}, {\"Column16\", type any}, {\"Column17\", type any}, {\"Column18\", type any}, {\"Column19\", type any}, {\"Column20\", type any}, {\"Column21\", type any}, {\"Column22\", type any}, {\"Column23\", type any}, {\"Column24\", type any}, {\"Column25\", type any}, {\"Column26\", type any}, {\"Column27\", type any}, {\"Column28\", type any}, {\"Column29\", type any}, {\"Column30\", type any}, {\"Column31\", type any}, {\"Column32\", type any}, {\"Column33\", type any}, {\"Column34\", type any}, {\"Column35\", type any}, {\"Column36\", type any}, {\"Column37\", type any}, {\"Column38\", type any}, {\"Column39\", type any}, {\"Column40\", type any}, {\"Column41\", type any}, {\"Column42\", type any}, {\"Column43\", type any}, {\"Column44\", type any}, {\"Column45\", type any}, {\"Column46\", type any}, {\"Column47\", type any}, {\"Column48\", type any}, {\"Column49\", type any}, {\"Column50\", type any}, {\"Column51\", type any}, {\"Column52\", type any}, {\"Column53\", type any}, {\"Column54\", type any}, {\"Column55\", type any}, {\"Column56\", type any}, {\"Column57\", type any}, {\"Column58\", type any}, {\"Column59\", type any}, {\"Column60\", type any}, {\"Column61\", type any}, {\"Column62\", type any}, {\"Column63\", type any}, {\"Column64\", type any}, {\"Column65\", type any}, {\"Column66\", type any}, {\"Column67\", type any}, {\"Column68\", type any}, {\"Column69\", type any}, {\"Column70\", type any}, {\"Column71\", type any}, {\"Column72\", type any}, {\"Column73\", type any}, {\"Column74\", type any}, {\"Column75\", type any}, {\"Column76\", type any}, {\"Column77\", type any}, {\"Column78\", type any}, {\"Column79\", type any}, {\"Column80\", type any}, {\"Column81\", type any}, {\"Column82\", type any}, {\"Column83\", type any}, {\"Column84\", type any}, {\"Column85\", type any}, {\"Column86\", type any}, {\"Column87\", type any}, {\"Column88\", type any}, {\"Column89\", type any}, {\"Column90\", type any}, {\"Column91\", type any}, {\"Column92\", type any}, {\"Column93\", type any}, {\"Column94\", type any}, {\"Column95\", type any}, {\"Column96\", type any}, {\"Column97\", type any}, {\"Column98\", type any}, {\"Column99\", type any}, {\"Column100\", type any}, {\"Column101\", type any}, {\"Column102\", type any}, {\"Column103\", type any}, {\"Column104\", type any}, {\"Column105\", type any}, {\"Column106\", type any}, {\"Column107\", type any}, {\"Column108\", type any}, {\"Column109\", type any}, {\"Column110\", type any}, {\"Column111\", type any}, {\"Column112\", type any}, {\"Column113\", type any}, {\"Column114\", type any}, {\"Column115\", type any}, {\"Column116\", type any}, {\"Column117\", type any}, {\"Column118\", type any}, {\"Column119\", type any}, {\"Column120\", type any}, {\"Column121\", type any}, {\"Column122\", type any}, {\"Column123\", type any}, {\"Column124\", type any}, {\"Column125\", type any}, {\"Column126\", type any}, {\"Column127\", type any}, {\"Column128\", type any}, {\"Column129\", type any}, {\"Column130\", type any}, {\"Column131\", type any}, {\"Column132\", type any}, {\"Column133\", type any}, {\"Column134\", type any}}),",
                "    #\"Removed Bottom Rows\" = Table.RemoveLastN(#\"Changed Type\",1),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Bottom Rows\",{\"Column1\"}),",
                "    #\"Transposed Table\" = Table.Transpose(#\"Removed Columns\"),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Transposed Table\",{\"Column3\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Removed Columns1\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type date}, {\"Nội dung\", type text}, {\"Khoa Cấp cứu\", type number}, {\"Khoa Hồi sức tích cực\", type number}, {\"Khoa Gây mê hồi sức\", type number}, {\"Đơn vị GMHS PTT\", type number}, {\"Đơn vị Hồi sức Ngoại thần kinh\", type number}, {\"Khoa Ngoại Gan - Mật - Tụy\", type number}, {\"Khoa Ngoại Tiêu hóa\", type number}, {\"Khoa Chấn thương chỉnh hình\", type number}, {\"Khoa Ngoại thần kinh\", type number}, {\"Khoa Hậu môn - Trực tràng\", type number}, {\"Khoa Tai - Mũi - Họng\", type number}, {\"Khoa Lồng ngực mạch máu\", type number}, {\"Khoa Tiết niệu\", type number}, {\"Khoa Niệu học chức năng\", type number}, {\"Khoa Tạo hình Thẩm mỹ\", type number}, {\"Khoa Mắt\", type number}, {\"Khoa Phụ sản\", type number}, {\"Khoa PTTM người lớn\", type number}, {\"Khoa PT tim trẻ em\", type number}, {\"Đơn vị Điều trị COVID-19\", type number}, {\"Khoa Thần kinh\", type number}, {\"Khoa Tiêu hóa\", type number}, {\"Khoa Hô hấp\", type number}, {\"Khoa Nội tiết\", type number}, {\"Khoa Nội Tim mạch\", type number}, {\"Khoa Tim mạch can thiệp\", type number}, {\"Đơn vị Can thiệp nội mạch\", type number}, {\"Khoa Nội thận – TNT\", type number}, {\"Khoa Nội cơ xương khớp\", type number}, {\"Khoa Hóa trị Ung thư\", type number}, {\"Khoa Lão – CSGN\", type number}, {\"Khoa Sơ sinh\", type number}, {\"Khoa Xét nghiệm\", type number}, {\"Khoa Chẩn đoán hình ảnh\", type number}, {\"Khoa Nội soi\", type number}, {\"Khoa Vi sinh\", type number}, {\"Khoa TDCNHH\", type number}, {\"Đơn vị Hình ảnh tim mạch\", type number}, {\"Khoa Khám bệnh\", type number}, {\"Khoa da liễu-thẩm mỹ da\", type number}, {\"Khoa Phục hồi chức năng\", type number}, {\"Khoa PTHM - RHM\", type number}, {\"Khoa Y học hạt nhân\", type number}, {\"Khoa KSK theo yêu cầu\", type number}, {\"Đơn vị Dị ứng - MDLS\", type number}, {\"Nhà thuốc\", type number}, {\"Cơ sở 1-BV ĐHYD TP HCM\", type number}}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type1\", {\"Column1\", \"Nội dung\"}, \"Attribute\", \"Value\")",
                "in",
                "    #\"Unpivoted Other Columns\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_ce76c71e-661f-45ab-b020-2805869489c0",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "6f3afda8-85a2-4858-99c6-25d56ca37306",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "830965c9-1d22-4d9c-b3c0-4e2ebb9e1f17",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "4ac9be64-d761-4f03-904f-1a23c5892782",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "351767e9-ab39-4bb5-9e7d-15bbe46295a2",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "2cc76782-240d-442e-b094-a134947af864",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "cf2c0593-0ae1-4a77-8ba2-84576fe6f036",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "cf995b90-f93c-46fe-b5e5-99c298b6cac3",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "75211594-9848-4d5b-bc06-031ee670ca97",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_ce76c71e-661f-45ab-b020-2805869489c0",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('KQHĐtungKhoa_2022'[Column1])), 1, 1), Date(Year(MAX('KQHĐtungKhoa_2022'[Column1])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "2557f757-d83c-4103-93b1-fbd7d0b64044",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "96f25e81-0620-4000-b6df-d32e0831f7da"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "2aed7ae8-7562-4a13-8d9d-218e8958dee6"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "e4f8b847-71f5-4af6-9edf-5ee04df806cd"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "c0e056dd-816d-49c5-808f-3249e1d1d408"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "KQHĐtungKhoa_2023",
        "isHidden": true,
        "lineageTag": "0fedb840-3c6a-4afe-9b99-0cf8a278a997",
        "columns": [
          {
            "name": "Column1",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Column1",
            "formatString": "Long Date",
            "lineageTag": "6896e26d-70ff-4e8e-8861-abd6e556d700",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "cba7acaf-760c-4982-b4cc-2dd20c809329",
                "defaultHierarchy": {
                  "table": "LocalDateTable_6473077a-0631-4155-8948-31a141d346bb",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Nội dung",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Nội dung",
            "lineageTag": "62d5a6ef-ef00-4efc-ad91-349712912c3e",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Attribute",
            "dataType": "string",
            "sourceColumn": "Attribute",
            "lineageTag": "7532f4fc-b724-4ff3-bdaf-d097892d9889",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "double",
            "sourceColumn": "Value",
            "lineageTag": "d4be7871-d239-40c8-af99-7de5b392e728",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "KQHĐtungKhoa_2023",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DATA\\DATA_FINANCE\\02. CO SO DU LIEU\\04. Ket qua hoat dong theo khoa - L8.xlsx\"), null, true),",
                "    #\"2023_Sheet\" = Source{[Item=\"2023\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"2023_Sheet\",{{\"Column1\", type any}, {\"Column2\", type text}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"Column7\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}, {\"Column14\", type any}, {\"Column15\", type any}, {\"Column16\", type any}, {\"Column17\", type any}, {\"Column18\", type any}, {\"Column19\", type any}, {\"Column20\", type any}, {\"Column21\", type any}, {\"Column22\", type any}, {\"Column23\", type any}, {\"Column24\", type any}, {\"Column25\", type any}, {\"Column26\", type any}, {\"Column27\", type any}, {\"Column28\", type any}, {\"Column29\", type any}, {\"Column30\", type any}, {\"Column31\", type any}, {\"Column32\", type any}, {\"Column33\", type any}, {\"Column34\", type any}, {\"Column35\", type any}, {\"Column36\", type any}, {\"Column37\", type any}, {\"Column38\", type any}, {\"Column39\", type any}, {\"Column40\", type any}, {\"Column41\", type any}, {\"Column42\", type any}, {\"Column43\", type any}, {\"Column44\", type any}, {\"Column45\", type any}, {\"Column46\", type any}, {\"Column47\", type any}, {\"Column48\", type any}, {\"Column49\", type any}, {\"Column50\", type any}, {\"Column51\", type any}, {\"Column52\", type any}, {\"Column53\", type any}, {\"Column54\", type any}, {\"Column55\", type any}, {\"Column56\", type any}, {\"Column57\", type any}, {\"Column58\", type any}, {\"Column59\", type any}, {\"Column60\", type any}, {\"Column61\", type any}, {\"Column62\", type any}, {\"Column63\", type any}, {\"Column64\", type any}, {\"Column65\", type any}, {\"Column66\", type any}, {\"Column67\", type any}, {\"Column68\", type any}, {\"Column69\", type any}, {\"Column70\", type any}, {\"Column71\", type any}, {\"Column72\", type any}, {\"Column73\", type any}, {\"Column74\", type any}, {\"Column75\", type any}, {\"Column76\", type any}, {\"Column77\", type any}, {\"Column78\", type any}, {\"Column79\", type any}, {\"Column80\", type any}, {\"Column81\", type any}, {\"Column82\", type any}, {\"Column83\", type any}, {\"Column84\", type any}, {\"Column85\", type any}, {\"Column86\", type any}, {\"Column87\", type any}, {\"Column88\", type any}, {\"Column89\", type any}, {\"Column90\", type any}, {\"Column91\", type any}, {\"Column92\", type any}, {\"Column93\", type any}, {\"Column94\", type any}, {\"Column95\", type any}, {\"Column96\", type any}, {\"Column97\", type any}, {\"Column98\", type any}, {\"Column99\", type any}, {\"Column100\", type any}, {\"Column101\", type any}, {\"Column102\", type any}, {\"Column103\", type any}, {\"Column104\", type any}, {\"Column105\", type any}, {\"Column106\", type any}, {\"Column107\", type any}, {\"Column108\", type any}, {\"Column109\", type any}, {\"Column110\", type any}, {\"Column111\", type any}, {\"Column112\", type any}, {\"Column113\", type any}, {\"Column114\", type any}, {\"Column115\", type any}, {\"Column116\", type any}, {\"Column117\", type any}, {\"Column118\", type any}, {\"Column119\", type any}, {\"Column120\", type any}, {\"Column121\", type any}, {\"Column122\", type any}, {\"Column123\", type any}, {\"Column124\", type text}, {\"Column125\", type text}, {\"Column126\", type text}, {\"Column127\", type text}, {\"Column128\", type text}, {\"Column129\", type text}, {\"Column130\", type text}, {\"Column131\", type text}, {\"Column132\", type text}, {\"Column133\", type text}, {\"Column134\", type text}}),",
                "    #\"Removed Bottom Rows\" = Table.RemoveLastN(#\"Changed Type\",2),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Bottom Rows\",{\"Column1\"}),",
                "    #\"Transposed Table\" = Table.Transpose(#\"Removed Columns\"),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Transposed Table\",{\"Column3\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Removed Columns1\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Nội dung\", type text}, {\"Khoa Hồi sức tích cực\", type number}, {\"Khoa Gây mê hồi sức\", type number}, {\"Đơn vị GMHS PTT\", type number}, {\"Đơn vị Hồi sức Ngoại thần kinh\", type number}, {\"Khoa Ngoại Gan - Mật - Tụy\", type number}, {\"Khoa Ngoại Tiêu hóa\", type number}, {\"Khoa Chấn thương chỉnh hình\", type number}, {\"Khoa Ngoại thần kinh\", type number}, {\"Khoa Hậu môn - Trực tràng\", type number}, {\"Khoa Tai - Mũi - Họng\", type number}, {\"Khoa Lồng ngực mạch máu\", type number}, {\"Khoa Tiết niệu\", type number}, {\"Khoa Niệu học chức năng\", type number}, {\"Khoa Tạo hình Thẩm mỹ\", type number}, {\"Khoa Mắt\", type number}, {\"Khoa Phụ sản\", type number}, {\"Khoa PTTM người lớn\", type number}, {\"Khoa PT tim trẻ em\", type number}, {\"Đơn vị Điều trị COVID-19\", type number}, {\"Khoa Thần kinh\", type number}, {\"Khoa Tiêu hóa\", type number}, {\"Khoa Hô hấp\", type number}, {\"Khoa Nội tiết\", type number}, {\"Khoa Nội Tim mạch\", type number}, {\"Khoa Tim mạch can thiệp\", type number}, {\"Đơn vị Can thiệp nội mạch\", type number}, {\"Khoa Nội thận – TNT\", type number}, {\"Khoa Nội cơ xương khớp\", type number}, {\"Khoa Hóa trị Ung thư\", type number}, {\"Khoa Lão – CSGN\", type number}, {\"Khoa Sơ sinh\", type number}, {\"Khoa Giải phẫu bệnh\", type number}, {\"Khoa Xét nghiệm\", type number}, {\"Khoa Chẩn đoán hình ảnh\", type number}, {\"Khoa Nội soi\", type number}, {\"Khoa Vi sinh\", type number}, {\"Khoa TDCNHH\", type number}, {\"Đơn vị Hình ảnh tim mạch\", type number}, {\"Khoa Khám bệnh\", type number}, {\"Khoa da liễu-thẩm mỹ da\", type number}, {\"Khoa Phục hồi chức năng\", type number}, {\"Khoa PTHM - RHM\", type number}, {\"Khoa Y học hạt nhân\", type number}, {\"Khoa KSK theo yêu cầu\", type number}, {\"Đơn vị Dị ứng - MDLS\", type number}, {\"Nhà thuốc\", type number}, {\"Cơ sở 1-BV ĐHYD TP HCM\", type number}, {\"Khoa Cấp cứu\", type number}}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type1\", {\"Column1\", \"Nội dung\"}, \"Attribute\", \"Value\"),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Unpivoted Other Columns\",{{\"Column1\", type date}})",
                "in",
                "    #\"Changed Type2\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "KQHĐtungKhoa_2021",
        "isHidden": true,
        "lineageTag": "ade1ba3e-886f-47fd-b173-8ec85c7b9de0",
        "columns": [
          {
            "name": "Column1",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Column1",
            "formatString": "Long Date",
            "lineageTag": "2eef017b-edac-40ab-bbf3-e0bee7f9d9eb",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "b85e5482-9ded-410e-82d8-b3d14a4df263",
                "defaultHierarchy": {
                  "table": "LocalDateTable_b378d500-dbba-4e51-953b-e51641bb1d69",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Nội dung",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Nội dung",
            "lineageTag": "bdaf3c87-77db-4c72-8aad-58601b327933",
            "summarizeBy": "none",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Attribute",
            "dataType": "string",
            "sourceColumn": "Attribute",
            "lineageTag": "a009a6ad-6f7b-47ba-b683-d4e09d2cd45e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "double",
            "sourceColumn": "Value",
            "lineageTag": "7673cf59-5d0b-4999-a988-e53ebb2bc653",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "KQHĐtungKhoa_2021",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DATA\\DATA_FINANCE\\02. CO SO DU LIEU\\04. Ket qua hoat dong theo khoa - L8.xlsx\"), null, true),",
                "    #\"2021_Sheet\" = Source{[Item=\"2021\",Kind=\"Sheet\"]}[Data],",
                "    #\"Removed Bottom Rows\" = Table.RemoveLastN(#\"2021_Sheet\",1),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Removed Bottom Rows\",{\"Column1\"}),",
                "    #\"Transposed Table\" = Table.Transpose(#\"Removed Columns\"),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Transposed Table\",{\"Column3\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Removed Columns1\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Column1\", type date}, {\"Nội dung\", type text}, {\"Khoa Cấp cứu\", type number}, {\"Khoa Hồi sức tích cực\", type number}, {\"Khoa Gây mê hồi sức\", type number}, {\"Đơn vị GMHS PTT\", type number}, {\"Đơn vị Hồi sức Ngoại thần kinh\", type number}, {\"Khoa Ngoại Gan - Mật - Tụy\", type number}, {\"Khoa Ngoại Tiêu hóa\", type number}, {\"Khoa Chấn thương chỉnh hình\", type number}, {\"Khoa Ngoại thần kinh\", type number}, {\"Khoa Hậu môn - Trực tràng\", type number}, {\"Khoa Tai - Mũi - Họng\", type number}, {\"Khoa Lồng ngực mạch máu\", type number}, {\"Khoa Tiết niệu\", type number}, {\"Khoa Niệu học chức năng\", type number}, {\"Khoa Tạo hình Thẩm mỹ\", type number}, {\"Khoa Mắt\", type number}, {\"Khoa Phụ sản\", type number}, {\"Khoa PTTM người lớn\", type number}, {\"Khoa PT tim trẻ em\", type number}, {\"Khoa Thần kinh\", type number}, {\"Khoa Tiêu hóa\", type number}, {\"Khoa Hô hấp\", type number}, {\"Khoa Nội tiết\", type number}, {\"Khoa Nội Tim mạch\", type number}, {\"Khoa Tim mạch can thiệp\", type number}, {\"Đơn vị Can thiệp nội mạch\", type number}, {\"Khoa Nội thận – TNT\", type number}, {\"Khoa Nội cơ xương khớp\", type number}, {\"Khoa Hóa trị Ung thư\", type number}, {\"Khoa Lão – CSGN\", type number}, {\"Khoa Sơ sinh\", type number}, {\"Khoa Xét nghiệm\", type number}, {\"Khoa Chẩn đoán hình ảnh\", type number}, {\"Khoa Nội soi\", type number}, {\"Khoa Vi sinh\", type number}, {\"Khoa TDCNHH\", type number}, {\"Đơn vị Hình ảnh tim mạch\", type number}, {\"Khoa Khám bệnh\", type number}, {\"Khoa da liễu-thẩm mỹ da\", type number}, {\"Khoa Phục hồi chức năng\", type number}, {\"Khoa PTHM - RHM\", type number}, {\"Khoa Y học hạt nhân\", type number}, {\"Khoa KSK theo yêu cầu\", type number}, {\"Đơn vị Dị ứng - MDLS\", type number}, {\"Nhà thuốc\", type number}, {\"Cơ sở 1-BV ĐHYD TP HCM\", type number}}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Changed Type\", {\"Column1\", \"Nội dung\"}, \"Attribute\", \"Value\")",
                "in",
                "    #\"Unpivoted Other Columns\""
              ]
            }
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_b378d500-dbba-4e51-953b-e51641bb1d69",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "40af6d2d-3376-4c7a-8c58-92afc030a1bd",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "1206418c-f663-4b4c-9a0c-d1a24de633ae",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "e759e6c9-a880-4c56-af82-442ab41c3229",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "88d36ec1-934b-4eae-ab45-275287601903",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "9760f962-1ede-43a0-ac40-761ec01ca8ca",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "5c333f8d-a208-4d0b-a869-5848df1e0f7b",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "4370beac-3304-4754-8ca7-20c54b5b5405",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "5b9fea4e-e919-4bb7-910c-e4703dd77ec3",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_b378d500-dbba-4e51-953b-e51641bb1d69",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('KQHĐtungKhoa_2021'[Column1])), 1, 1), Date(Year(MAX('KQHĐtungKhoa_2021'[Column1])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "2722b2c7-d33e-4217-8d0c-01a679e3b0b4",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "42acca54-5c2b-4867-af92-566af054b768"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "e64ec86a-3010-417f-ba82-85591429b51a"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "dd6a5aec-b5ff-4bfb-9005-d14009327d91"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "6809cd5f-1693-487e-8341-8be264bb92e3"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "TOTAL_KQHĐtungKhoa",
        "lineageTag": "1de81ec8-a990-487e-afce-2089e5e65957",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Short Date",
            "lineageTag": "b41a7faf-422f-4986-8e16-9bdb030a07a1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Nội dung",
            "dataType": "string",
            "sourceColumn": "Nội dung",
            "lineageTag": "42826c32-d399-4652-a202-712382bf0666",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"TOTAL_KQHĐtungKhoa\",\"TableItemName\":\"Nội dung (groups)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ]
          },
          {
            "name": "Khoa",
            "dataType": "string",
            "sourceColumn": "Khoa",
            "lineageTag": "7428344a-aaa9-47de-a83c-a18843a5fb10",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "double",
            "sourceColumn": "Value",
            "lineageTag": "b2cd8588-10d7-4b18-b181-05d6921b9a06",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Value_bill",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "'TOTAL_KQHĐtungKhoa'[Value]/ 10^9",
            "formatString": "#,0.00",
            "lineageTag": "a3bffbce-a5e1-4ea3-818e-460134609540",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Nội dung (groups)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('TOTAL_KQHĐtungKhoa'[Nội dung]),",
              "\t\"(Blank)\",",
              "\t'TOTAL_KQHĐtungKhoa'[Nội dung] IN {\"Biến phí\"},",
              "\t\"Biến phí\",",
              "\t'TOTAL_KQHĐtungKhoa'[Nội dung] IN {\"Tổng chi phí\"},",
              "\t\"Chi phí\",",
              "\t'TOTAL_KQHĐtungKhoa'[Nội dung] IN {\"Định phí\"},",
              "\t\"Định phí\",",
              "\t'TOTAL_KQHĐtungKhoa'[Nội dung] IN {\"Tổng nguồn thu xác định chênh lệch thu chi\"},",
              "\t\"Doanh thu\",",
              "\t'TOTAL_KQHĐtungKhoa'[Nội dung] IN {\"Chênh lệch thu chi sau thuế\"},",
              "\t\"Lợi nhuận sau thuế\",",
              "\t'TOTAL_KQHĐtungKhoa'[Nội dung]",
              ")"
            ],
            "lineageTag": "bf6c3ab3-7b17-4aa2-8f5b-6c06e31280f7",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "GroupingMetadata",
                "value": {
                  "version": 0,
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "TOTAL_KQHĐtungKhoa"
                          }
                        },
                        "Property": "Nội dung"
                      }
                    }
                  ]
                }
              }
            ],
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"t\",\"Entity\":\"TOTAL_KQHĐtungKhoa\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Nội dung\"}}],\"GroupItems\":[{\"DisplayName\":\"(Blank)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"Biến phí\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Nội dung\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Biến phí'\"}}]]}}},{\"DisplayName\":\"Chi phí\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Nội dung\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Tổng chi phí'\"}}]]}}},{\"DisplayName\":\"Định phí\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Nội dung\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Định phí'\"}}]]}}},{\"DisplayName\":\"Doanh thu\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Nội dung\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Tổng nguồn thu xác định chênh lệch thu chi'\"}}]]}}},{\"DisplayName\":\"Lợi nhuận sau thuế\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"Nội dung\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Chênh lệch thu chi sau thuế'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "Month Name",
            "lineageTag": "ab6e7b5d-fd43-4bb1-a9e8-bbc772bfffa2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month",
            "formatString": "0",
            "lineageTag": "3993b338-b260-4192-b566-fa3e00110c28",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "formatString": "0",
            "lineageTag": "c9aa62c1-d031-42d4-bfd2-01f67c7d1e3b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "YearnMonth",
            "dataType": "string",
            "sourceColumn": "YearnMonth",
            "lineageTag": "fed7bde6-0e59-4481-a209-ba85d33192f7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Quarter",
            "dataType": "int64",
            "sourceColumn": "Quarter",
            "formatString": "0",
            "lineageTag": "93283012-8b8d-41e4-aa08-ec43bcc1de23",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "QuarterInYear",
            "dataType": "string",
            "sourceColumn": "QuarterInYear",
            "lineageTag": "ea91b183-ccb0-4b15-8bfa-746635bb3e91",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MonthShort",
            "dataType": "string",
            "sourceColumn": "MonthShort",
            "lineageTag": "06b8c39e-0b1c-4288-9cc9-c703f003039a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "TOTAL_KQHĐtungKhoa",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.Combine({KQHĐtungKhoa_2021, KQHĐtungKhoa_2022, KQHĐtungKhoa_2023}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"Column1\", \"Date\"}, {\"Attribute\", \"Khoa\"}}),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Renamed Columns\", \"Month Name\", each Date.MonthName([Date]), type text),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Month Name\", \"Month\", each Date.Month([Date]), Int64.Type),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Inserted Month\", \"Year\", each Date.Year([Date]), Int64.Type),",
                "    #\"Inserted Multiplication\" = Table.AddColumn(#\"Inserted Year\", \"Multiplication\", each [Month] * 20210100, type number),",
                "    #\"Renamed Columns1\" = Table.AddColumn(#\"Inserted Year\", \"YearnMonth\", each Text.Combine({Text.From([Year], \"en-US\"), Text.PadStart(Text.From([Month], \"en-US\"), 2, \"0\"), \"00\"}), type text),",
                "    #\"Inserted Quarter\" = Table.AddColumn(#\"Renamed Columns1\", \"Quarter\", each Date.QuarterOfYear([Date]), Int64.Type),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Inserted Quarter\", \"QuarterInYear\", each Table.AddColumn(#\"Inserted Quarter\", \"QuarterInYear\", each Text.Combine({Text.From([Year], \"en-US\"), \"0\", Text.From([Quarter], \"en-US\"), \"00\"}), type text)),",
                "    QuarterInYear = #\"Added Custom\"{48}[QuarterInYear],",
                "    #\"Duplicated Column\" = Table.AddColumn(QuarterInYear, \"MonthShort\", each Text.Start([Month Name], 3), type text)",
                "in",
                "    #\"Duplicated Column\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "A1_KQKD (month)",
        "lineageTag": "83dbfcb5-0853-42c2-8352-f4d455cba81d",
        "columns": [
          {
            "name": "Cơ sở",
            "dataType": "int64",
            "sourceColumn": "Cơ sở",
            "formatString": "0",
            "lineageTag": "fbaa6fc4-6119-4b6c-9897-3ce905451feb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Chỉ tiêu",
            "dataType": "string",
            "sourceColumn": "Chỉ tiêu",
            "lineageTag": "c106fa9b-8073-4c0b-97a6-34fb2707f9d9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "dateTime",
            "sourceColumn": "Month",
            "formatString": "Long Date",
            "lineageTag": "45d7eede-3cc4-455e-b00d-854e063baf62",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "double",
            "sourceColumn": "Value",
            "lineageTag": "45029997-ba5d-4b58-8b10-7f5b75f2c905",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "id",
            "dataType": "double",
            "sourceColumn": "id",
            "lineageTag": "da55e8db-2592-4adb-9d46-74ff003e7784",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "A1_KQKD (month)",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DATA\\DATA_FINANCE\\02. CO SO DU LIEU\\01. Ke hoach hoat dong - L2.xlsx\"), null, true),",
                "    A2_KQHD_Sheet = Source{[Item=\"A2_KQHD\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(A2_KQHD_Sheet,{{\"Column1\", type any}, {\"Column2\", type text}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"Column7\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}, {\"Column14\", type any}, {\"Column15\", type any}, {\"Column16\", type any}, {\"Column17\", type any}, {\"Column18\", type any}, {\"Column19\", type any}, {\"Column20\", type any}, {\"Column21\", type any}, {\"Column22\", type any}, {\"Column23\", type any}, {\"Column24\", type any}, {\"Column25\", type any}, {\"Column26\", type any}, {\"Column27\", type any}, {\"Column28\", type any}, {\"Column29\", type any}, {\"Column30\", type any}, {\"Column31\", type any}, {\"Column32\", type any}, {\"Column33\", type any}, {\"Column34\", type any}, {\"Column35\", type any}, {\"Column36\", type any}, {\"Column37\", type any}, {\"Column38\", type any}, {\"Column39\", type any}, {\"Column40\", type any}, {\"Column41\", type any}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Cơ sở\", Int64.Type}, {\"Nội dung\", type text}, {\"Kế hoạch 2021\", type number}, {\"Thực tế 2021#(lf)(lũy kế)\", type number}, {\"01/2021\", type number}, {\"02/2021\", type number}, {\"03/2021\", type number}, {\"04/2021\", type number}, {\"05/2021\", type number}, {\"06/2021\", type number}, {\"07/2021\", type number}, {\"08/2021\", type number}, {\"09/2021\", type number}, {\"10/2021\", type number}, {\"11/2021\", type number}, {\"12/2021\", type number}, {\"01/2022\", type number}, {\"02/2022\", type number}, {\"03/2022\", type number}, {\"04/2022\", type number}, {\"05/2022\", type number}, {\"06/2022\", type number}, {\"07/2022\", type number}, {\"08/2022\", type number}, {\"09/2022\", type number}, {\"10/2022\", type number}, {\"11/2022\", type number}, {\"12/2022\", type number}, {\"01/2023\", type number}, {\"02/2023\", type number}, {\"03/2023\", type number}, {\"04/2023\", type number}, {\"05/2023\", type number}, {\"06/2023\", type number}, {\"07/2023\", type number}, {\"08/2023\", type number}, {\"09/2023\", type number}, {\"10/2023\", type number}, {\"11/2023\", type number}, {\"12/2023\", type number}, {\"01/2024\", type number}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type1\", each ([Cơ sở] = 1)),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Kế hoạch 2021\", \"Thực tế 2021#(lf)(lũy kế)\"}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Removed Columns\", {\"Nội dung\", \"Cơ sở\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"Month\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Month\", type date}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type2\",{{\"Nội dung\", \"Chỉ tiêu\"}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Renamed Columns1\", \"Custom\", each if [Chỉ tiêu] = \"Doanh thu thuần\" then 3 else if [Chỉ tiêu] = \"Giá vốn kế hoạch\" then 4 else if [Chỉ tiêu] = \"Lợi nhuận sau thuế\" then 17 else 0, type number),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Added Conditional Column\",{{\"Custom\", \"id\"}})",
                "in",
                "    #\"Renamed Columns2\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "A2_Union_Actual",
        "lineageTag": "adc0e97b-1ccb-41a6-8105-62162313a605",
        "columns": [
          {
            "name": "Cơ sở",
            "dataType": "int64",
            "sourceColumn": "Cơ sở",
            "formatString": "0",
            "lineageTag": "d8dbfeec-f26f-4b8d-8414-8b88dc8eff9d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Nội dung",
            "dataType": "string",
            "sourceColumn": "Nội dung",
            "lineageTag": "a5b7672e-2103-49d0-b8b4-6b81d84c27b0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "formatString": "Long Date",
            "lineageTag": "9da1594e-d3b1-4441-aa87-64c3d054ab6e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Value",
            "dataType": "double",
            "sourceColumn": "Value",
            "lineageTag": "292755c9-c17d-4c28-a8bf-a7757038eedc",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "YEAR(A2_Union_Actual[Date])",
            "formatString": "0",
            "lineageTag": "3744ff29-90a1-4603-ba30-bd8f6f0facb2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "A2_Union_Actual",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"E:\\DATA\\DATA_FINANCE\\02. CO SO DU LIEU\\01. Ke hoach hoat dong - L2.xlsx\"), null, true),",
                "    A2_KQHD_Sheet = Source{[Item=\"A2_KQHD\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(A2_KQHD_Sheet,{{\"Column1\", type any}, {\"Column2\", type text}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"Column7\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}, {\"Column14\", type any}, {\"Column15\", type any}, {\"Column16\", type any}, {\"Column17\", type any}, {\"Column18\", type any}, {\"Column19\", type any}, {\"Column20\", type any}, {\"Column21\", type any}, {\"Column22\", type any}, {\"Column23\", type any}, {\"Column24\", type any}, {\"Column25\", type any}, {\"Column26\", type any}, {\"Column27\", type any}, {\"Column28\", type any}, {\"Column29\", type any}, {\"Column30\", type any}, {\"Column31\", type any}, {\"Column32\", type any}, {\"Column33\", type any}, {\"Column34\", type any}, {\"Column35\", type any}, {\"Column36\", type any}, {\"Column37\", type any}, {\"Column38\", type any}, {\"Column39\", type any}, {\"Column40\", type any}, {\"Column41\", type any}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Cơ sở\", Int64.Type}, {\"Nội dung\", type text}, {\"Kế hoạch 2021\", type number}, {\"Thực tế 2021#(lf)(lũy kế)\", type number}, {\"01/2021\", type number}, {\"02/2021\", type number}, {\"03/2021\", type number}, {\"04/2021\", type number}, {\"05/2021\", type number}, {\"06/2021\", type number}, {\"07/2021\", type number}, {\"08/2021\", type number}, {\"09/2021\", type number}, {\"10/2021\", type number}, {\"11/2021\", type number}, {\"12/2021\", type number}, {\"01/2022\", type number}, {\"02/2022\", type number}, {\"03/2022\", type number}, {\"04/2022\", type number}, {\"05/2022\", type number}, {\"06/2022\", type number}, {\"07/2022\", type number}, {\"08/2022\", type number}, {\"09/2022\", type number}, {\"10/2022\", type number}, {\"11/2022\", type number}, {\"12/2022\", type number}, {\"01/2023\", type number}, {\"02/2023\", type number}, {\"03/2023\", type number}, {\"04/2023\", type number}, {\"05/2023\", type number}, {\"06/2023\", type number}, {\"07/2023\", type number}, {\"08/2023\", type number}, {\"09/2023\", type number}, {\"10/2023\", type number}, {\"11/2023\", type number}, {\"12/2023\", type number}, {\"01/2024\", type number}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"Kế hoạch 2021\", \"Thực tế 2021#(lf)(lũy kế)\"}),",
                "    #\"Unpivoted Other Columns\" = Table.UnpivotOtherColumns(#\"Removed Columns\", {\"Cơ sở\", \"Nội dung\"}, \"Attribute\", \"Value\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Unpivoted Other Columns\",{{\"Attribute\", \"Date\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Date\", type date}})",
                "in",
                "    #\"Changed Type2\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "A2_Thực hiện_union",
            "expression": [
              "",
              "var _total = (SUM(A2_Union_Actual[Value])) /10^9",
              "return  _total",
              "    //if(ISFILTERED(Dates_ref[VN_Month]), _total /12, _total) "
            ],
            "formatString": "#,0",
            "lineageTag": "54df7578-7b35-441b-a58d-e28457d3c558",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "A2_Thuchien_Cum",
            "expression": [
              "",
              "    CALCULATE(A2_Union_Actual[A2_Thực hiện_union],",
              "        FILTER(ALLSELECTED(Dates_ref), ",
              "         Dates_ref[Date] <= MAX(Dates_ref[Date])))",
              "         "
            ],
            "formatString": "#,0",
            "lineageTag": "8dbdee53-7f11-4897-99f8-6fb65178887f",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "A2_Plan vs Actual %",
            "expression": "DIVIDE([A2_Thuchien_Cum], A2_KQHD_plan[A2_Kế hoạch])",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "36394819-9713-44cf-969e-54d26b58e4f2"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "LocalDateTable_6473077a-0631-4155-8948-31a141d346bb",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "2f59e3d0-e801-42a2-97f0-a04c7e37b8e9",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "f3b50357-e1c6-4796-a821-5fe275df969f",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "9c8b6bb0-6661-4919-ada1-e7c057bf1ca4",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "a33942fc-658b-48e8-af92-a3cd129b05d0",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "273484a1-452d-4bb8-a63a-571cb19624b6",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "5a74ac60-b874-49af-a8ad-e9cb10321bbc",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "40af54fb-b46b-4ee3-938b-482b54e8a5ce",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "85a61284-1f83-4192-8927-3a48fb9ff7cd",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_6473077a-0631-4155-8948-31a141d346bb",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('KQHĐtungKhoa_2023'[Column1])), 1, 1), Date(Year(MAX('KQHĐtungKhoa_2023'[Column1])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "879a0db6-3184-4da7-a60c-b3a5d50a3f70",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "92ef0c54-cade-44ef-a8af-398f9884e7d6"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "160d72e6-745e-4f2a-9c9e-6a1c922acb79"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "2153b4d3-69b1-4fb8-ba60-6cb5b734401e"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "41cd291c-2c75-4182-9078-a527ef6cf90f"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ]
      },
      {
        "name": "A8_Metrics",
        "lineageTag": "b844d53b-1906-448f-b704-ed4f7f50cbb4",
        "partitions": [
          {
            "name": "A8_Metrics",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "1.Doanh thu",
            "expression": "CALCULATE(SUM('TOTAL_KQHĐtungKhoa'[Value_bill]), 'TOTAL_KQHĐtungKhoa'[Nội dung (groups)] = \"Doanh thu\")",
            "formatString": "#,0.00",
            "lineageTag": "6383136f-80ea-4398-b8c6-8a99666d46a8"
          },
          {
            "name": "2.Chi phí",
            "expression": "CALCULATE(SUM('TOTAL_KQHĐtungKhoa'[Value_bill]), 'TOTAL_KQHĐtungKhoa'[Nội dung (groups)] = \"Chi phí\")",
            "formatString": "#,0.00",
            "lineageTag": "5295d479-5140-42cd-8da7-7499b0aabcc7"
          },
          {
            "name": "3. Lợi nhuận sau thuế",
            "expression": "CALCULATE(SUM('TOTAL_KQHĐtungKhoa'[Value_bill]), 'TOTAL_KQHĐtungKhoa'[Nội dung (groups)] = \"Lợi nhuận sau thuế\")",
            "formatString": "#,0.00",
            "lineageTag": "62444ae9-9f2f-44c8-a20f-04d80d1724dc"
          },
          {
            "name": "4. Biến phí",
            "expression": "CALCULATE(SUM('TOTAL_KQHĐtungKhoa'[Value_bill]), 'TOTAL_KQHĐtungKhoa'[Nội dung (groups)] = \"Biến phí\")",
            "formatString": "#,0.00",
            "lineageTag": "e3ac19d2-f1cc-4721-a1a6-d059d8dfdbda"
          },
          {
            "name": "5. Định phí",
            "expression": "CALCULATE(SUM('TOTAL_KQHĐtungKhoa'[Value_bill]), 'TOTAL_KQHĐtungKhoa'[Nội dung (groups)] = \"Định phí\")",
            "formatString": "0.00",
            "lineageTag": "275402b3-ca76-4a9e-8acd-464915d08a72"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "b3d86edb-4ec0-4b58-9f80-e7f36cc26da4",
        "fromTable": "Select last 4 Quarter",
        "fromColumn": "Start of Quarter",
        "toTable": "LocalDateTable_3e4af95f-1a5a-4b07-911a-35a3156bf2dc",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "d765c051-4655-457c-97dd-3eab0e59ce9f",
        "fromTable": "Select last 4 Quarter",
        "fromColumn": "End of Quarter",
        "toTable": "LocalDateTable_035e6a83-2b8c-4063-b5b0-b7efd8da0d25",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "9b4061c3-c24d-4662-937e-7bd58c8f1b81",
        "toCardinality": "many",
        "fromTable": "UMC_Điểm Hòa Vốn",
        "fromColumn": "YearnMonth",
        "toTable": "Dates_ref",
        "toColumn": "MonthnYear"
      },
      {
        "name": "8c04a982-552e-4649-94c3-f7db6551108b",
        "fromTable": "UMC_KQKD",
        "fromColumn": "Parse",
        "toTable": "LocalDateTable_8ad98c6c-2592-49d3-be92-64d686a661b3",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "83295c94-57b0-45a9-ad92-d987a622dbc0",
        "fromTable": "UMC_CDKT",
        "fromColumn": "Parse",
        "toTable": "LocalDateTable_81224034-15ea-4f3b-959e-fc1d6244be47",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "99ceded1-c131-f6ce-88d7-31e469878f75",
        "toCardinality": "many",
        "fromTable": "UMC_Total",
        "fromColumn": "Parse",
        "toTable": "Dates_ref",
        "toColumn": "Date"
      },
      {
        "name": "8d835b1e-2e50-463b-a2e6-f0a41a198620",
        "fromTable": "A2_KQHD_actual",
        "fromColumn": "Date",
        "toTable": "Dates_ref",
        "toColumn": "Date"
      },
      {
        "name": "a24e0f9b-49c4-4a59-a0c3-c102711e526b",
        "toCardinality": "many",
        "fromTable": "A2_KQHD_plan",
        "fromColumn": "Năm",
        "toTable": "Dates_ref",
        "toColumn": "Year"
      },
      {
        "name": "c9a2d321-ec98-4e49-9573-e5db2183232b",
        "fromTable": "A2_KQHD_actual",
        "fromColumn": "Cơ sở",
        "toTable": "A2_KQHD_Coso_ref",
        "toColumn": "Cơ sở"
      },
      {
        "name": "5393b304-cdde-4e0d-89bf-e252fe686705",
        "fromTable": "A2_KQHD_plan",
        "fromColumn": "Cơ sở",
        "toTable": "A2_KQHD_Coso_ref",
        "toColumn": "Cơ sở"
      },
      {
        "name": "ede686cd-b538-46a2-b61d-312720a96ef1",
        "fromTable": "A2_KQHD_plan",
        "fromColumn": "Nội dung",
        "toTable": "A2_KQHD_Noidung_ref",
        "toColumn": "Nội dung"
      },
      {
        "name": "dca8f06a-c07a-49d9-bfbd-1819c97d1ca9",
        "fromTable": "A2_KQHD_actual",
        "fromColumn": "Nội dung",
        "toTable": "A2_KQHD_Noidung_ref",
        "toColumn": "Nội dung"
      },
      {
        "name": "abc79ba5-000c-4261-adf4-136c3e3ef364",
        "fromTable": "UMC_LCTT",
        "fromColumn": "Parse",
        "toTable": "LocalDateTable_bd4459e3-a3b9-4b5e-9661-ef18bc474853",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "c42d461b-996e-400b-8baf-3b129a5032c2",
        "fromTable": "UMC_Total",
        "fromColumn": "Chỉ tiêu (groups)",
        "toTable": "A4_TSNH_Quy_ref",
        "toColumn": "Item"
      },
      {
        "name": "33201952-52a3-4555-9749-bf8e51b3042d",
        "fromTable": "A1_DoanhThu_NguonThu",
        "fromColumn": "Ngay",
        "toTable": "Dates_ref",
        "toColumn": "Date"
      },
      {
        "name": "a4eba96f-0148-49f0-b6a3-09b471412ae4",
        "fromTable": "A1_DoanhThu_NguonThu",
        "fromColumn": "Startdate of week",
        "toTable": "LocalDateTable_94d69a44-648a-4564-b2cc-c62d8874f422",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "a39ade90-bcca-46d3-8ca3-84fe9928e723",
        "fromTable": "KQHĐtungKhoa_2022",
        "fromColumn": "Column1",
        "toTable": "LocalDateTable_ce76c71e-661f-45ab-b020-2805869489c0",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "b85e5482-9ded-410e-82d8-b3d14a4df263",
        "fromTable": "KQHĐtungKhoa_2021",
        "fromColumn": "Column1",
        "toTable": "LocalDateTable_b378d500-dbba-4e51-953b-e51641bb1d69",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "64ddd181-78d6-42e2-9353-0717c20efb8e",
        "fromTable": "TOTAL_KQHĐtungKhoa",
        "fromColumn": "Date",
        "toTable": "Dates_ref",
        "toColumn": "Date"
      },
      {
        "name": "72b25757-49bb-420e-bce2-4903068a1485",
        "fromTable": "A1_KQKD (month)",
        "fromColumn": "Month",
        "toTable": "Dates_ref",
        "toColumn": "Date"
      },
      {
        "name": "303be73c-92fb-4d84-9690-6eb3a9036984",
        "fromTable": "A2_Union_Actual",
        "fromColumn": "Date",
        "toTable": "Dates_ref",
        "toColumn": "Date"
      },
      {
        "name": "fb7e2ec6-b9b5-470b-884f-b8c471d2ab83",
        "fromTable": "A2_Union_Actual",
        "fromColumn": "Nội dung",
        "toTable": "A2_KQHD_Noidung_ref",
        "toColumn": "Nội dung"
      },
      {
        "name": "07ef482b-070d-4ac1-b87a-6613bc56300a",
        "fromTable": "A2_Union_Actual",
        "fromColumn": "Cơ sở",
        "toTable": "A2_KQHD_Coso_ref",
        "toColumn": "Cơ sở"
      },
      {
        "name": "cba7acaf-760c-4982-b4cc-2dd20c809329",
        "fromTable": "KQHĐtungKhoa_2023",
        "fromColumn": "Column1",
        "toTable": "LocalDateTable_6473077a-0631-4155-8948-31a141d346bb",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "queryGroups": [
      {
        "folder": "UMC Raw Data",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "UMC Processed Data",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"metrics\",\"Dates_ref\",\"Select last 4 Quarter\",\"UMC_Total\",\"UMC_CDKT\",\"UMC_KQKD\",\"UMC_Index\",\"A3_A7_Measure\",\"A4_Measure\",\"UMC_Điểm Hòa Vốn\",\"A5_Measure\",\"A2_KQHD_actual\",\"A2_KQHD_plan\",\"A6_Measure\",\"UMC_LCTT\",\"A4_TSNH_Quy_ref\",\"A1_DoanhThu_NguonThu\",\"Metrics_table\",\"KQHĐtungKhoa_2022\",\"KQHĐtungKhoa_2023\",\"KQHĐtungKhoa_2021\",\"TOTAL_KQHĐtungKhoa\",\"A1_KQKD (month)\",\"A2_Union_Actual\",\"A8_Metrics\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\"]"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"SortArrays\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}